// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PcNrL2X8Fy3ypb+46oa3xiVaXqaGU7q40dayXZ+yFKpTBkzwxWJMAA4EgTl/77",
	"qW4AvAxJaWTLsr2ZL4mGxKXR96cB0B+iROWFkiCtiQ4+RCaZQc7pz8NCvAdthJL4KwWTaFFY+hkdnhz7",
	"dyyFiZBgmJ0Bm7tnkDI3DlMTZmfCMA2FBgPSchwAH3PJ1Pg/kNiYnYHGjszMVJmlLFFyDtoyDYmaSvFH",
	"NZphVtE0GbdgLBPSgpY8Y3OelTBiXKYs5wumAcdlpWyMQE1MzN4oDUzIiTpgM2sLc7C1NRU2vvzexEJt",
	"JSrPSynsYitR0moxLq3SZiuFOWRbRkw3uU5mwkJiSw1bvBCbRKzERZk4T/+qwahSJ2DiaBSBLPPo4Jdo",
	"vsOzYsZ3olE0ycR0ZhOb4WzV819HkV0UEB1Exmohp9Eout6cqs32w5tRdMQtz9QU5VFoVYC2AkhWvCWr",
	"/6dhEh1Ef92qZbvlWbjVkOrNKLoUMu1K9ychUyYM48xN7bhXCxEfoRxOX56ds7BkJ2gn07qpqcWLohFy",
	"Atq1nGiV0ygg00IJaelHkgmQlplynAuLevN7Ccai5GN2xKVUlo2BlUXKLaQxO5bsiOeQHXEDn124KA6z",
	"iSwj8Xakk4PlKbf8LhHMd8Zg+c5vqgDJC/HbW+LZG7AcRzEFJHeN4PXgDJtiF8ttaVbt5Brf3Iwi5K7Q",
	"kKKSNjTIq0VjQZ6qWk+dmBsqeWwh7ypS42VDJdD2eVFkInHewEJeoEk7leAscb1idmxZodVcpGDQzfAy",
	"s+gdJmJaatfVmTWzM25ZwiXqRlIaq3Iy+qsZSMbTNOhra1LFOJtkABZl+c1Y06foXUMaH6Fs2M0p3MNr",
	"zqG2YsIT2xNoJOMZuXkr5sC4b8gmSue8R3SS59Ad5S39wTM2K3MuNzXwlI8zYKkwRcYXDHvhkI7rYRLy",
	"4dc8LzIk/F9Hb/+9y14Ic8mOcz6FPkm4ByuzMyz7HLvdjKJSix4OhCW/Oz1mT98eHTMNE9AgExixd6ev",
	"R+xsjxXczkYMbBJvtKn+veQLdH4a0hm3W3oG2eZYKZts/p6oq93uIpaEiyStKLxzv/g2+fiU4v2S5Nix",
	"TLISLduRI5Cnm+NSZClopkpblKGtidkLZ/2UAaD35kKCZmLClMwWTEloC80H3qplNIrCcnkuolEkjMK/",
	"JU+UTPmm+znP00v83ww1WPOraBRNE+iPzjjF5pxr1ByDcw0w5KhBwkCTf3nKBl4fEsEDL4+J8KGefnm3",
	"NnrvFj30lngx8PKUWDTw8kfkXFtRjriFqdILpyQk0OggajjlaNSNH9SDFCjEBSYs5E0xm4XB6DNqDXVv",
	"qYW5zsJoPe8OmxMsLS7EpXHWYwVHrag1EZCl7aiFXlJMBKSMW1ogyzAvYU95FfrMBmW4ag5aizTF0GZD",
	"xu1ax8w74k3X2UfHSZllmBUXGU+ABm+/f4pZVQ56CulG16O6gEthMU2F86MnjRZWlzC6dblhGpDz91yb",
	"ESuUtmbE5iorczCjKuiZPhf2IfL98M/Xb3/87fXL9y9fRwcRJnroimg0FObz7efbB/gfkk3HZbmFnJEb",
	"vt9y/nn29mfmOjq4gyE7aQicFVzzHCymuSgjOwOhcd0iJRY0wnZND0ahvmD1AiwXGaQsVUmZB8w0YgX5",
	"fT7OMI1mOdeXqbqSjUjY9eS3ue0XmFR4Xe6hoXpJCTVOQZqr9JIhMqWDEsbshNIUVDKZop1Q3uZGQhRH",
	"mWdXw3IwBgNqh4pTH4iYb8Hgusi4Y//VbOGitWjNgdy/QruyiqWKCWks8LQdE8+pG9Le6huzdwaYnAp5",
	"vVlkpWl27kR6b00onlvSDcorCAMDa/RoM/BpwyIxnC1F8JqgO4N1YOQdAfu1MPbWXB0buIw1w7/UhDVe",
	"mofLl3HhpkvJ64FJq+Yrpld1RhZxrfliDXi/EsCLAnYI5H5QwinAHdpNA6NSZtnbSXTwyydg8eUqS1KX",
	"X5aSXBSkt2lbeZcxZEpOnSjPRC4yrtEtUfJRUCiW7KdyDFqC9RWjyuohncImL4q7jT4Q1WXLr8tx7I1n",
	"JbnxNjYPZSv28tqCTA2rGcGuhJ1VyzOJKoSc9ka0xpCnAaP0eXX/KpTzCi1yrhc1RKA0J/jQJvwLeKDr",
	"gXzXHm9yOAwfMSeJp/GIETgYseOzt8QaQiSMEIlpe+NfAsK8BQ4GpEFo7k4AhlrmOzoUclc3bIWiva83",
	"rDB2j1fsBZ4ny2JBAIq6oMo677R8GrOzsqAkjLXQqSF4aip86rO7XnhaaJWDnUFpGn8+BDg98wWOwViH",
	"DVo17HaBqZvw9GTIDVyzojAqKHQzClDoPrJsgQ0aopXLrThKMwPEQVwx5OfeCso/bimcmBnmoUJWbMKs",
	"Qchpf9BoZbXvdNYX/+Ul+ga49vX9VpfeQWcqh6I3h0TXHN6iPvoyD7RzsEIr2ovoG1skfRkyDqU0I3eK",
	"huGzvNao2JPmC+wSkr077p3E1zl1nxm6NzhbUY4zYWb4o2e6pyhuLhfY0gLPSTobA+lrwz2vqC61S78Z",
	"RWamtH3RJLTjd9lYC5gwJWEzExJY43Uf+b10GudZhnXEN6gjGAmlqS8kgClYSuJmkBXxA1TuQsXOu8G+",
	"sDPnIiNbCW1YaZCEIyETITEgsVylCNoRdnh0YIjaEBAxCRgxcykK42rZxtKIyYxLCZl/Q9tgOaSC23qy",
	"5ajluxBOdqNEo2jCjUUHGiaPDqLdeH8/3o5GEY2NrXfj/b14m/wsn0YH0Xw33v+OmsxDzh/5RxjLmhOF",
	"8ZfcU4X3ojNISi3sgk3ENRqHHztmJxlwg2nvVPMU4gbi8kTuEQU1RftdivZ7KOosvR5hrzsCPvqYUNuA",
	"OMuRdi6MGItM2PtEi/d1p+UQSOM37bmhk3eExtvrtS3PglFfSIYAJQS7ZgFOYaieCJ1fcY0UpFrMqeLZ",
	"LMDOIMujEUb8NANLL/NCGWqP6f29C3ZI6duzqLOmVzUhS29eBLqWng8UafHVPxzVS0//VS2iM1JY0/LU",
	"tMS2ABqYeTWwMpwBfIiUBD9CSz34FGdtP0zFFFD7UbWXMpnKVDoZk3/j4E3I/hoIp4nPB7xrbQUPlK/Q",
	"MrrVl6Nj5t6RMxV5Xjq3WRlJzN6UtuRZtmBwnWSlQWxAKIfS2VcEDg6YmfHd754dxHE7Z/WP+R6kz79L",
	"OIy3dycTePZ9kqbPJ+n3+/vbz559v83h+V76bG8vGe8829/dTbe34Xv+P8nu7vPvvhvvP0v3b6kqmf40",
	"BsNHHU98+UHWsWNUFyebsMo7UYom/UH2UhSnXPZlT2eQz0EzjW/RK1SxrKpdh9FToSGx2cKBOkeZC20o",
	"hD82jdWYkrhCBkXpmbITcb0MfC/K7e09+GEn3o63Gf1IdmLv7fsI7wu9VWH3o+hdMdJiBNmk7af+mBvR",
	"EqJRtBPvuPi5un1QVFpeFsFM1FAkuSizbFiNnfq3GVvH7c7086FjPmeQc2lFUumcSEFaMRGgA3TeiXfj",
	"vRFG7u14e1MnOxsxq+q2k7o4zJROgWpriO6DFKaaF7M2nUNkLgW+eVUnqpzWChWQw5qc5R0lNlFZpq6C",
	"9SynaagWus6vLiTXwKRKAdWCNRSLlkSLDIQxbJrxMf5JdquM7xpfyHcN63QtHRhN2XhRZ4VPne1vhGzw",
	"aV5mVhT0ROkLWZkwe2oaJrvR2GYdCB7NzagL6TeXWrtEAZ/G7OU1J5NBp4MZPJ9Stu18bV4a29rJii/k",
	"HUWi961kqC2p+h1t+GqVYQ6syIYNgNMiA70wIuQlqeYTDNIBNqX3TzJqMl74wXpfntQz1Eu8tc4+WGN/",
	"9Pr6vWvr67r6n62ufmsVzVfQ8M24t4bWdLVxpXXk6yqA4IBvphIMZ5s5l3wK6R3bTo9UsPq4+s+jlX7u",
	"UfV50KLNl63XPASOHtT26jhlv77T6+Z5RuJKqTU5HPe2lV64pfYerXCZat9kjfFgWeb1gCv57WU/cRTm",
	"7Xry5c2lmsI+9zDEKc8i8vwabKn9IRCSLZq4T8hTJZ/Y0EJZ0m4a/AGDYKLSPmBTTjFrgZT94/z8JJCA",
	"betzgE6UI7bNxIRhwDDusKjbPKITKHavcYQO4cEU9DocPng4HDgfctg5z9n1VrU9Oj4WoIe3ETRw0+8W",
	"c57MhITBqarjKNUEKGghiYaL6BUXWanhIgqHYNixJ8ipgDAM8sLiGIgyhGFStQ7e8FBOjtkhOyUyWZJx",
	"jZk2HagmNfaLJTUel2hfYEhzG3l9v9++3ZA9L2vmsbcEAQ7YRXRWJgkYcxGhJ2+s9LOrDQKNTS7Tzfpc",
	"0e2QsS8L8gv3bqLSgNGtZ2mW/en6psyD3ZQhxnYvyoTHKwK4WiDvq671s1dh7GPV9/olGiJO1H8HZziY",
	"fvShk2qIv3MDPedOVtmcGhzTbVX1bRusUC+pRgmZumEpHU90+TodvEY7tFWG0k1bhGGHJ8fsFELWchsT",
	"iQMdI8KnrMpFMHqWpFiNmk19kIZma2qbq+oJO2MkHrr6kaYYhV2pImHIBoZa1E07Mm7suebSOGaKfGCP",
	"GdsxK3IIAMjTaqu+kLrYjEzzjhopkZT3tPIKDMKbONa9oiEhHlYFqHBm0h/FRB4F0fGxKq2nuCKvNy6o",
	"sUGXk/4I0rv+/tXHAU3G06qlS/Ha3LjiBrMoNuYGUlYWbtpmQvVsvzehGo7MTwmxbDDXot7eD3M+MSut",
	"dLU7VIN6O3CrqgovPWr0kcFmeco7YnbFh1Eo251rDAGveGZgxN7JS6muZNMJ4/toFFGDaBT5FquWztrU",
	"+bGWnoahlx5XM9226jt2LStNE80MtrG6wwLxNmDsPz958x4og8JfhxZDJWlu82nd/AVI9+wVHc/uDkB5",
	"kHD7y60fwfWdcG2o6dlCJvTHe54J/P8p+rHSHssTraYaDKrMO0zGHaPPCkhC0ze+8vv2SoI2RNdcJPAC",
	"MCQLgxEMO60mrpdSqyxD7H3qEEFjvZ137eV2u/Yy8Ahd6YQOg5+JKZLWnWmwTcXywRaVLAZbtKk+hUIZ",
	"YZVe9EoIBTP4oiPG5stKpK8yABuERT/6hOuE1hCxe9AUtHuyqrh7bKYqB/ZWgOloZ122Cw7ceW2zkHYG",
	"ViSNQg0V+Gd8DiMmaFMBQ0omjHV3HuZcC1WaCnB5HM8OaySLKScOUN/aUhP2oT5pOmKBsJveYokVsuwx",
	"/jd8QRsPYBGoo9MrDWj6zVkmcmHdtgswWeZjV0GjuomH/ZC6jLi+tFBFLop+ms24YTnmw8ShBhbD2Fch",
	"OFXw30uokusx0ZFikBfG0AtX4vDgO+ToDZyOnKd469Im2hmwCsnUAuYutZBwTZUIggbVIaOK3UeOTbTR",
	"hu7QCGMxIaOxkCwP9QvldDywzK+0XbnFdSczLqeQIrojFtgZl4yzCVyxXMgS2UUyLbgxkDqWBIkH5EN7",
	"TBW33Q6rOw1F6wyi9ay8ElmGJLrNxoRngVOe006WE6EN1RELJTGSlTIDY9hClY4eDQmIipVWXYL0F4wl",
	"A61xOS7qDlQCcnfRxO2XlX3XPM5bGmXKsUHBSuuVy9NJjL+aiWTG3Jah9eYDqWsSBB2W4msDEJ46ZQmV",
	"8tTtJKI4HFcNZJAg+Bphp2U9r9YRiDKsdGE2XFTywwSmZzBBQEjGI1OmcmEtpCwtqWBlQAueiT98FaBJ",
	"KMkxLzKwwJ6CIE0fQ8JLA0xYV9KwLJmV8hJHUvXbcI3HhjSaGm3U69HgWec0cHlNbiHCfMpKArJWdP2U",
	"dHy+E+98x1IVSn+NOZyWY3oqUYy4iOqWz7Le4Mr+BsaKnFz935y1iT/A14hVhvIjIo6oSFfBe5xXA3nK",
	"obGtCp5Paf8Drv0t2Duz6psVss3GfYjuQZv6ioBYDiA8y1iB1k811t4g4mxChP1p7OG9GPlv3zbRwG1P",
	"7Zxqlrwqnvdf5us5atHZYfGNHSxZVL5QJNB7x4Ho8Sm8sTwv+v1ChQR94RaBj1tKujrUSyGDj5nLGwB1",
	"v89801tQ3iFz3i2pvEurbN0A0w0E6I0iBUPHQagoELMTVZQZ3dYL/KYrtzE7BZ7SkZoVQaE7U/EJ4n/D",
	"C3Ldrhp/CYuQynS+KhEiudJTLtF46YCHOwuJP5+aRBXuqXPIG82djI4W9X+mgAJK48qgL/v1AnNMB/uk",
	"1Ng24JapK2lCXdE9x+SNXVD5cwvnuoiGb5BiGGwF8t7vM/i0xzORpq2OCZlGbvHENOqQjVM4cnidq3io",
	"E26Tmc/1kb5qR6xfJyaEe5eciRqwrLqYbxW6M+RUE0zylD4V4E7p0F+5mpNpgT9e3Nns5XbWJza6Ynyi",
	"iEF0W6Z/1xMVs59Ulxv50pbS4ehQ3ClJqCLyZPRVGzrnlZe4/XXu+N1SkF/vAK53ANc7gOsdwIfcAUR2",
	"+Zsr9FUI567GwDXow9I5ePfrVXAU//z3Oc5FraMD/7amF7lDYV1Pj9N+B//u3fGLSgwuC2mU2X2gr6F3",
	"zN7wwu8wtNrXmXqM8Z8OkUi6igl6EYXUBCn5jcpQISIU4idYRDe4ePryhi/J+K82ITTJooPIAs//t7l5",
	"V4+Ii3Bbb1Sk0Cpj58BzuvKaeR6ghrR6d1K2X9pD/Pq0r9uG97Euj3fnsACNxV0DdsfL6EsMauI+AkYa",
	"DukUzRr7NL/jcaX0ZaZ4auILeSHPw4ZWyGGehu/4bdSbZPQA1XIKDfDjkJEGdMLkzK3y5RV3VjYTCUi3",
	"/+V5dljwZAZslw5Et9l0dXUVc3odKz3d8n3N1uvjo5c/n73c3I2345nNM4rqwtLZ6iX2H54ct648VR8k",
	"RE10oTQ6iPbi7XjH5wyk6Fv+GFKVaU3BDpwybR7gYzzRyjig1zx6WvkU1HzqdphlzY40d/i+Cm2u9uSg",
	"/sB/1RB5SyodagaGvh9VxUaXkzYreN626hEIf+aYXjaqT77Vk1CzeuKrDt7RFxrmVAZtl3QGjKyqaXrX",
	"wHswy82oD4q5mo8rDmLLxNaVGCr7+FJbQNQOaQntz6G3v6gFc9ALO/PX+vsIpV5nftZHpNYdTh+FY4NU",
	"OCJ1URpZfAnsyQ9PRuzJD/hftNgnf/nhSbiacBFdwmLnB5LbzugSFrt/cT92L6KNoZXSjB+3UlSlnF+L",
	"vMxbFTinedUim3XBuuZ3XtdgCb+7gtOworW6Y3raUnO4Fsa6QZeKq5grUl2t/dEp09B7IdF31uVM4tCg",
	"Zohc2Baf7kyOb+jKqaOc/Mfu9nYIJ/57Oo0veW39xydk9QwrHvek8/cUsJbqVj+hg9t/wEkHUFLP3H/n",
	"KQtglYjY+QJEvJO8tDMqXKSOir0vQMUrpcf0HTMiYff5FyDhXCn2hstFEIlBUr77Itw487nKO1kl+q7+",
	"waem9ZmXm1F0vRlyCowhzWB8M6qi82qRmbXOYXVDcQjUXyAGr0PwOgSvQ/C3G4IfL/x+kXD7ZcLrFwin",
	"XzB8Pky4LFTvPUzajWO8Ewm7gdA1DbcfXUkJjP27ShcPbTRurXXNyuoSbjq2uvN5pu1jULo21s9urNuP",
	"YaxHSk4y4XZ51u7hjmy6nUlvffB/3Wzdt+bl/0mDo/rO5GCOvVKta3mLuM95UY5AO3x1ltvyXbVruV8a",
	"+Qk5/leXfT98lv0puee6uLIOGPcJGPuPMOXPyrJXqpTpOmJ8VEJJX9YlIDfo/VuJ5bH7Zwe+Fvf/62fN",
	"c933uXs0oF5U68vEtFVWHQV89Px4iNx1jvxf7PIePS3/RnLjrW6teTlD3vqAnufGOckMbO8/c0FHxdvu",
	"8q502XX6Oh3maMW5W35tYH7637299WfK+oZVKSR7ayf0uZzQ1+cSeoHvj3TX6j6W/CPYtRk/qhnfkcqs",
	"bfnPZ8tFafv+fQ73D4XdB8j4PmuL/gZgVHUz4G4c9cjOZw3c1n52DdweGbjdG6jdslHagmefGgHon/Cj",
	"AdcgaW3w6+L0g+GzWwy4RmUPYb1Td1vuGwFGa9td2+6XxmPcJj3Xg+mK80r2Sy0f0IKJoC8ChTZp6v//",
	"acetW3fDVzpZ9aheZY071rhjfY7rsxaz6Atrq4GXdg3rIbynu0z/bVSSvjr3uD7lunbIa4f8336wlqpP",
	"W/XHJwbRa/Pf1bgPjj0Ln3f4HLsRaxi7djVrGHs/GHs/Q24C2q/QlNdodo1m1x7tz40t7+fQ2ijzG3Zp",
	"3z7CXHuPNfT6c0Ev+nAdfTOSvIz7oNgWL8TWfIf+9R8/VudLz8GF0T9g3PvpkKXzWTe/3vxfAAAA//9W",
	"d9iiW54AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
