// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xde3MbN5L/KtjZq7K0R44eflysq1SdVraz2tixVg/vH1EqBc40SaxmgAmAocy49N2v",
	"ugHMg5yhKFuW7YT/JOIMnt2N7l//AIw/RInKCyVBWhMdfIhMMoWc05+HhXgH2ggl8VcKJtGisPQzOjw5",
	"9u9YCmMhwTA7BTZzzyBlrh2mxsxOhWEaCg0GpOXYAD7mkqnRfyCxMTsDjRWZmaoyS1mi5Ay0ZRoSNZHi",
	"96o1w6yibjJuwVgmpAUtecZmPCthwLhMWc7nTAO2y0rZaIGKmJi9URqYkGN1wKbWFuZgZ2cibHz1nYmF",
	"2klUnpdS2PlOoqTVYlRapc1OCjPIdoyYDLlOpsJCYksNO7wQQxqsxEmZOE//qsGoUidg4mgQgSzz6ODn",
	"aLbHs2LK96JBNM7EZGoTm2Fv1fNfBpGdFxAdRMZqISfRIHo/nKhh++HNIDrilmdqgvootCpAWwGkK97S",
	"1X9pGEcH0V93at3ueBHuNLR6M4iuhEyXtfujkCkThnHmunbSq5WIj1APpy/PzlmYslO002ld1NTqRdUI",
	"OQbtSo61yqkVkGmhhLT0I8kESMtMOcqFRbv5rQRjUfMxO+JSKstGwMoi5RbSmB1LdsRzyI64gc+uXFSH",
	"GaLISL1L2snB8pRbfpsKZnsjsHzvV1WA5IX49S3J7A1Yjq2YApLbWvB2cIZFsYrltjTrVnKFb24GEUpX",
	"aEjRSBsW5M2iMSE/qtpOnZobJnlsIV82pMbLhkng2udFkYnEeQMLeYFL2pkEZ4mrFbNjywqtZiIFg26G",
	"l5lF7zAWk1K7qm5ZMzvlliVcom0kpbEqp0V/PQXJeJoGe211qhhn4wzAoi6/mdX0KXbX0MZHGBtWcwZ3",
	"/5ZzqK0Y88R2BBrJuH/JNIxBg0wgZudTYNggGwvISLoowVRg1VxIbpV24aA0zmFI8VsJ7FrYqZDOFnyr",
	"hmXCdNiA5DksD+ct/cEzNi1zLocaeMpHGfVcZHzOsBYbK+/iQh8UDN7zvMhQAv86evvvffZCmCt2nPMJ",
	"dKnUPVhbL0F+51jtZhCVWnSIMsjx4vSYJKFKGyI2+63kmRgL0E624XElcrZl+YQpzVIxAWO3yaBxOUHK",
	"uCWzzUq3sEQO7Qn/VvI5OmAN6ZTbHT2FbDhSyibD3xJ1vY/mIuRrkBM7jQ72lqSxYG701k1xTas698Ls",
	"EcdY6ZzbtvHE7M26lsOOZZKV6KLcnATqdDgqRZaCZqq0RRn6aKECDEJcSNDRIApy4LmIBpEwCv+WPFEy",
	"5UP3c5anV/i/KS4vza+jQTRJoBs6YBfDGddojQb76hHKUWMIPUX+5UfW8/qQBtzz8pgG3lfTT29loXdu",
	"0n1vSRY9L09JRD0vf0DJtY3liFuYKD13hkKxJjqIGhEjGiwHN6pBaDYELSYs5E01m7nB0DhoNXVnrYW+",
	"zkJrHe8Omx0sTC4EzVHWsRKOWiGVPGo7pKILR+dASx0nyDIETWyLV3HZbJO/VTPQWqQpxt3auVDpmPko",
	"MXSVfegel1mGkL3IeALUePv9FkK+HPQE0u1lL+3QAMXsNBXON580SlhdwmDldEM3IGfvuDYDVihtzYDN",
	"VFbmYAZVRDYDBjaJt1u+7UPk6+Gfr9/+8Ovrl+9evo4OIkSh6I6oNVTm893nuwf4H9LNkttyEzkj1363",
	"6fzz7O1PzFV0uRjiiaShcFZwzXOwiMFRR3YKQuO8RUoiaGCKejwY2boC4AuwXGSQslQlZR4SugErKFLw",
	"UYYYn+VcX6XqWnq/14Fabla77heIeLwtd4yhekloH7sgy8Wg31qIGLC8EcbshDAUGplMcZ0QqHQtYYpJ",
	"sHjZwnIwBoP00ihOfUxivgSD90XGnfivp3OHAESrD5T+Na4rq1iqmJDGAk/bwfKcquHYW3VjdmGAyYmQ",
	"74dFVppm5SX04FcTqmcFhCGsQgk6sEaNtgC3GitSyWzeNv+oHlB0W9wOgrwlaL8Wxq5MJLCAg9MYfnEC",
	"jZfm/sA8Ttwsj+R1T6dV8TUhW43yIq41n2+y8a8kG0cFu/TobnmOM4BbrJsaRqPMsrfj6ODnTyAKFimg",
	"pOaG2vaDeD6saVt5lxFkSk6cKs9ELjKu0S0R+CgoFEv2YzkCLcF6Oqta9ZBOYMiL4vZFHwa1LJZfFuPY",
	"Gy9KcuNt4iBwauzlewsyNawWBAHzanomUYWQk86ItpjGrvIxWKBFbLZZh+VA0+F2QpawIvNw4Zosuk4a",
	"W82yFzSIlCmZwP8up2XGZV4zYMCTaZ0qC5lCATIFabN5zBDzrsiFQwZcafjnD0F+zSyFssoqmyu0ysFO",
	"oTSNP0mvd3WFVfZ/Q5ngsau+t+wfkwZGX7PtCtbfDAKsv8vQWsCZmmjhkjVbaaIZbMSRBT91Mgz/WEEs",
	"mCliKiErG0HFCTnpdoAthHahs65YJq9w0cN7T6S3qnQ2OlU5FJ14CN1MeMsuTl97i4Y2nii0ItK/q22R",
	"dKE9bEppRq7h4vQ4IJZWq1iT+gviEpJdHHd24glFvdzRiX+DvRXlKBNmij86uttCdXM5x5IWeE7a2e7s",
	"zkyVti+a/Sx5AzbSAsZMSRhmQgJrvO7qvbubssBMo1/FvkDtTEmmTXWT/CZgCU9MISvieyCmAiHlHVeX",
	"M5xxkZGphzKsNDiEIyETISW3guUqxfwREbAHqs5fFlrkXM8ZxqMBM1eiMI7zNZZaTKZcSsj8G9ouyiEV",
	"3NadLbo9X4VSNtdKNIjG3FgMYbXb9bmnd40HkZny/afPDvhjSJ8/TTiMdvfHY3j2XZKmz8fpd0+e7D57",
	"9t0uh+eP02ePHyejvWdP9vfT3V34jv9Psr///OnT0ZNn6ZMGeDfRQbQfP3kS70aDiCaAQ9qPnzyOd3Es",
	"s4Bp8dnTeJcQQXP0tw965ttf6vQxddrqgcp9hG9vAOq2N+9m9eqo2bCZWzBVN71HIU+N2wvXxzzEsiGW",
	"NLkahd2Ohc6vucbRpFrMKPI1o+AUsjwaYBhMM7D0Mi+UofKIBO/M7eBI355FS3N6VQ9k4c2LMK6F5z18",
	"Hr76hxv1wtN/VZNYainMabFrmmJbAY30aj1c2x9gl0BtZdBLaM2/caApAKMGqm3mZD1urEYW9xLX2yut",
	"m8H5sJrrXgLFvCB6MeA62vOwihHJzFqUfMx+hLlxKC/nFtGgKy4kEXhxtbZi9lZmc3YFc0gbbDbXwHjl",
	"jSs8GviTNu31OZxf4MGdZ3I+DcXVlN9eJ1cVnFcXJsFgUkcXnxfLOpIMatYMQ22IKWUx0TwFii3dIfdK",
	"FKdcdkGhM8hnoJnGt6i+KrJVpGpoPRUaEpvN3ckGNzIX6FD+vw+N1YgvXIZNMXuq7Fi8X8zILsvd3cfw",
	"/V68G+8y+pHsxc6Ndw68KxBX9vpR410z7mJUGio0v+4IHNEUokG0F++5QLf+Ip71nVY5g5xLK5LKCAQm",
	"RrTdxbYgnsQDthfvx48HbLaP3Q91srcds4rhG9c0IlM6BWJhuEwrsUw0L6ZtjXgLvi1BnlWMQuXqWo5k",
	"jcT5sB7b4kYEG6ssU9fBthchFSpN11joUqILkCoFVBprqJ3mRzMOoyRvkfER/kmrShlfNb6UF42140qm",
	"Po0dzWsEt+VW5nZAblt5mVlR0BOlL2W1wNiWaSyo7caOW08gae5hXEq/J9HaXAipYHwpV3AFK7nIXh7y",
	"wTnIO/OPG+7xz8Y9rmS8PNuFb0adfFfTr8SV1dHCrnCAy8gylfAsmw9zLvkE0luo+QciQj6OV3gwSuFL",
	"sQlfkkhYsf13Vh1m6zZWet08TUZTKrUmb+HetgKhG2fn3rFDPF2dNdqDRYXVDa7ldBcX+VHo99akuDHC",
	"rrXdJykvInLbGmyp/S43KQbXpwd2qZKPbCihLJkmNX6PESxRaRdALieYskDK/nF+fhKGgGXrvMOpcsB2",
	"mRgz9PbGHdVz+720xW4f79emhTBzAnoTy+49lvVsgB8uHYJbdjX1enRyLED3c8sauOn2aTlPpkJCb1fV",
	"fnvVASra725cRq+4yEoNl1HY5WfHfkDOBIRhkBcW20A8LAyTqnWyoEqLY3bITmmYLMm4xhSCjrOSGfvJ",
	"khmPSlxfYMhyGwi02+muXshelrXw2FuJTumAXUZnZZKAMZcRuuHGTD+72ZgCkiGX6bA+OLE60+mCMH7i",
	"3k1UFjBYeVhg0Z9u7inc2z0FEuzyNYXweE1us1bIu6pq/exVaPtYdb1+iQsRO+q+AdEfTD96V71q4u/c",
	"dHGQ62x59LbpNkC6yO41MvuqlQCzDUvp/JUD20oC47gObYVQlmGLMOzw5JidQkAtq4RIElhaRPiUVVgE",
	"o2dJhtVgF+qTAtRb09ocOyTslJF66OB9mmIUdqcKE8dSohUtw46MG3uuuTROmCLv2XjEcnTyOGQvfqy2",
	"qgupi80oNO+ocSSScE8LV2AQHmJbd4qGlK6wKkCFQ2H+rBnKKKiOj1Rp/Yir4XXGBTUy6HLSH0B61989",
	"+zikgvGkKukgXlsa19wgimIjbiBlZeG6bQKqZ086AVV/ZN6idGObuRL1nm/o85FZa6br3WDptdueOy1V",
	"eOkwo48MNotd3hKzKzkMyPDUmJ1rDAGveGZgwC7klVTXsumE8X00iKhANIh8iXV3ldqj820tPA1NLzyu",
	"elo161v22ipLE00E25jdYYHJMmDsPz958w4IQeGvQ4uhkiy3+bQu/gKke/aKzp8uN0A4SLgN29aP4PpO",
	"uDZU9GwuE/rjHc8E/v8U/Vhpj+WJVhMNBk3mAsG4E/RZAUko+sZzlG+vJWhD45qJBF4AhmRhMIJhpfXU",
	"9VJqlWWYOJ+6jKAx36V37ekuV+0U4BG60jGddj0TExzack+9ZSqR95aodNFboj3qUyiUEVbpeaeGUDG9",
	"L5bU2HxZqfRVBmCDsuhHl3Kd0hoqdg+ainZP1lV3x5qpuLxO+pbOrtWcW3DgzmububRTsCJpsCy0rzfl",
	"MxgwQfQ3hpRMGOsOdc+4Fqo0VcLl83h2WGeyCDmxATrHG9zRh/oo3YCFgd10kiVWyLJj8b/hc7ojABYT",
	"dXR6pQFNvznLRC6s2yAAJst85Ogv4k182g+pQ8T1qewqclH002zKDcsRD5OEGrkY3VQKGZwq+G8lVOB6",
	"RONIabPUGHrhKA6ffAeM3sjTUfIUbx1sIlrfKhymFjBz0ELCe2IiKDWoNksrcR85MdH+ELpDI4xFQEZt",
	"4bB8ql8oZ+NBZH6mbdoV551MuZxAitkdicBOuWScjeGa5UKWKC7SacGNgdSJJGg8ZD7ujlyQttupc2ds",
	"3IFDr1ovymuRZThEt0eW8CxIykva6XIstCESsFASI1kpMzCGzVXpxqMhAVGJ0qorkP56p2SgNU7HRd0e",
	"JiB3J+ndzk7ZdY79vGVRphwZVKy03rgaRxvZ9VTQ4Ugg8bvlA6krEhQdpuK5AQhPnbEEmjt1e16oDidV",
	"AxkkmHwNsNKinVfzCIMyrHRhNtzE8M0EoWcwxoSQFo9MmcqFtZCytCTCyoAWPBO/exagOVDSY15kYIFt",
	"gSBLH0HCSwNMWEdpWJZMS3mFLan6bbinYAOMpkLb9Xw0eNE5C1yck5uIMJ8yk5BZK7ozRzY+24v3nrJU",
	"Beqv0YezcoSnEtWIk6iuMSzaDc7sb2CsyMnV/82tNvE7eI5YZag/GsQRkXRVeo/9aiBP2de2VcHzKe1/",
	"wHt/3/NWVH2zBtpsHPhevsdRn4EWiwGEZxkrcPUTx9oZRNyaEGEnFWt4L0b+25dNNHDbwZ0TZ8kr8rzv",
	"rMstp1vqwi4tmVe+UCTQeYibxuMhvLE8L7r9QpUJeuIWEx83lXT9VC+FDD6mL78AqPpd+pusyPIOmfNu",
	"SeVdWrR1I5luZIB+UaRg6BQDkQIxO1FFmdF1pCBvulMYs1PgKR3NWDMpdLv/n6B+f7jJs/FXMA9QZulO",
	"f4jkSk+4xMVLRxHcCT78uWUSVbinziFvN3cylqyo+243BZTGnShP+3Um5teya7vvsLltwC1T19IEXtE9",
	"R/DGLon+3MG+LqP+K3IYBluBvPN2vIc9XojUbXW6xTSwxSPT4CEb50Vk/zzX8VAn3CZTj/VxfNWOWLdN",
	"jCnvXXAmqmdl1WS+VejOUFLNZJKndBfanSehv3I1o6UF7ujr8k4tt9MutdEdyhNFAmJYqFMdZJjdQ3XY",
	"yFNbSodDLvESJaGKyA+ji21YOtG0IO2vc8dvBSG/2QHc7ABudgA3O4D3uQOI4oKk1MLO6dq7c1cj4Br0",
	"YekcvPv1KjiKf/77HPui0tGBf1uPF6VDYV1PjtNuB39xcfyiUoNDIQ2a3Qf6OvWO2Rte+B2GVvkaqccY",
	"/+kQiaRbdaDnUYAmOJJfiYYKEaEQP8I8usHJ06cFwhFs980cTE2y6CCywPP/a27e1S3iJNzWG5EUWmXs",
	"HHhO1/oyLwO0kFbtJcj2c7uJX7a6qm17H+twvDtEBbhYuBUzYO5sGF01V2P3CSaycEgnuKyxTvNDBddK",
	"X2WKpya+lJfyPGxoBQyzFb6itl1vktEDNMsJNJIflxlpQCdMztwqT6+4U6CZSEC6/S8vs8OCJ1Ng+3SO",
	"ty2m6+vrmNPrWOnJjq9rdl4fH7386ezlcD/ejac2zyiqC0tHghfEf3hy3LplU30ODi3RhdLoIHoc78Z7",
	"HjOQoe/4Y0gV0pqA7Tki2jx9x3iilXGJXvPcaOVT0PKp2mGWNStS3+EDErS52oFB/cHxqiDKlkw6cAam",
	"zGwjNjpM2mTw/NqqW2hcZLCLpR4FzupR+ACU9If3YUY0aJvS6VlkFafpXQPvyFluBl2pmON8HDmIJRNb",
	"MzFE+3iqLWTULtMS2p+Ypmu9dP6Ybl/OQM/t1N9b7hoo1TrzvT7gaN0x6kE480fEEZmL0ijiK2CPvn80",
	"YI++x//iin30l+8fhRP1l9EVzPe+J73tDa5gvv8X92P/Mtrumyn1+HEzRVPK+XuRl3mLgXOWV02yyQvW",
	"nN95zcFS/u4Ip35Da1VHeNoyc3hPH4Y6dxuATXIVsSLxau2v6piG3QuJvrOmM0lCvZYhcmFbcroVHN/Q",
	"nUA3cvIf+7u7IZz4D4Y0PlW08x8PyOoe1rwcRYfnKWAt8FY/ooN7co+d9mRJHX3/nacsJKs0iL0vMIgL",
	"yUs7JeIidaN4/AVG8UrpEX2oiYaw//wLDOFcKfaGy3lQicGhPP0i0jjzWOVCVkDf8R98YlrfsbgZRO+H",
	"AVNgDGkG45tBFZ3Xi8ysdQ5rORSHQP0FYvAmBG9C8CYEf7sh+OHC7xcJt18mvH6BcPoFw+f9hMtCdV6i",
	"pN04xpci4XIgdEXD1UVHKYGxf1fp/L4XjZtrzVlZXcLN0lrd+zzddgko3SzWz75Ydx9isR4pOc6E2+XZ",
	"uIdb0HQbSe988H/d7NyV8/IflD+qLzz2Yuy1uK7FLeIu50UYgXb4apTb8l21a7kbjPwEjP/Voe/7R9mf",
	"gj035MomYNwlYDx5gC5/Upa9UqVMNxHjowAlfTqUErle798Clsfuu+pfi/v/5bPiXPcB4g4LqCfV+vQq",
	"bZVVRwEfHB/3DXeDkf/ALu/BYfk3go13lrnmRYS88wE9z41zkhnYzu/401Hxtru8DS67Sl+nwxys2XfL",
	"r/X0T/+7s7f+TKiv35QC2Ns4oc/lhL4+l9CZ+P5Ad63uspJ/ALtZxg+6jG+BMpu1/OdbywW3Scdx9BP/",
	"8db1Exmq8Qdaz3TeH+d0rwt73WxqSF3/96cdNWjdi1hrV+HBXc0mYdokTH+whKkobdc/1OX+bbm7eFRf",
	"Z4ORvgFiqrpr9dX52A0VtvHsG8/+wFTYnamvFUdPWoTXp0YA+lcfqcEN7bRZ8JvtvntjvFYs4Jrnuo/V",
	"O3H3j78Rqmmzdjdr95tguFas3yazdR8reMMqfU6vssk7NnnH5mTsZyWz6JuV6yUvbQ7rPryn+zzJt8Ek",
	"fXXucXNvYOOQNw75j35VgdinnfpzPr3Za/NfKrpLHnsWPpjzOXYjNmnsxtVs0ti7pbF3W8jNhPYrXMqb",
	"bHaTzW482p87t7ybQ2tnmd+wS/v2M8yN99ikXn+u1Is+BUpf4SUv4z7RuMMLsTPbo39Pzbe19O384MLo",
	"Hy/v/BjTwvmsm19u/j8AAP//3IAyDiuhAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
