// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a2/ctrboXyG0D5C9e8bjJO3Z2DVwceE6aevbPIyx0wPcOveAI62Z4Y5EqiQ1zjTw",
	"f7/gS6IkakYaPxPrSxsPKXJxcXFxvfklilmWMwpUiujoSyTiFWRY//M4z1MSY0kYPZdYFvrHnLMcuCSg",
	"/6I4A/X/BETMSa66RkfRr0WGKeKAEzxPAalOiC2QXAHC1ZjTaBLJTQ7RUSQkJ3QZXU8i9dGmPeLFChAt",
	"sjlwNVDMqMSEAhfoakXiFcIc9HQbRGjPaYTE3Ky4PtO7chbXB7G5AL6GBC0Y3zI6oRKWwNXwokTXf3BY",
	"REfR3w4rLB9aFB+28HuhBrrW4P1ZEA5JdPSHQbFDjAd5OcvHEgI2/zfEUgEQHvroSwS0yNSoZxxyrLEx",
	"ic7VgOafs4JS86/XnDMeTaIP9BNlVzSaRCcsy1OQkHgzWoxOos8HauSDNeYKXqGmaMHgz9lq9IBotVVQ",
	"tZocmK2GCu5Wk7eQOqrEeZFlmG+6qJ3QBdtJ7aoTz/R4KAGJSUroUpNNioVEYiMkZD4JIckxFaSTVgcT",
	"U30ZQaLqRzqBgTwS+hVwKleKJl/BkuMEkgDZDCaV+pzVHJ1dvMk7+wSopN6hBPd6Ep2cfZiBYAWP4S2j",
	"RDJ+nkOsVo7T9P0iOvpj+06EPr7WAwOX52SpSHkGfxYgZJuY2n0Qh5yDUFMgjLj9UbEijARZUkhQrEh0",
	"oRYGaMFZpqnt5DiaNOgX5+R34ELP1Jz4+OzUtqEEFoSC0KOszW+QILM8w8eJqKAyNMwWCFNkqGiKzhW/",
	"5AKJFSvSRPHrNXC1kpgtKfmrHE0gyezRkGpVioVyilO0xmkBE4RpgjK8QRzUuKig3gi6i5iit4ybQ3eE",
	"VlLm4ujwcEnk9NO/xJQwtT9ZQYncHKpLg5N5IRkXhwmsIT0UZHmAebwiEmJZcDjEOTnQwFJNItMs+Ru3",
	"uylCR/MToUkblb8RmiCidsv0NKBWGHP8YPb6/AK58Q1WDQK9La9wqfBA6AK46VnuM9AkZ4RK/UecEqAS",
	"iWKeESkctSg0T9EJppRJNAdU5AmWkEzRKUUnOIP0BAu4c0wq7IkDhbIgLjOQOMES72J07zWK3oLEmjna",
	"o7nti/aZMmeyL2sNfG++a3JV73xZ2vCWZWENsdz2BMd5ztkap+07COsWCJCda0GEJpoXKOkI5AqM0OI4",
	"xwoLNAegyPX3Lp05YylgqmByrceye6ZjqchcDS5JBghLK475011hUZvJXI7RUaRI8EB9FyIG98VPm+7Z",
	"f9q42RsCpmrlwas0xXNIDRqTRN+4OD2robf1SX1uM4A93CDVpPYnyfSdvnEcLYE1icGDwm13i2bsfvYj",
	"jBNGDeBtvJx6ggees0IijE7OZ61bQIkhF6XIcUFCErz61WHUiC2a4j1RpfdWqs8/aIbTcyrDnRQe44Jz",
	"xc7ictF9J81ACLzcrZrYfuiKyJWV1oRFnk/EavXQoa6I0F78xAkoDUK1lmrDztF6siOHDceF3EitK92S",
	"1gS9AkrU/zFNDhlHP2OSaoHJiXKup5blVNdoEtlOLQGuScC6dasy0qbiN6Sf7KP6mcOWqn+xBQrIUKOU",
	"c8dSDpGQBTTlN51borhe+dGwm7Wi5ghzjjejlPUwUpbaXCNjDZNxzLb34wJOrarv639znOfAEeasoAnC",
	"qBDAD2IOCpnqQpugjCWQQoIYRZ+KOXAKStghTCMR52TqKURiun4xPan+DoDQZCDwOSfc2AtAXT0B2ref",
	"Q4KSgpe8YY1TkhC5KTm+B4dCAXyWHG+TPspD09q35pmog/NaDYywNAQDwt2nCnVIrrBEDn9aM1Q4zFle",
	"pPqn+Ub/enx2irSdiyu86v5aklCnLMsKqe7LKLCvS86KPICiX9TvKINsDlysSH6HMPVHG+/Suy9WgOZY",
	"wD9/OAAaswQSdPb6bfXv307O//biuQJzit5iGa/szaFk+mmplBNIlfiNsE+XncRXciVfrJlvOmQDperz",
	"d0F762kp8Htihrp+9DfmgtGc8s8Cp2RBIEHWqtiapiABVvvh9NXdU5QHgxPdhl0dH9RnwgwAPGyZfudp",
	"Cne/lAbr5KXA4m1mT1ZZSoZdO4+txniYACU4PVxgkhYcnOBu16xXp6C2JnRDMUSIojIjKeGbKEFng+Az",
	"EdrUXGeQPlsLniQ7YNs8NanQhRiNocJ0nzNQ6gGij/bTYMB62UYf2lM2qXSvFme57rWLlkJbsJ8VPGcC",
	"EONIxCwvKbQ6yT7GK7H9NeUsTTOgiqaOl+b/M6BwhdOA4D6JtmiPZVNFGk4fUrcZo4CwYnbSAeeUM63N",
	"lAKzOijOADrdT/V0eqC2KeiZStAq9RMSI5spuJxuyhCmTK6M7n83eqI1rSjZsq4tGoi3G/KdH+kXoGCE",
	"hvDqp06emi7LnoZR1bFxhYU2Qqh7K0FFbqYtF06o/OcPQfdUl9b697lSW//R1FvLGZ+JXuu8sRrb67Og",
	"X6OujE5CBFcuv9r9IA9ugOc5Pi54AVpBTgUMdnU0xrVjNX51Qzd+rnkpanjwoPN0+eM4BiGIuZtqf7gj",
	"eoa50F3PNzTW/3i/Bp7iPCd0eQ4pxEr9iCbR70q0VYtVSo11G+YQu5/N//thoOJaNWOnnn0GORNEMr4J",
	"gqug7GxorclvLNf3cwogOxap29ySXmkDnrde84O/6gvIcnV5WYXIIkFtTiEky27fizRpnlj1s7kXiD2w",
	"memvOFSsoSilTBEwRipgzbra3MD8Xnc/5auNIDFOPfPmaHwZXUxP3sVU8Yb+F6D9Zg9XUui+MqPVHNwd",
	"UQwOA11GiEEhK21bxFusVf1AnINBS5APTSJh3PF7hzm0MOicbnbcbpydMLogyy5scaAJcEg6uZpjaVYs",
	"ThzXNJ8pxrQgy2kP5bA+z1Z4BUuhDepydnby2h7VoDVEqIuT0dNXgdYGOLWx/C+74TpVAiYnsjN8pucW",
	"B0eze90OZNm5vR0D3Ty4p9IytVBM3Dy3Ix5vA35oSM/OsfzAMCyE7//xI8A+UFHkOeP9Y8CCM5dTBFvL",
	"eYOtFTAdzR6E5crD7qaqre5iMr+LUbZ5aMeStxG9LDZWkB09SN+oB8ns7/tzp0g1+HcWNOQwITkA0q02",
	"UISjD7M3u29kM+BWQLriRMOgNCSF9+cGqptDUiq6HfDEedHv7NQHMtfMJEqI+HST7zPIWN9rPzRCAxtq",
	"NeWgFrq+uOmOYf1vzG2M8QknUum4e0ezhib2g2XbrdXkoVYPoFCzAzLU5luMPB2lTSFaSu1mxaa9bkqo",
	"uDdRn2SEYsm4N/bGeKvs4I4aGIUe5o9fiDRy+Rlna5JAZQDZ9tVvpdftHGIOctDHpzQlFPaY9Vcp89Bn",
	"IaJs3kxVKkN7UzIs49UZlupSr7uHc/NjdBT9vz/wwV8f1X+eH/x48D/Tj9/9R4hp7/ZWsJ7Xq2W/JofC",
	"Xu1taUjNY3MozK1pzVKWkKzPvP/V3rCGhTBpFM5kCBoz/PkN0KVcRUcv/+ufkyZajw/+7/ODH48uLw/+",
	"Z3p5eXn53Z7Ive5kTl1uPb/VN8CF1Y/KxYedXQ7Zb5UwIjkmqYmNjGWB08pjg7eY8So1ux9dBCwPOzx2",
	"pQXbW6IG0/hJzFAGzKC/yYe+n0ev23838Tjg7rXWLAZKjnVKyF5K3cDTV35TO39Db9YBJhdLjHVjiztv",
	"p1Zr7jFA1f96ElnRtt+nJnw0qea2X5vY5D6evqYIUZFlbSGTOuH7OPZ3uaQWvXHVYiqU+iB2yyb3kG5k",
	"zVGt8N0bWyZulGPUNYQnmb3Xt3E4uWgGc8asV+aMXQGH5P1isaecVoPCm7XV5gESaK1LYbUmH9xAc20F",
	"gfaADFc7esGro+xRi1UniTgsCpJow0FByZ8FpBtEEqX9LTaNuPXGjeBpjWG39bHXQ3F0bYVxATStcPiK",
	"6hRyjEmyEUPNmESnr4YMpQDW7jqz/jCc710nZHr1n6CpyPooKdfRhqL7BNQZ262bJO3hdwH1t3f4a3Dv",
	"d/jbQ3iH/0N+wV6ZWJf3hXy/sP/2nLH7nPTalN4UgVZ/1uDHDa9wvdU/sER8emg/sNKQkQ6qax/rHCvp",
	"N3RMEsK1Y3yDVB/FMJwMr4avj7n9nOg5PgZ9z61YgDYsrS5bEiJtDJwCFvRnW0Xc0Zo7eqqfnKe6dZyG",
	"Oa3bn99uKmRHcNCYCfnEMyFbdBH26QW71d17rS7j1fDQjr7glvQy6bTlh9H79416/8IX124OoLqZffY6",
	"Gvthq+8zgSTmS7BWxjZniAVvTxkLbiYIZQz5GQjCZAO4DQ8y5qRhGN47gkyB2g+PHUbojo7D7NG9uG11",
	"ww8666VocD3ZnpLi70Fro9pJKtOhuScn7VQIuAFT255n0mHHDG61tkm1HSJdSQ+6v8t12KnWldHz1zZy",
	"uj2g/rmur1lZIRmDbEa1bFTLyi/0SRmmiplPblf90mOGReuyqS5O65/Hc/zgMnS1D73uGMOwR2H5GxWW",
	"K3YSPsdbhOKFat8pCAubNrVzaXgOqcux0vRmc6ZCYsl9ZGc0/RRhTthMK3RAd+O6Q4j2GocJznobesdx",
	"6N4TBGo5BKfpBpFSxvJ6oBVeA1JHRscdxS7pPcMULyHT5wy4dhrpKgZXK5KGtKChsrBZzL3LvzrRlsQ2",
	"XMOdhkHRaqEwOeetap13V3NgZ/CBG8R+sgX2GeSsdBgFLXULnApoAtonk9YN7ZZa8DTsCfp7znTCpbob",
	"MybhH9pjatI00YfZm52aghrZ9gkuNRjr19tD1t7l60krNYbImRrhS4f7K1DYy62woxixZ2j1sFFdfQwV",
	"AhC2VUI2NEam5ZIGQ8g0s53BmjiJaVe2UAle6+NJl8OtmeJjcBJ2zFUxjQMpL8bTmAfEx590cRXktG7O",
	"mDQlSlu4yLEQV4wnYcS7VuPwK+TK1G779eLizHi4c8alb10vhwv5vD+R3AgjvwMv/aftic8/kdwSvysD",
	"svY/CLkNZCp6YeLizbk2PiB7qfcCXA3+CTb9B1ed+47NPkFHZQLddCuY7y7RcmFLs+gTtmOq9iFpMZeO",
	"4Nxb5S5KtAyylwVJ4azTw6796u6GJCmgqxVwsCxF5IwKba4SknHtyyo72tzKWsbhNMxY7pmPiWKxIJ8D",
	"FU4wLwuHfJi9sWV3WAYC4YW0frk5Frp1ik4lijFFhMZpkQD6swAdhsBxBlLrekW8QlgcXdJDhcRDyQ6d",
	"zvC/def/pTuHYNzGSMvt2sk73Y53M889L+5Vje/2izrvWzqj94Wvz5neJoZinKaIcRSnjJrq0kOu+4m/",
	"oNDd3xl0f6sHlJiwvs6tkLyAXVtuxwjv+NbEg1tditDjB7lNxgoqz7okmg7h1DSIHMc9RFdbNaz6YuJN",
	"uvPQVKCHkVjXFdtWI5SZ1PJPsJkY+0OOCReGmWAO6PjdK0im6HWWy80hLdLUuKSRU1aVHiXjlVKAVoQu",
	"24qNbn4z3DW+fd3+qKEzUKr/QeOOarFa+hwEclqyWbXYULkCSeIqNQdlhTCK3sQyUEKX2lwntI1rjTlh",
	"hSiVTQ2GmKJjL1kDb4ymyGi60SWW2AJ9qfTuCXKAXQeVQ0loEXLD2BY9/hy0K4B4tdjU3xilJCMSMXPb",
	"VW9+aM0RcZAFp7aUrRfeUVZHstLZCguUMQ5aqEJ4jUmK5ylMkWJvhnaIQCzHfxZQWv7mGo5EcT1dwMyV",
	"kyojOKwB0TNPYaMwazWaCGMUlUyByQmszV1O4bN0bo8SkgrvJwYrapOwUssFEVIp0HosBZa1cFklDBzK",
	"7EprCTV63fEK0yUkSAcBankCK11+AVcoI1SXh9Sbm+s0bIMSt/XOLGsqGTpsK8GEokIYKx8RqNxJg8or",
	"kqYKRBNIHJsAPFlh2kku3NQ81JLNBBU0BSHQhhUGHg4xkBKVVtTkLEOYIvA9Ux0vumSYUEKXpxKyE8WU",
	"2gTY7lPGzZR0Joq5UNut2jTJWej1dlSvzahNseKJFc3c9rsFTtHpovrSkZDL90osa2Lc4rrkURP1UZP6",
	"S8gdUAIVJspUU69BrxrGbUUKC4kKqo8UTRDLiLTVStUgAjjBKfnLPGFTA1TvrnkfBf0diKb/OcRYSYFE",
	"N2vz0aqgn9RIrGrVKLD41OHHutM/qvVwsKgzdNlck1kIETdZibMsszQxxR0pWr+YvvgvlDANtxqlmsPQ",
	"PqESqNpGtYhSFA5RyncgJMl05O935gySv6wBLmap2j8NxIm2WJceCTUvB81Iu8aWzPFDxu0f8BnHslc9",
	"t5DW81Znx97NMyae/bV1wqo2ha/6XaUEyVzxF13RMHhfmfNlz5XQX1g+qW8I29eU6wy4nChlsspZ2zOw",
	"repsiuttSm4bjmKbRK4c6AXJQEic5X2zktTUKez56XJLFcFjZHhYXPKQmqcG67K1ZEFi5FUYLNVJoQQX",
	"a/hHZ81SqEb5nKIZ4ORACQg9iw7eOOLQFRYyDqhPsHHyTFo4CUApjd4tzvgSU3VEdcVTLGHJuPrz76bK",
	"pvrVsN1/lNdxaH/Ddgpfc7Z9QxkpVxSCsqznJMMSsStdilX7Os3vSnhDl9rpc6imuoyQQXLXe2b+/R2Y",
	"kDppx+JPT2szf4grZqy55zPh+UarkgWVy7Wf4eVMSb1eVH9p+h+gDbM8rKDaDBvFUJniKQozU68wKk4S",
	"nbyXp0ZJ4ZCxNQRLooYTII7R/zl//w6dMY0JbakJ4l0TXxhGI/tIhnCiZTELzbSlHrC822Tb9s/ObJ2o",
	"ftn8oTAmVzyqV56r7rx3nvo95aG3KnR1no+vN1d9n6zzofXFagaiQM37qrWMdt/kAfOhdxKXRFojUPD0",
	"zbaYJ2e+OdKLIPuFSN9UybhiTdpkBVXBsjEYZQwqe/JBZdUJGhZZ5n13u+Fl1cDhGLN6ez3QrGwjY9jo",
	"w4eb8cZu9LwZS24/Rp59o5FnDZ6jhPh+BZ8a8S59ii717nwuVlXfHVB3BHI1ewyL5qrkld4hXd4nNw/A",
	"qg92v1FYTh4+ToHLWRGqXFtbQVsXWxUZpgdlxYNGyKJGnxo7nE9TdBlJXjmjuZ+5ydbAvdxNvAaOl2Ay",
	"3bXLwL0FPoeFOuF6YkKXU/SzJoEjZ3BZsDRlV8Zs8kw805EMwjwnNUHPMvODtcdP0LOV+WHFCq7+TMyf",
	"Cd6Yu64qTHV5mfznHyJbJR+Dtahy4LG6uZYdWmnVrlBnlmWcJ5wsl8BFEJ1mTaaE8Br6VDqqbfq5/Shc",
	"KcKN6O1VbR11O9BOCqtN5tWUCBb40zVU+tWQ6JykGrizizdjZx8Dircapz+GYhYz83iB+ufJ2YfOIxx+",
	"ydpUpehUrzsqVjijctd33SbnKozSxVhaDXtYScCO1ezi/dvg2mFo6MDEdWCXwoYY7FjeNruD7oS46jVF",
	"753H1fyaa7eoIRItBRmmMtgWUfHegODl70awbDjO8pTQ5akSYW2iXgcrnYO8AqClCUV/qtZ1Z9wRvS2E",
	"lsMw0lccWRuPztIkvvsl/V4c/Pjx8jL5rpN9Nv32Hl4m/l4GULKNLZ1vaBwSKKrWZkmTBXBtvJfMeN+t",
	"J1fHfpnIbM8AIpmJy9J+Zyv/aj2nrHA2qkqjMWQ0hvivAQ00h3hf3rZBpBramUTG0/qwhg377YbGg69Z",
	"zelH08Y3a9pocJDOdJLuWG9sIr11BTVXX43Qpo6OTnV5W9djckllrSJbdUYlJtSE6YXufhM2T9klFcXc",
	"fU7UCXyN45UBpTGWCQFwIyiQjQRySW3QjqsA/ijizdt5M4FCdjaggdtebXwPixLvm27TIJhOu1Kzz1DL",
	"UsWvbmYnwvvxvq1VlZ255IRlGZFbHvuMdQe0wmJl7BH6cUv9aF945/s+pqlHb76j2Ri8T4jVAIPXuVjt",
	"lTqVc7LGEn6DzRkWIl9xLKA7Ccq0G81JrM7Kbx9D7lMdoF1JSnbd6Pz81/55StdhxO+ZdiH8LdthSb6j",
	"pAu1+oZr26Vg7Jl6US0qSKUdDMkyIWI0UVlwauUSRWkxTlMba5Uw+ky6HiZO2gui6llxpo9t13/BWgdt",
	"26PcEQgVftr2GGU4XhEKnVNdrTaNCRQO7F1xqZ/DKjhcRhYeGzVLRBVODlkuNzbQVcfJ1tl3FYR+jGbm",
	"hd04xdyEX7kQBrtYdTDQvFBYBhNxy9bAOUkAEbmjfG9wO12gWok89F6H9R+hy+i80E+qXkZKLPFWeueS",
	"nlKLDjBNDsr3ensccvfo6ivfJlp7nzecT7wjSWdLKlJnEmE/w3EQ4BLGqGNFNWC7Ovkgd/Xx8sQ+Xrfe",
	"rA3wonqHumnKjwdErirC6I0fTUyjiQmLw8bRGWZlan58u4amxujh8JtAp3oMTqPDGIfz4Oaq0I70Utua",
	"98BotfpGrVYhptQuVBCu33jhavegqxUTUN747nwudMAA2/0EgBm/D3glr+yXpVR7eHsHP9vHvFKu2HKp",
	"W4jFuc1Xq27xIaRQTva1ftzKPEKSkhioMUiYhJjoOMfxCtDL6fPI6rWRO1lXV1dTrJunjC8P7bfi8M3p",
	"yet3568PXk6fT1cy06VbJZGpGu59DtS++YreVgWpjs9Oo0m0dpdKVFBzeST2wReKcxIdRd9Pn09fWGOc",
	"xqk6pIfrF4cxcGkL7zqGYTYqhVCtWPN7LaNPbdyJulzObf3emRunfOuF0dNEP76jPlZ9bVevp8sL1bO/",
	"fP7c5UqDyVT1Hp46/LdVYQ0J7DRJOEmhlTH1/jeFox+ev7i1uUxF2cBUHygu5EqnVyVGb8NLrf200a/V",
	"kGWI3Wgxox+mFZ8M47kqE6KZRyANytiEqnoiSkIwJUacibtIpXcHGauXnztuT7IeQQ2g0xJNbQHZ7PTM",
	"JUs/s4mt1qSQc1jrRPx61rB+aCw6ijRArkBYlTuvZLxyp1pnO5QHaNKKbXSA5CSWVbKv9nfZHG+XaGnS",
	"/Ai35fyn6BUssEaIZAjWwDdl8YQQoGmtiMMgaC90JbrPJCuyWuqz2Y4SUD8hu0q2vqhS4nXmsMn07UZ/",
	"7XNEFvW9h89ESDNoI9ddh22uQOcZ2ixKSBAWHjnpAA0vj1xjqBNfJNMpMhWefGv09y9D1uiPd8hN2odK",
	"6wpbuMvzu+cuP+EEeQX+HyVHy5kIlhwwef84UGe8xdROdGJzeweiiRvnJ5Zs7nCrDR4qAUHyAq5bxPbi",
	"ziFoSFEaLfq+f/n8X/c8+XHKAScbnX7CLRRPhObVpD/e/aT2kWtGFylxz+VuO2rXk22y3eEXxVive4l4",
	"IVGjt0y3S9TwPd0dE+n7QHuPy+vAVljqvjXvl/c/KqlSTfrD3U/6jsmfWUH3F2MVwzCCYykf6BqMjec/",
	"WpQ2A5wMpzNT+4UugeecUOmTnL1nWuONdPe1011eBOlOVxhokF4vJjczn96cyw2gtbqYsZP2Ho/88zCE",
	"/6By1xOSeB7VSe8l6xz6LyiF1RBTMql6INWFVtS4ROvs9tNOymeYBrCK9rttXxmnqN6eemiOUYfkCavo",
	"9354J9EPL1/exypzzmIQAs9TeE0lkZvbYhyVZ7pbkBW1AKLBckVIpD134T6DRIvh0uxAvjFKt1+DdHtD",
	"euyQc/cjyVHaHQ/CvQh/9imfPRyXr+yXYbNW1fpE3ZMGsTtckl04fEOErNpGx+PX6ng8RguS2v0Iwupe",
	"0rIlUGtoNp9CKSh9gs1Q0M2XP+uBapD3r/43+lL39KXeLunqcq9Dt9/UiH0o8dQwsNHJayWA7+9FAnCF",
	"PLruou1WHHshdVhoysa7kCLt4PfsJ/ZnHW2UD+2VLem0LaAO8b52ELEvmA7Rx8ovHrs9oJuYn6Tqs0sC",
	"D3hTOyhnBjjpRzcFJX8W9WT0kXy+evLJlR4UentOxitX4b6koSRMQ7rzcOaT3Dr19L26D/Sq/3MYimu1",
	"+a/tZf5g9Dp6J+7xjPQPHOjksrrzY7igH1a8vb8jMorS347H8NHL7ofeEyFBgWxWhjTbnur/1FicA9xC",
	"d3YviXzzcln5ZMoonvWlN/cySSfBLa35cVGkaflylUnaWzDeT677BWTg5Zwd5PjuriS8SWelIvOmX/Ox",
	"lrDdUPedtbo+DPkHsLvlPvuhvcvvGHKAjLfB47kNbhIislNPH+51H9X0b1sFGUxKnjLyGKjpqagko4bw",
	"IKITlHGzN8hlr4Jvu8JCWuG5TzhCpIXyHcEiFe62Z68HcTzGkIzJ62Py+v6nu3mmxrCGPsxse+p69Y0p",
	"ibM1+CCU2HEXUlF7nnsOSegA4F4y13vNPSauP6BiHTpnW8W4IYETbQmjrxi3X4oW+npyLXqdjCepgA8Q",
	"YwMRFxVeg9acwYTWkbR+p2mBI8k9CpIb4IHuweisAeiWON1Xkcizp+jzIBT/kBLXaKJ6kBPeR8y5jYz1",
	"0KntpZE8gXz17jU/NKsYs9WfeLb63izjJo7I3bwiKMUOdyiNAuwTF2BvQoFhSfaREeHTlmfHA+Aza13V",
	"fR8P5M/mw7DVqmx8og5HWyt/q5OxA4FviJBl0+hLHH2JY/L2t528rQ/76OTsYqA70qg19jrMBq7tLiQe",
	"M/Y9Oyy9SUeT2UP7Bx2JtoSpwy/6/9eH7uEZ+/DJPlJW8+2aLoGr+YbULtlBXQaa7bmbvTXRNKxxLLwz",
	"9fB67+OWAhv7v0Me3L3V6pJ4xBs9GQXUUUAdg92G8JTQk46jFLiFgfa/bIdE4zR5Yr9L9sas9+44r29K",
	"7Dnro7Jnt162HI15wySKQPzPTiKfAU6+HhJ/N5L4EyHxAM/vz9rD9gHPSj3EK+M+eOy01WkneDoUdU/2",
	"ga2Wgf68OUyliiH3otFAzYWRVL9G5ueZPYcUwloEyUf3HczjFrdNON9MFaydpDoGPd3f8egfgdzFW3Xf",
	"hxcBHtQ1cW+HY/SCjGLVbYlVXfrAjcILd0hgwyO4RgHsG75hhlJRddc8AkJ6GjfOEyVcjzlyyJkgknGy",
	"16szM//zsAGl0eWJunlLPG92eHj5Noy+IUI28DlG/43O1dG5eoNyhu5cjn7VrRxrR4id1zscZzfzO9yF",
	"fOFNcM8Rd82ZR4XzocPuarTbIe0McRBtoe6GkLMZIrXXhn3sOuB2Kn+S8nQfoS7gyNlCTTPAyUhLIy0N",
	"c+1sISjr+3g8FPXNeHr60fBoYb7nc9Pf57OVDesPvsZzc3cC8/0enVFAfwLntSaaC1bwGMSGxvtZIs33",
	"5xsadwrpVZcnbYqsML3TGOl1DRsja1gfjZGjMXI0Rt7gnqpO02iO3MG1dhokt7AuZ5KsMa+7kbG8Ke7d",
	"LNmce5R7Ht4wWaPiLvlnmG1yC6G3BZ9hmkxt6MdvVdpO8E/UrtRH2gtaKbfQlbFTjlQ1UpW7jYfZK7eQ",
	"lrXhPS7a+oaslv2oebSD3PsJGmK53Mqare3y6zxBdylb3/cxGqX5J3J6PTlesk9AD10Zxa4wc90L8Y4S",
	"oReq1X9Xx6Pi7w2im081J4RDrDqvACf6lH+J3jCDiToSmqdTAf/Di3+1Bz0u5ApRJlHM6IIsC6418vZa",
	"1zglCZawY7G2WyipXK/3dzdMi1lpHmTWVXEhBR1QaTd7n8JsDQNYBaRHz6E+hFa9huDtehIZI5lZVcHT",
	"6Cg6jK4/Xv//AAAA///Bs6k3nE8BAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
