// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9C3PcNpPgX8HO7pXs7GhkOflS+VSV+k6R7UQXP3SSnK92I+8aQ2JmsCIBBgAlT3L6",
	"71doACRIgo/R07JZqYrtIZ4NdKPf/dck4mnGGWFKTvb+mshoRVIMf93PsoRGWFHOXrKL37CAXzPBMyIU",
	"JfAvUn7AcUx1W5wcVZqodUYmexOpBGXLydV0EhMZCZrptpO9yUt2QQVnKWEKXWBB8Twh6Jysty9wkhOU",
	"YSrkFFH2PyRSJEZxrodBImeKpmQ2mbrx+Vy3mFxdNX6Z+js5yUgEq02Sd4vJ3u9/Tf5NkMVkb/KvOyUg",
	"diwUdgIguJrWYcBwSvSf1X2drgjSXxBfILUiCJdDeat2UAms+q8JZ2TAGg9TvCTeQo8Ev6AxEZOrD1cf",
	"eoChsMrlKbSor99806vHSFK2TCpbQJzBrmJyQSM4BsLydLL3++RIkAzDpqZ6DKHMX49zxszfXgrBxWQ6",
	"ec/OGb9kk+nkgKdZQhSJJx/qgJlOPm3rkbcvsNDQlHqKxg78ORsfvUU0vpWranxyy2x8KNfd+ORtpApo",
	"eZKnKRbrgQBPEh/Wsh3YvxCcqNV6Mp28IEuBYxIHALwxUKurLedobeJN3tomAM9qg2K5GnS5Wh1wtqDL",
	"Jpz0NxTBRw2KKi7iXK3C4IVuGg4B7JtCv/fHr1u6vT9+HcZZQf7IqSCxBmAxdTlaCP1+wipaNeeBnxGV",
	"CDNEEgLkkDI0h58l+SMnzBx9db8JTakKE58Uf6JpniKWp3MiEBcoIyIiTOElECVzmyRSHOVZjBXR8+lr",
	"BnPqqYbRn6NiVCBaKWV62snebrF5yhRZGoI0nUiSkEhxoRfdNexrPCfJiWusO+ZRRKQ8XQkiVzyJ+wbw",
	"13XVdhAnFrItB+I+o5gsKNPAWhGUUKk0AAFOBoBzgsgnEuX6haKs47xk63z71XHNjPCgSj0MVSSVfVs2",
	"d+tqqg/h0HQoTwELgddhUBwcvT8mkuciIm84o4qLzZ7JUGc47AO984VGd3JCl5rUHmsAyMCVbW2KBMkE",
	"kXpChJGwPy64gIdpyUiMorIvWgiewjEd7AfIQ0Z/I0LCjI0DODq03yqnfWF+IzEyuzXvOZXlsuyDuNCo",
	"a2A6QydE6I5IrniexJpcXRChtxLxJaN/FqPB7YFLhZXelkYVwXCCgPuZIsxilOI1EkSPi3LmjQBN5Ay9",
	"4ULj7oLvoZVSmdzb2VlSNTv/Qc4o18eV5oyq9U7EmRJ0nisu5E5MLkiyI+lyG4toRRWJVC7IDs7oNiyW",
	"mZuXxv8q7OHKIOE8pyxuwvJXymIgZsi0NGstQaZ/0rs+fnlyitwEBqwGgt6hl8DUgKBsQYRpWZw0YXHG",
	"KVPwjyihmnbKfJ5SJd190XCeoQPMGFcaWw3Fi2fokKEDnJLkAEty56DU0JPbGmRhYKZE4Rgr3Ifn7wBG",
	"b4jCQBgtrnb1aMUug6vTiYQ3+PrDmO6NN7HEN3tVvE3alYceydZ5XtONaIdubu6hI66tTUdicffEonjE",
	"qsB8PeRsBj2A7e/NVf0dHEnXg5AufdaGcG1GKszxb0QrHA9TPd9/CpxlRCAseM5ihFEuidiOBNFARQcn",
	"x1OU8pgkJNZi13k+J4IRRSSiHICJMzrz+A05u9iddS6hSVjIp4wKIzaSiLM4gBK2v1F4FDTjAic0pmoN",
	"3A/cmHJiPc2CixQrw3F/+3zSZMCnE/JJCdylrinwrHHEdfyp6XH0wAgrc7mIdHoPDV6kVlghB2NgzjSc",
	"M57lCfw0X8Ov+0eHSALGaNhDe71zTddomuYKz5OQysdcpCBXeQryjCTff7dNWMRjEqOjl2/Kv/96cPKv",
	"u8/0cmbojePnVwTpl2lW8JqUJMDXY/8+dDGshipUjmS+ViSEOMDCirdBHdIhi80lgzWJ4k6YPobgA6n6",
	"I8cJXVASg8opiKA5DRC794cv7uGcvEVIvCSB6/4efgeo620A9SXwJpyTNTK9vP1bQZVKmVe5/8pD0XuB",
	"9ZbDyru3nuLuHgBTI4XuNlcux2akr+Dm2i4UzjLBL3CyExNGcbKzwDTJBUGy0EIVu9Sr168GpkwG4A6a",
	"A83PrBH5RKWSTYLnnVAYRe2ITXFuWsINcS2IFyAfhFyauhoZOsA0Ft+Msk0fLPcRbYZ+ZfySochrKAja",
	"B8iReIpeEEb1nxpArzBNzKKK+zdMdi6WMbn6oGnqAueJJmRXVwHJ3b8l3t6Cd6MYt33n5bHGRGGaSHhY",
	"OCMIa1RU7hpEuRDAmSh92I6n1Zf92CN1Nc0UlupUYCZhplPapiPX7ZCiKTEzFUtTRV8SG35Jr8teT8UR",
	"ZlytiKhcA80YbeuxwhyK1HSkuYpf8hQzJAiO4ZrZdogaXNH8noMOnvNc2RUXywsSOj4HMhD/TBgx73d4",
	"9zPH4syWRUtDbKrQuMQSKKJ+y2KUZ2Za/73//rvgey8IlkEBBj2ZC0oWT5FpUbIUbs4tOWinAwVHN6oT",
	"FN1IA7uBYrWOAcpoW+0KpqErVwCgPP9OZGkjnCcVsljAaAqXki/QqdAC2CucSDJFVpPtK+r198l0Ag02",
	"Vs3XVmfHqv3qhq797GvVq9Bs3sd1Bnspbx31JQxvN44EGnW++6shh7BLTQv1R9DY0nlC6v9wdOMICwlN",
	"T9Ysgr+8uyAiwVlG2dJpf/XZ/qZZXw05Lf1Y61JGIvfzmzxRNEvIu0tGoP0L0G6/IFrwoVKLFbrTMHi/",
	"ZIInSUqYss+pt8nWJ3dImwJCrS0K0B2TjEuquFgH4abB1fqhAVz/YwHoVwkhqgXa8M3B1oDSA7z5wQe/",
	"+WXoIZiruKBLZ6p0ktowg8PPVAW6X027e/1acO4nJBJEbdT5kCWUkWvM+otSWagbwEBw9vJTJogM65j0",
	"d0SKBshQeyDUevg4T0AXQVMiZ2dMvya2BZXo4zfI/vdxD22jN5RpmWwPffzmI0qtnPNs+29/n6Ft9AvP",
	"RePT82/1pxd4rSnCG87Uqtpid/vbXd0i+Gn3udf5n4Sc10f/fnbGTvIs40Izz5ptwPrm6aV+1Ct2ophm",
	"Ko3+5QmZLWdTGIYytNJLLsYjF0Ss4benet6P2x/30DFmy7LXs+0fPgLgdp+j/TeaffgB7b8xracf9xBo",
	"oFzj3enuc9taKmDudp+rFUoBhqbPzsc9dKJIVi5rx/Uxi6n3ODEW9OpefihBol+VH7wuZ+zlJ5xmCdGQ",
	"Q8+2f5jufr/9/Ft7pMGH+CCXiqe3b8eZNt5CI6VZRwC959S019cxglWgkB7QPbf67hvK0Lzz5veqySdb",
	"rSWNcOLZv0dF7WjVGa06O+VDPJwTt32uYa8JMc5mtIYjTNNRLKxnqYlew/2lgK+P1y1uV9bjYeHkW33N",
	"Llc0WoEADz2dDql/GqmwUAGR4G0xi2uDnNRXCFPh0T3xbNiZhV226ocHIHaA8VZezDLoAKtOOSHBUZoG",
	"7qBW4B8ElLLTZ6l6HzQ69t4H3UhzNIZ6axnckRiQTH1/tFuRUrs9turw7oWqYfzaAHngKVVK0dLAq9W/",
	"SRAWE0Hi1vfOPXbV4Vw3b9w+FWR1ns5NSp60PuX2s/+iWwkafo44YySywmZx2M19L4+PDl7aByGM9LpF",
	"+WZ42ozaPOHrYVjswxfhse1ndPhis4FrQK1swp+0Hbq+7NQkqrH39RSLJQnA5qTQqZv7IPVqUFyVyVBK",
	"1IrH1VvjS/zvGQGhGKR7LSWuj4kkqilQ1/ccWGL7bg81YRRUrfvVMPZiU9cj4GplEHjYe1ib2SJ/E+Xt",
	"74O3cFIuorYTS0Sr2F9sp3kSNySfRnVZkM5yolshnF17vx7t7BirRznXAcPCRxlLWdVUlU6975l0gulA",
	"dVFwwcUUwa/FvMGv5WJaPnsrLAD2mi5ItI4S8gvn5w5ObsM/kQUXvgpnf6GI8P5tGhyTOed+i/KHTUBR",
	"WUpj6kCb+mpah/EX2DaOt+YmcDZ7jBPX7Q7R0RKyciqzhBsjY23L18PC0CDetSovqlGZ2itdeVoKT4bm",
	"J/DMb3xwjuL+b6c0JTxXtV83xNDaZupYVvtc2VHge+c2+9v7e+9vXcKkv60Pq57WNQIScqAov1X96Mzv",
	"clTGPLjXnHcSg3zkrOptdIj73BzippuxrK1M6rU96cy4707CjnP+V2Q+zS0CK2Ds0buTQjxqfSjToAn+",
	"tDIINLLKIDEs+MaM27mp64jh704Gb6EmeLtthDFaf3lBl60uazF8q49lDAdIrvDzv32/h5/NZrOnQ0FT",
	"nbQdUIWpcCNwFQSsj1GKsnzY7a6uw3Av00lM5flN+qck5UPxKzRC3QUnyyfFoHZ1Q0HbYoPXiKApi9Ur",
	"GmJqgG1ofDP0759Y2CDGA0EVjXBy7SDA0EL9GMPm13Ly0FdvQaHPVbam+s13XPD03C1kqUaUcIetqFTx",
	"tb+pfqvBD2s9yjjwwkYtMY1uXvMdZdZWPHzuoGm6MT0fyBzYJ8Covw1iB5g5PWrlmlozoN2F9Vsevoea",
	"9TG0AbmWiqRxi5bOfAQHTBfZaJfUvAdgeD3CSvOCsisaDxqizLasbKahGDdGXrcOzV7AKzZFl1St9Fum",
	"/9SCn8wXC/ppikwQ24okybZU64SgZcLnbjJYP8yOl5gyqZwfXrJGCccxMVPAmlL86TVhS7Wa7D3/2/fT",
	"iR1isjf5r9/x9p/72//5bPvve2dn2/89Ozs7O/vmwzf/FnqY+kMFDbN1xBMaDaSj770e5lpdtZLItlfH",
	"/+qrksMitfRC1y0dQLavZjuVwDQx5plI5Tgp3RpvSjYs1+DbJUppfgPmvGlPC+ACbhorNh69ZuwZ7jFb",
	"nAHA0di9nOFHwzHoNeqDdyhVc76xXbS0f8sVS4xmwJxG7VqKTT1CgqU6IYQNcWq118L4cBLmnMUtnRru",
	"wVroiK6lAdrwASj6VJ6ATdmmjaWaxoU01PTQKtgGDFC2L8hVvAmlilts4x5mVFZVxcRJGDF9MPrXr7jG",
	"cDblekuoeVfNvwHtbOb17bfeXV1hEV9iQUA7YvyztJxvtl317rl9u65dg/P1vj0DxS3YdDdK5BG2PrwD",
	"Z8Jwzg5fwX3EL4kg8bvF4pp8fGWt3qyNb95CAl+rXHrlU1MfX/lc2UHge4DHr2B7kAkoWlillIkTorHc",
	"yXMam3wWjP6Rk2SNaEyYoot1p0zqa3rC5Hzfa6GfPuO2OK8P27ibGjghm/JPnCt0+GKToQocNPsPr/Nd",
	"gagnDlEHTlBXIfkgKfbRXEU7njS4vh7DdAYtjTchZnhpwi6ADhiaCEmgoiSP9ZfLFWHud6cAnhMU80tm",
	"OWNNt2xYT/PEXbsT40bb+56azRSti3fluv2vesAWX0tZZdZ0+7biyvC3SY4rm70eOW4O0UaOlY1uCAKs",
	"MGhlp/wFhliyd7l6t7B/90yT16HDlUV6UwS++rMGO9dspNWvDXLa7n/QYANcOiDrF7dICFFIEJULRmKD",
	"cAuiopVGvyIjGMQJdEpL5U1uCzgeEMTkRcVNG/uYC4LPNUZ37mS+Rmf+us4mTUNreblknYf6DBZv19S9",
	"cMUVTlrUivqT5xsZmmlgUJmlfp8TdCzj3AWdevQYgGoauKz1869tOEiNqDx/aNf7mMpzEyvdxMgMq1Wb",
	"qUFA2M8a6TaezgyGr47ZzTTAHB/C7v5Uihxm3U8SfomDGbACjap5t8gFSWx+PH5JYr0428HQJ8GTRL9c",
	"FC5IJvhSEBmQUZaC59lP63Y9ToLnJEHnZA3cZEaEvsgIumlAF0aucn7sVrxZBHqKP71n+ALTRD/CLXnc",
	"TEI1D3Md0FHRs0AMlx7TQCLsc5xStt8zZS113ALlrDlXcQy9cwb5ndyPi7VEYPJMY1v7gopkGG7uwtHa",
	"+JAqjiKbg3GG4Ha7DiWT6JIMxAhDdAnX3MyF9Rsj+trbsedrhI0SJ2dUzVAZsFT8CBHhe+ijNLE/0qTz",
	"mKKPqfnBhPPoH1bmBwhcghtZKmif/GPv993tv384O4u/efqPs7P4d5muPgT1s2VkYpkdsZ6Q1bXYtvql",
	"Pl6sHPPEdriaTpYii7aBEYdUhNvkGr63ZXdf1dVNQwLL71hMiBI3gjebS2406UgxZ9Mk6Jtl1tapJB5d",
	"X8Y4pK8wDqmBUJuFJDW73242uZZ47hCj3Nq0TJURlpQLQuHZOVBJzYqcIiFZycSNdyRruVwRtSLCT06C",
	"VliiOSEMuQG8M59znhDMrJUIvu63kG54yrCy4VH+BJdYVsYeZqNwPX5aD0qJrduK4G0FHuwmicX3nWrQ",
	"jAQ5Q7IsWTua2NCFtcgJxQENulphL8pgs6pDZaPJ+L48uGtl8EwGWS6bXMjob/mlJiAMv379NAB8lqhx",
	"Vioamvej0XZLOv9IsKYHHOukCBPcULo7P1+yNPlH/AcqQFirzhnD44vvgo677EhWQECX1ObLt6SdysLi",
	"viIM6ZvsPcRUhl7MFtqvoTrsyFsU9i0NN/NhGfQ0lBzNRnSpYIWupv1p2vy71MzVNts4A1szrRi5Ac3t",
	"8BbZLHVaUyLuOFfbpIs/XPFLq5nQJBCwDhzCMHqV0OVKoQNNEnniX1NPYm5WONBkMSq0JxsJ9/u5ggzx",
	"nqCd0x7x/v3xa3c67w9L/MNLvdBcGk+7TLhX5P8eI31F4PVPKDs3aVFgPvd2dRg6r6u1KJQXgbIMHrzK",
	"CVphMOhKABz7r4UrVlEmT7RvbHVZlUtjUttf42qYobc9lNx2L2IN8aChl4TqBVa4XKaP5noAwy1gt3Q9",
	"PlrQBPINodPXJ2HEN4s5J+vORfxK1htNfk7WfXPXkb0FKs0lDjr44SRhAGVw0eMaLfg1D93bl75UXFDV",
	"CvKy7b5r2g59n0soRkaV3MdtCEwCzIjhRPX7C8QjjgWRhQm7d+PoiWMqV1wqLUXuZVyoAfEPHQAqFhs8",
	"eXB7aShYW9NIQnuXPbJ/WUU6wqvp5BVNiPXdMCTd2aNtxllwH0ttdjnnIjbMAl0Z+qAYrvLzcTF25ef3",
	"biK7QsfW1u4fZ4q0vRxZgilDinxS6Mn701fbPzxFXNQTMtsR3FXQ2N3GSuh2L3U3/VPTpUG/syY3gzK6",
	"XKEFHJhlht7kEsQXQkGXcjaBxZ1N9IrOJmZNZ5MZemGMEfCoFY18JwH4aTK1XQIpEKbGwhQGid7eljTG",
	"pKlnjLDLApuEC31ieUoEjdDhi/qyBOfKrKopCPGYdE6dEWHjPyHT+Qz9B89BPjSLMZ5CqZbmFjilCcUC",
	"8UjhxDEtCcHghPMnEdzlMnv2/XffwdliI89ENLUdNJkL9/nu+bOnWkBVOY13JFFL/Yei0fkaza1pBRWR",
	"7jN0uEBaAC0gNjV+Q9XNwLOg96llgBJgenlhY1i7YRTPJU9yRQq7qLuctdQ26C1XxHBFRQ5ksBLqpiCb",
	"zAniF0RcCqoUYS2JsYnoPDR+CRm/b/2+hGy4BaoF6SL4fDTX+so6jHiGFCu3xWOo8GgvGe0lXg/Alc1s",
	"JKbL7dpFYMywwrr4VFVSw88jJj+8Zro8iEGqEUOzRxX0l6qChvM9Ng44barIZpvNtJDWI7T08qnJAUaZ",
	"11Le8tTVlXQ+RWUo45w47yESow0ciEoiGt5qh3odttKrUrdbHRbreFxpfJM6l4qkWdKqgnVfa5kWmm6c",
	"dan1PnKQ1r23ww9P3Q/T7bf1Ynfe6Gtf5cExodB6igjw3jhJ1oiW3rMeaqzwBQERBbQpkasU03SDMqWE",
	"LldW0G3I05spzIsTv3lIZdxwGt8kDcnUYcyg16hKrTbU0ENZDRodk4wXbrZB69ICKjLUQDyk8oQb2mWO",
	"yEWLW/WTjEMSfs1LpFyRpxB0Y1L3D8tdooe2bYJ7Daa7b+hhllQd6+2E1ijIggioYwtaxp+pqsbo25pF",
	"AbLBc6aOChHZeWnuNJw0dRtHgswt2pJGArYhgzUXEwehLWnE69I9E6as2ObKB7ZdWPdldJtEwa6mLKTQ",
	"kt/Xfe73VymHqpT4anr5wrNyTC6obC38IuxXCFeTXtnazvU2srQWi2/MOm3zx54OLFhfy0XRvxqbf9he",
	"xNDEkKMvckrO0jG+Fq+06Aw9B01LapV5KVEBH2CvHPNgwqjX1kkclc2r1ukx/Vk6KKMtuVX1T95Kt6r+",
	"yVoe2lpt3dxHOcCpDa3rUd6O45xNrj5A5ED1x4C788VvWNzEveAlu6CCM3ifL7Cg4OJ+TtbbRubJMBUQ",
	"eqg34zm750zDOFyMMG/BeS2AaEBXb6gf14jZGmGxzFNgZHIJMdcKsxiL2OQJQXLNFP6kL4+WoaAyoVWS",
	"SpTaAixuJokymkFdsyU4EE71jaKA3mt0SYRXtTxnMREIozmWK7QdGR36p7A7yCUX5y9oi75SfzTRKC6u",
	"xGw3ly6MTOSMOQnSLnQAqctZK0mplDobfteKbvrxepf113Lx+3iFW65619VV5WW/UuOlJG5E3z8IuORI",
	"iZzooysrMwVpng1UaXk8Q1tu4BNvsVpwZxR6Ip8iPT+o2LECcw5JrOHFvMJ6CxIrKq0pAX4tlj5cZ1Ex",
	"igUI8gaqe2wV98K/lgWogXGPVpgtDc29AZjD6nSehe9uURyol4FtvIYe86YX+cvp6ZEJzdWUICBV4Fkk",
	"Am/XT2DDckYyJDhXtnB+gPmS8pKLuI0BM1+N90KuVsZa1FxX4UZcjBeyIZ/TzKiNfiOiCHgL2JTPaWb5",
	"bld388LrEHaJVokcBIzT1yfG1wHq8w1duh79nKyHj35O1sMH5+dtKWfg0+1Av70u6qmthwp8Yt9c/ZzB",
	"pKU8VoMsrZTKBko3zKxkmHyjqcJRkIz0CjSKewKNM2EX8dI23wIsRRJ9L0v+rssOuIk4IpriiJMmsK1i",
	"vGYR6hBUTBqy0OZFYY5/f/zaVr/lqSb5C2UDEeZYwtcZOlQowsyyMQT9kROIJhU4JQqU9Xm0QljuobPJ",
	"jqaIO4rvOKXvP6D1j9B6iIGyIvIUx3f/Uo67kW10/ZqqiVXlSRhWWW5oMc3BKg24tXDuHEU4SfS7GSWc",
	"GSk1eJOgMrmJoW65U3o8c98MK8hZYtJ9uK6a/YWKhmUZ3kISRu8lWBDASUhfcHczDQMMchK8XXbVjt+c",
	"r90Bu/yk+iw0Uw0rIdLy0WCmX5EkM7QM7FPFjopESUplhbFiI7XO1D/X0I05TPHSz8vmqGGTErZknz32",
	"aaCjSFD5yKaODVQkQhmOzgf5KrVn120tjNhcuMk/1JFp0fCU+s6Bm1KzgtBgtrEt/+XdkgS7wxCYOotP",
	"DqyVtfkypxMJsw3VC5arRKZjr0Lw+ipAM8FAvd8wgJRrDg4gMxx1jAKfe4cKn3w5/NSDUK/lw/YuDyl0",
	"dar2oRD6QLICZ26y9nr4zTzE/AIEe+uMU1qdkbkBMk/KPKevTYiFsY6raFUKrrb2+dsXJJ6hl2mm1jss",
	"T5La7LYmJ2JcrShbtqRd9Ubtw+Y39faQNKFY6Y3CSlKc6Y3/dU7WU1D2XBltTzgspHkwzoobNNLrL15C",
	"Ymd/s9LxmqkVUTTyEmcXkqivD9Kk0RzHBRaU57IwY8Ey5Azte+l38dqIsvC02sLUf5UWvSlyC7sKmp0U",
	"ZXkAQd7gNWglibKqI5AA4N8YJTSlylHqMl0EUOqCGzbqRVqEs1YieIiAUFbwNwQIFYkmzA01ajgqEc/w",
	"HzkpPDfcE684olLCBygIX8Sv2ofQ8y7AxgIHdjkqzbujuF6moOTCMBWMfFIOV8qUFwW4DwyYTBKkiDNJ",
	"JTD+MJZelnVQsEYh4kBmd1qVSvS+ndoBUrkI8CNkCKMFuXTKWXOmGdQTKpAWTty51RgmqJqryegOYZ/u",
	"aC0onUuiyY0XmdwGqoS0tSNTAXkRZMaZJFOUs0SzZmuem/UIEhFagNIKn+CpzxDp8YQGb2ZMGWXLQ0XS",
	"A00x+yo5ynwu9cEyZS+XXScAvqztqMFv5ZDYNHEH7bYCjqRFT3dZHLsUW4IGXqSgW3WUDdxN6/e82Idb",
	"lES5ScIF99QAUg/jgJ6QhUI5A+RhMeKpFgULrbIkguKE/mmUF5WFwjkawwF6Yn0/5yTCmhmm8Bksz6uc",
	"gfaVl18BBNbrHvK5QaOn5X4EsaAzN7C+J7ORQtl8rZ04FyCexCA9YoYudme7f0MxN069RHlzmFtOtUgN",
	"Sa6lJ/LW743e2TdEKpqCCPGNwTb6p7XdRzxJbHk+ZAJOCt8xPa8gQCnbxjaSBFADUWjtcTQsTVbozag9",
	"Z03WL6g5MhmFbUoin3raJ9/kOQQfqfbUkVz0aHbLAHkgIPDK2jfceb4fssl08pYr+PPlJ/04TaaTF5zI",
	"t1zBv4Pe8MahrmVflvk3bYqU55ukUapxVRqE3qY/NME+IN97qZIf7mRXP1yTaunQdN1tSiNvoG7E7WcN",
	"0zv2/Hgaey2/aeSpciZa2s/0syI1Mge5E0NsLZGFLFDueQTGwLY1MlzAU5Qxrso86tdk3srGgJ3NhNoN",
	"zIP12EpiUuE060iHYVKagx/jpX6iTdTM8BwYMUnIdeaylBW6bzLfkjAiWjTk+8g8m1HxbFW8OLGzNkeo",
	"HKXMtmeKhRr/OHTEszzBXjZZI9fN0DHB8bZmOgemD7xxSPgbw7lb51TI02Z4ZENDQFuJmc8icrHETL8K",
	"up3mQpdc6H8+kRHPzK+GnD4teL3JtXWK1lk5SIsvGQlKcZ4XLVaIX4KjA3hDm9+1VIDOwCl0R891NkEG",
	"0m1Vq30OMWh1tPy0BSJMa9Mlu5y8hmndkp73dFnkqHTKHqbqP9LU0UvJVZDUDbSjvdZJL12f/27h2ITQ",
	"ZYmR0U0wXfCtChsV99H/OXn3Fh1xgASYFdvUoHnLBTHctX5jY+D27WpmjfeLZ12+O/VH5IiIiDAVVAqW",
	"3xz/Zw/b3JwqJcjKxqZVBZn/68nus2f/D1xA/vH7s+2/f3j6v4IJ6o5t3eh6LZzBL5rX8aX17biaDlOQ",
	"7bOKdlM3mt2qg0qrlvbqw9WHaUMjG4RErXJaUZjbUqDFdimJyEqyT4Ny4YLy5fVws3ZVTGq2udGibAHC",
	"TWum+MxfpXC84igmWcLXGxQOCl+6DQownRYK1bzGDQPhPVyywiGgjeZGZSH0QQVJoDE8bdUS3/2dK0XB",
	"r1nWabMy8sWNcKUZMhJ1PjxjvajPu17Uw1V+qhpzq9fwQ5CieVbLAC0rv7pHzs/0LiretI4fWFJlbXJB",
	"HuC4wwhf8QH2Yl1/pso3yOuDsp4IvsVwjJob41/H+NedEok2C4L1+t1uJGw5cDgctvq9GhNbfKNjjPtn",
	"EBkrascxkJUoKP4YJPulBsnWqE4HkjeqyVZFgypTMUx2rEes9Tqb+z5kfY1P5Kps27P1lljKeovNAiqr",
	"ELlhQGN1sPtN/edkiv2ECHVsSzvVikf5O2gy9as8xWy7qKtUiz0GFyw9djjPZt6mxnXVEgoel6YmqYzn",
	"UoMviMBLYsp1gMV8bs3dc7LQSA8TU7acoVdwnnvdsUX9UUNdEUNnZ/G/txcyyDrUVqcmrY/TRvGF3ZEx",
	"fAm6XGpCGYKk0XAbx6cLMqS+Z+W8T2yncCkqN6J3TJV9VBVAvZerMlkgWZr52rgzToQJFv2GunnD8oK1",
	"rqUcuLWJN2NrG7MUb9NOStdbpXqrKWXOKpniLLMZvQ6O3rci+dH7kL3LFN9plURbCvM481urMa/VOHdV",
	"ELj1W9BDTqzSwPnVDnsQWnbTR+q71tUjk7dA4ipwSp0V+8LVh3AlJrbGBDtq2qUWgkZI6FYz9M65MJlf",
	"M3A4sihBi9IzG6uKSrIeKsbjHWNrYf6KAquqMGp6X+I0SyhbHmoWO1huoCDrc6IuCWGFSgy6akDcA6Uu",
	"Ajs7YjormQs9OE39sw3suIsMnqxZkAsrv9brsnjequDeZn2mjOMwJFXwVDCKm/gH8PCyBwZiFi3UjKOo",
	"NqpjRnXMjo9ymypkvJ63rZIph3ZKmRFfH1i1YjuvWbTx0wvUflSufLnKlRoN6XzYA0Zn/Yg/kU+LZ9um",
	"/e7SLPSkgzGpmRpx35Q1ossOoWaTazG1xR1dhxLtFabMeNeHOApjtWNcXx3Xm2qcfomjlY2EqQ5lnKzc",
	"AHrBPlvTjav3Gyk6JKWNcxcrUts0IX1XGW0C71D3/buGjsvvf0MtF74eKe1MT+OUPQc8TalqcyIGV3fd",
	"AK2wtLkaLrGE828JvnID/9zhZVgM7jkRBsYe4jO9ibLOpBCzfizEOnoHpKyC0NhKHMbVr8jhpgUjL69h",
	"Qz1RE/elEliR5Xq4rA9JEU+sHyZoaKuXpxgxHKVny9q6VhZ1+5GpGLYDeKU9v4Yt/mendXQrscX66wno",
	"6npSSBdmnABOy+RJnTqKvEz3ETePdUACxvpluILzDBUf7tGVNLpAvDwEKJ+uBJErnsR9w3jOeUGXihO5",
	"uqX8Hycnv3Sl/8gEvcCK/ErWR1jKbCWwJO15PMx3o1GQq6Oi7+eRvqOypN40G3bnAKDhmTZaDuuaQf3S",
	"P+YeO84dhfTr7ddcVFyAf1dgf1dIe7mrEHlpe4Xty0uNQkflglnWXt+2CCeuwFfM2ZbLp4FMYJ/nmD2w",
	"JMcQa0z5xBvpwbkStzBdWIbNPimOVpSR1qkuV+vaBLZMuV7D2eQVpkkuSFm+3gR/UVnGP5I0U2sbrwXh",
	"XlWepYya3EfHsEwUJVgYb27ni2Q3C+WZ5rmGMjGBY/yCCEFjgmjYMiW7j9M5vhfAQ+8g/HQPnU1ODNF0",
	"hTaKnd65sCQzEm1jFm9bkA5D81ObjrZVtVBrUNVR+g7yRa7eUdU4qhpHVSP0qCHPZtrGeufbVTjWRg87",
	"ggUaVb3Bag1GM8PDqy1DRzJI3q4/BaP28kvVXobIUh/uN5zEKm+/DZRoZwEW4TJKp06gRpcrLr18/xbf",
	"F+D7wvt5dTP+kM0WtHdYhJaf8H/6102dvTbM7tSpArO3enip+wK4l1ga/ZVDjIGxt5voqxoRYsFz2Ewn",
	"WWzA3r0ZnC9NyX9yl2vL5Wx/zY3HTm0NGiZ/agmwiP0U0voWwGyH+2/3Xbzg/vHL/Z3X7w72Tw/fvZ2i",
	"SxBF9I9VHtjkG4GKfgLxiGBm3hDXs0hwDdmtsVA0yhMskKS2MC61ykMsCJ6a6rGfwB8C7UN9M7zzllz+",
	"939wcT5FL3N9/3aOsKDObSRnOJ3TZc5zib7djlZY4AiSFrq91krLoSdnk5/fnJ5Npuhs8v704GzyNEie",
	"jCbrJFqR2DoG1tWM5YstbSuXJJPrY4zs9ZJ+ih9FU5P5OUY8MwoFZFONB3iHXg3agajmJgbeSqifBY7I",
	"C8+9cKgWTnmXqfOtdO0aNDlEhHQjfbtd5iEcwcZIimky2ZsogtP/vYCSoJFKZpRPXOg1IHKtWOgpwenE",
	"6j4m7t2q9G4EkP9eHeLDE++5W+XzWcTTcoTyb0/to27LeOizjYmWsjG45niVPvjCUHHAUxIvyzotNi8M",
	"FZApO+E4lrMz/V4lNCLMqOXsXvczHK0Iej571tje5eXlDMPnGRfLHdtX7rw+PHj59uTl9vPZs9lKpYk5",
	"QqWv66QGtv2jw8l0cuFY0cnFLk6yFd61KUMYzuhkb/Lt7Nls15pe4Arqh33nYncH52q1U4ZTLkOP2c+k",
	"Uei44kk9KxJ1UM4OY73lXDmtEgQTQsoemPf5s2e1cqNe1OjO/1i1jLmOfZfVmwWuYi0/xq8aBN/t/hDg",
	"z3Ow8JXlM0hstAh4KQPFpj/obxWA2aySpBVkv9kGEOxbBR0kWQqDzPWCg3J5V+ElDyTHDoyqJQC3NHiL",
	"deMVwTERJertNyppF8CuP4sfwodXWwzMDNMCwJ/ttrWhrGw1+Fimk7/d4pUx1YADt+XQSkuGS3fNhl0J",
	"v5YyXTLKlo5fN3tMiAq+M5AFyivmfGI62+wKVcNx9bKYvq1d5V1iXSGvt2GcuQB3e1zvma0B/Sext+7b",
	"u5/0FRdzGseEmVt5DzPa2uPvWaEXrlzK1osHLttBwgTS9LXunO7ZeeM6SRZkKrF8UdFQ0yuT3dJ5SkCp",
	"20Iktvm+vQSCVtyAEfQAkKTIREureqMtlzFvy+Y8s2r6TJALSMJYTSjn6CUsqCSXRUbFLkI5DeXrsWm9",
	"jOOqEjRSZR44cMOyif5c2iWTjocKkyRMVmv/kgsi1kU2ztBCk0qG0ftbLcBWTh0jDmnrbNYuDeJzgrZ+",
	"3JqirR/1/6FAzb/8uOWKR59Nzsl690c4t93pOVk//xfzj+eWfQ/tFGa83k79Ij9+/j9z8YpN+lkJy4yD",
	"p2UGSEjyZNLdtV+0SndEF9VbDhWmzaC11I5QyW5FWKOKUIk44CXtJVMECLXeDJpCpHwJJ9+D49vnIQ+O",
	"D3f4grRSEVDWdjws98AH/IRj5NIbjY/Z5/OYZTykxz8wKcbxgBet+aCZzq09J0YAJlL9xOP13V9+A7JS",
	"5lYiJ1cPgYXtGPj8FrFho+nNUcVmDc8fZg37UUSyYhE/3B6+MMGTJCVMdU2eCILjNWQpEMqRiZEefqX0",
	"cJDwufOXfv+vumRQ83uVfiKLCqikgxsJn0OUF75Xcz/pNrnEoNii43BsRS7L4NgM/FXaeQ3FxkPR1a8E",
	"q7579t3dz/iWq1c8Z/EjltE1qTfyb8H8Rx3YVsXOY4Lje8bNpS1cfWPEnE5yRv/IiU22DBzQiKsjrn4m",
	"IghWUbhgTrS6pggCfe8ZW7MiMfttPaRDhaRtmPrfNzvLSsLhKysjjSKRLxKNgsCXQwa/e/b3u5/wgLNF",
	"Qo0b0SOgu3mQR4K82zU26WADNgn63zPtNY4jD0J8Rw3VSI5HcjyS43vUPO3gLBO8yJjUpoJi62tT8ReE",
	"rR+xImqUd0fKMlKWHhufISLX5/T2Tf97JhNu1eBbytZfrOJ6ZHVGgrQJfQDnwSpZeijvzkfFbFm/8wEO",
	"pSawp9979IUdcXQV/Rqsyeb+9PiF9l8d3ay8OKPH5+jx+bl7fO6jBU3szQvu00X02GqYlQtlutrambmE",
	"1DMbHpLp+QoGqqx8eF3c0Yn1mk6st3vtoejnpsdvKoVueGNtmiS0SPASKuObKr0mZ6EGWZpisa7G3soZ",
	"+qcGN5wnRyBI2Lx99uzguCvpD4Hi2sG8KFUbgAm3Ata/ZbC4Qm+2yoOsB2JC4ektO7Aeagsyj4m8leR6",
	"bUOwKtJG3an8Y9610Qf5/rikt1y5HPCfIZ/U43JcY5ba/ItNsztyJraDD7LL7N7JrKMV5CFUAw8kqX9G",
	"6NkUjQe4u75w7q69uOuLyJsqCGuDPy7v1XbcHs0BX7r7W5+OAPIA9OPOMcHxrWHOrfmWjmgzos3ds4zd",
	"LqK9qAMNbw13Rk/PG+DryL2Ohq0vh11u8aI0ubCGPergL3lrtOlReEJuIl7fH20aRfmRGI7E8C50BzsR",
	"Z5In7Wm9nKcPZEfULfWfzNaoaJJMaHxgx7w5zYyc6rE5uc0l+jjEJAeRUVoakf8zQv6YQE0l6XJ6Bzmm",
	"IiNoaXkzCj6vb1OZWH68RZViOeijYKN8KHxuLNXI4YwqoXumNoKwmMDl78i6auz3puEUSZIstq0Bn8SO",
	"+shGOe8B4tzPRB3bcb1E4Leirq0sunWRt0Wypq017M4Zv2TFQn5zmbXDDgjQ+LjadvJQXFLgZDqEwe+a",
	"V+ctR24hI6EZuakHoW9lLZhO6uanwd/AsmQ9i0f70igxfVX2pQ4l7jWwyVPp3hpCjYrdUQoZCcdn+0qT",
	"ItukSbLveU21+3wwVCapNAUXmtSk3mITUmKDJTuiOh/DG92AwIjoXy6io88K00usDgYPNj4PiSNs5KXt",
	"DylsdBmjC7+O6MLQ/esKNNzobukewZs1hh+O4YdjwYmx4MTmKdbHIK/xsao9Vt3RXqzjyWqL/Gom9r8b",
	"ZUZLAYH7iwcbVMGgUsJhrJ4wxqd9kYaRjQWxDaLWNqNBLRLZphre9ikfV1zbIDox2lK+dJXoBoJqQ/PZ",
	"j3PHBMd3jHGPxF45otuIbu2sdlcoyqYYBzbMO0a6R2HTvKYY8CA4/5DSx8j4jy5YX7GkUUnKHVZ67Fdz",
	"1wZp8qwtz+4dkOI7Tqd7D6R438H8oUlydSGj8vMLJ4/Pn98HXDPBIyKlJlEvmaJqPeb1vQF93txx9haE",
	"1Ou5/42i6kinvl5R9YZYGBZc7wIRR/F1pAMjHbidd3uREDLIfe6VbtjvMvfKjDe6yX0NngdweXpc43rv",
	"jW5V3JrRBW50gRtd4MZ09Q+Yrv7QJqfXqyqP11VVoAwRHK0QkL62WXFswzrlAc+ZergU8EBXR+fA8Ynu",
	"T/9efafbfACh1R35/Zmx79nXz5t0tLCNrnUPgJkNYWznL/jzakeRNEuw0q+cpJzJ7rKzNhV8xJPE5lDT",
	"PKwdAhVjhMW2U9vut7JZr8IG3lbHKDcmalHPLDwC8vC60lGWfCyyJPCH/bdZ8zqf8V2ejiLtKNKOIu0Y",
	"1RWinDW6NYpt42u4AXM4IPCi4BHrD9wwpvDG7+jdPaN1++HAmT8ru30d2qO17iu01vVwwYLg2LCAxfvX",
	"i8vHBMcjJo+YPGLy5/KCD6/r16eU9Wzum7rYVId+XMGPrUrbEa0efXTC56qm7awh2Ien+g2+JSy9RS/U",
	"VtNnW0luJ8EPNH6emEEe2Pw50omvm5HuqWHYh7rQ7pZwdyxgeH1UHdVdIxvxxdh8+8oX9vMT4G1/S2Tp",
	"UfjTb+Adcm9UaXREGangKEzdolKkL1gQ9J9ljFJVE+qoYYvodb1IpDsVwEbZZ5R97p/LEIZ52BiPSpbj",
	"tlBpZDxG7B2xt/+NFCTjkiouKBkSqnfsmq/74/WO/aFHT8uvwbekuE3rntC9YfdIN63dojGKb3R5HF0e",
	"R5fHAZVBHYUZvR3HF8m9SD2RaoFnqS1crWx6RzFr3gT3HLhWn3lUGo7Raw+Fsi2iyiaeToOQuiayrDfV",
	"QAQmeVyOT91IP+oGvnTdwBDRzXgkDcKnY4LjW8emR6IfH1FpRCWf5+z2EhqETtZf5pbxaXQauiEOj+zv",
	"aDN/xDbzOqHqdBwa+OyDKe/WKdWjMOdtKrHfL7UaNQQjiRxJ5O0pI6zVas2iYYZT0/5kzaIhptOy9Wg7",
	"/Vo01eWN6rWeDrtMxn5ath3tp6P9dLSffsFZUOvcdPl66TuzoIleltvbvHUtwmffH0qHVpKt0YA7Povl",
	"s9hrwg28je1G3MrjeDdCoTfFvRty63OPgtpoyn045G2Tnzaz5g7C76YctbkmKjDRY7PpduP/aIr68k1R",
	"Q4RKZ9cdhFnGsnsHePVorLsjUo1IVWVJ+yy8gxDLmjfvALNGO++NsXnkjkczxqM2Y9RJVo+tdyArYK29",
	"d0CzHonFd1Ph/r4p16hOGAnmSDBvrrm4mk6MVcEQtVwkk73JzkQTFtulTuneOVIp0YILpK8NYcruYuYl",
	"tat8mDSV+t5AnKEDIhRd6NbkhC4ZZct6HVvpDR6VraVpLQqE6Z7HJNoLDmpS9vWO0F5p1x+sWUS0b9xA",
	"2cdKkuC+/m2xp03jR/9IbXbYYizvFl19uPr/AQAA//8ZV6lffOIBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
