// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3LcNrLor+ByT5Xt3XlIdpLrVdWpPYosO7qxHkePpM7x6MYYsmcGEQnQACh5klLV",
	"/Yf7h/dLbuFFgiQ4b8fZLe1WxSPi1Wg0uhuN7sbvUcyynFGgUkQHv0cinkGG9c+Ycfjlfn8MEu//wnKg",
	"OCe/HI4FSwsJF1jOVKUERMxJLgmj0UF0CTkHofpCmCJs66IJSQHlWM4GUS/KOcuBSwJ6kDzYz/UMqtaq",
	"CpIMYdMPo0jOAIm5kJAN0BmTgOQMS4TpHMFnIiShU1P1gaQpGgNi98AfOJESqIIAPuMsTyE6iIb3mA9T",
	"Nh3iPB+kbBr1IjnPVYmQnNBp9PhYfmHjXyGW0WOvAzF5fq0rhuaiukBsogHHeZ6SGKtSDQwtsujgg1kG",
	"AVEv+lTgJAUZqYGoxIQCj3rRDNIsum3C14s+91UP/XvMKc4UTj9EFpSjskf74T/LjssaVf/20w96mAWT",
	"dLCrtkClmi9O0/NJdPDh9+jfOEyig+gvw4qohpaihsEO35IUXE+PvQ06uIQUS3Jv6FH1wOFTQTgkChGa",
	"uG5bK7jK9I7p/U+YGxKtESxUBThJiKqL04talQYJ9RoEcUzvCWc0AyrRPeYEj1NAdzDv3+O0UOROuOgh",
	"QhWwkKCkUN0gXlBJMhggRU93MEeYJsi0ABzPUFYIqWh9DPIBgKJ9XeHlt69QPMMcxxK4GEQtXKxD3w43",
	"F4zLNp2rryjDea6gJRRNGM+wRKNoxoRUhQclOau/RhF6DoPpoIdG0eu913sHr/dG0Yv69rTfFdPAUgJX",
	"w/zv0Sj524H6z7+1d+sKsHN2TxLg32MR2KtHLMsYRdWKq1kgnKb+rtW7WbRZGa44wNpk7LjHYy9S27iD",
	"I3owqFrlmu//v//zf+srjVJGpz0kJOYSPRA5QxiloHCIGEe0yMbAe5pC7KIgytDDjEgQOY5hEGSE/tZy",
	"k73dhH7sGlzlEOuZEjXTjFAsGVcfLBUZIWSYWAcyLY/zOq+xzc5WtkK9nWaxHU0UX6zXdmy6o4Fltn6b",
	"x5Ji5md6kUssPvYiRmFTJhpAwka8NAjyRvAE0LtRT02sr8S6L0GwgsfwnmTEKDVNJcWUo1RX0Fs8IJjr",
	"mzvOiwC7uLgxnSh+p8ASA/TWsD0OauNoBj7GAhKltjR5SJ3Z7Q3+57chjpZBxvi8Pfip/m7H11uc5UYa",
	"oYISuQUkL7/9LttOE2ouxaJViBkVkmNCV12KtFzXTdhsB5VsNL0riWUhwmqfKVNKH0aC0Gla599Wi03g",
	"nhh26/TACw45trrdlWLf5udlQan5dcw5UwrbDb2j7EFxIrX/U5CQrK4f1mfgj9kq9IBolVVQtYocmK2C",
	"Cu5WkTeRFbB/I4C39TNe0EMRlp+FAI0Ep4mbI4T+jOSMiNoCiRkr0kRJV15QVNAEuNK9iEBEIMqk6UH1",
	"hoX+rbtR+5BQfRQppZAIaP7oOZm4v8cpvBigNzDBRSqFOumU3elzjW46VdoiL6hQwz2fAgWO03SOOGPy",
	"BSITDZLIISYTAklbfitCmLK+/XhjMeF/7os7kvcdD+nnjFCpECx5ARvtjp9YWhhVpjog1BflDUwIBYGw",
	"VmcSdK9bqKknaDzXR8hFjCCsKd1Q8qkA5C+0369doQCXaXFeDnGKSXbBUhLPt+U3BhuXtS6bSpWeUECj",
	"+n0b7eAkw1Mwo9cUr40E8ikrqNxVZxqyzh5vVxL2gZYtlmCWP8AU3hMhNYf2NqatrAiCSMjEbtY9qjYQ",
	"5hzPoy121GWTLBPDOrRQVSwn6nXssxl78LjJDNMk1bvP7o+HGZiNwR4UV6+hhQjEIWP3hrc4YWXHu93g",
	"IGbmYvj+Yum5E65w1mIHHVt+AhxoDCGFxRY5Dp1AnrI5JOj86KSvKCMlmEpEFFWrU5YSmxMcSzTG8Z3C",
	"58KxQ6zAh2eTg5a4KrIM8/mKekr9mCu6dZQfAKdyNo960RuYcpxAEtRLzpgPy/rKSR38atDOKh40nXUC",
	"ekm9QlA/qVdpTqxzKaQEIXWtN1jiNvIbFZzOIND1xSnCVSECxd4U7SkN2SwIAspZmhozEnAy6dwRMyxm",
	"h+m0PfwPWMwQTqeMEznLyh2mFl0BUNpnxAy//PY7a55p7RmS4VPAouCgYFE8NTDRq6OTEz09Be6EswwN",
	"xVwM74BTSIcC4oITOR+SDA+xiAn5xdq7fsmqrgV67tSTMCTZ+D0LTPN7LOC7b/pAY5ZAgmyPCRozJtGY",
	"UKyOUWy6rHfKgnzhTH02uLN6hcLdp4JJs1oTDmJGQYhgp7reUpCrHi2FKHZycXRpDIDhnmWeHd6t1LNH",
	"hehHmKO8GKckRncw7+r4eLWOj2nCuNBrt7zjlQXikaJsTe1wRaYKFZfwqYAQ2XVWRdy7qUDcftTGPiTI",
	"lEKC4qqtIVi1tEeHIbsf+Qm40CO26P7ixJahxAphLQXMN0iQUSOMZNIy1oJlT4kTJe4MPgboCrhq6I4m",
	"MaP3wNVUYjal5Leyt/IMkWK1sEgr8hSnhlqM2S/Dc8RB9YsK6vVgCQqdMg6I0Ak7QDMpc3EwHE6JHNy9",
	"FgPClB6UFVRtWEWPnIwLybgYJnCvNjOZ9jGPZ0RCLAsOQ5yTvgaWan45yJK/cGcYCFLYHaFJG5c/Epoo",
	"PQQjU9Nav0uUORF7eXx1jdwABq0Gg96iV8hUiCB04o6A5UoDTfQRSP8Rp0TRsCjG2mJk6UXheYCOMFVn",
	"rzGgIk+whGSATig6whmkR1jAF0eltkb3FcrCyMxA4sRKn7UV2XONuFOQWHUlrHq9vkWwax/aw0MkSj1w",
	"h32bPtuW63K7WkrzcGTneLs1Lypt2zUS/pnjPAelGrKCJgjrU34/5qDoBh1dXfZQxhJIjZXurhgr8ShB",
	"IMI0veCcDDy+JAb3+4OFILS5FXzOCTc2F4gZTYKmOd3e3D2VjOgepyQhcl4a6TxA1DDmvic6iAiVr15W",
	"lKi4zxS4QiF8lhwvujkrT1xtoVM7PLWu1FTHSmHS+wdKi0tlRHE41kxc4TlneZHqT1bjObw4QUIzBYV7",
	"XV/NXDFLkmWFxOMUAhdohriC0ud6Btrk6knFi+PT6vePR1d/2d9T4AzQKZbxzEoHRYKDUiYRSLVmgX16",
	"WCTYDOOrLcl4LiHEG7So42fBE9MJTQyRaZh4SROmjZEimht/KnCqrU7a5hLkQQUJ8PObkzd/wDp5QAg8",
	"DVkBbvT30nimBQxou8AdzJFp5c3fKnlEiKKuJdRMBksJ2BkjFx9V/wDENNijo+YaceyAH3Yc9Csqw3nO",
	"2T1OhwlQgtPhBJO04IBEeUAtp+7dW4qOxUBkUjmEBC5rvarhjWu7bCuDvQqbSKv+5UKstOUUzyXm3Bi4",
	"fnZl5iCulpv522+AflRnUxR7FTmgQ406SHroDVCi/lUYeotJaoDa3JBVQhQ0YPl0481rdWppX1xu507S",
	"ddG/kXky4A2ybT8dltNtrbtdd+ubWWVpSmh3l7ePayyvI57tVrXsp1zLPOBvs03H5hK+QdEy7N9w2+va",
	"tRVPSkBikpr7TEYBYSVcpONhccG5Pk5Ixajc0U+x78tSeC/FadiBRX2tuIM6KBX64IAmLE3Zgzoi/Vhp",
	"EWpI/zSBbgRYbxG1WtrpLlFqqpWNsXFkA1pkgWtZLOQ1x1QYjJIuLxZVD0mSgcFFCass20JijmEKc5b7",
	"K0gokzPgNSarzlt91Vf44COU7A6YvYoMU8QBJ5qJ23qIGFGkcOTWD49ZIS3EJXhB5YKNtehN3umbORk0",
	"BqjZD9xRYzAta1bXfBU2HrDQWoi5si9yM6yvY3/3TVDH5oBF0BKBno85gckLZGpUarwb85lYaabbHNXc",
	"UB1HM9t1L0RL5cyqhV2fES2/bqhhpKdJkE3QNS+gh97iVEAPWQOxbxBX5VEv0hU8E/hqFu8GdLavxlfX",
	"deNzOdLSqXc4p1rH1IrwiG+78KbodIyoF11fnP6kDc7O0u4KjPahEaFUj3bVOAYhyDiF5h+O8V1gLnTV",
	"qzmN9Y+f1LFT1VAMrJAnShxNOQhFJjd5gq1rghJOruppkUqSp3D+QIELDdc9ieENxCzLiFBHf9VotdU5",
	"Lq3sVpP15tsqq0+3Uxn2uuisU+Kys0aJ5M4adXAuIWeCSMbnQdQrjHcWtNbHLyzX6m0KIN0q6D9Cq2ZW",
	"w1s788FfQfNl1XVcQPsTMm3eDW+hbL0jMtDnRlpWJYWvIOYgd6W37Qq+H6TMQ30tQnbb6e9fW5vXDkhf",
	"6EhQ1630nfIKV9Lm7tlIdiIqF6SgIM8ZD7lH+n7cu3OD0D7jATMI9z0Ed+HP19YqDPKCivyK6kNeuN5P",
	"GVUc1PGSirjr65WZassDQqprCoZso+UmGr/3oLfQBlEU7ekt2Oqc0ePPuWLnQT1XlSMoK7hIAEWWCoqk",
	"SPVVDclADEZUocPWIAJ9/Cuy//94gProlNBCgjhAH//6EWXWRrrX//bvA9RHP7CCt4pevlJFb/BcofeU",
	"UTmr19jvv9pXNYJF+y+9xj8D3DV7/24woldFrrYOJEgtOZZMAdFXFQ9KMy6mc3s9ZS/RVTeEopkCuewP",
	"7oHP9bcXatyP/Y8H6BLTadVqr//6o0bc/kt0eKqo5DU6PDW1ex8PkPZgcpX3e/svbW0htQlo/6WcoUzj",
	"0LQZfjxAVxLyCqyha2OAaba4Mq6r9bm8rlCiuM5rr8mIHhs/YoU5tNd/3dv/rv/ylV3SwcohG0eFkCwz",
	"Av+ETtiiW4PmQUdfqpjr1gTFuiMX0mFXJQhH0yrsdUKooVBtT9VnwrpjzGp8xMymDbH5Xr+SzmdzQWKc",
	"eoM83To/3To/3Tqv0U11rtjSbmE72uA++XY93tDyiG87s+4oygyyMSQJBAj+5xnIGbTiMNQecI3cHdiY",
	"MRkbpdMjgjFjKWDaHcvWsL/5ntrLXbJxMg+rVCaozRoznOf9w4zEM31HoluilT2/deRcQLqclaO4OsiZ",
	"/rqiVwI2uh3FKCjWXWhfMBufcDJB4xTTu15o9XhBXayCjlvQfdoPxiO4GVew8zCCrXZhOPDmsdft312Z",
	"9WwVz8Wxjsodu3s7VrHkzqx08lVE7VFdr7KElvu0t37IZYun1L1YQ6qTMBUc9c20z23DRT7gGNw4rVp9",
	"beGu91UqY253klQboWsRal/MIL3YV7rDPL0m/o0VpQvlR95dUGWBth6+sW7aRjAHtd0h6VQAL20Fp/J1",
	"9rvMF6A+zvozFyztVHhtsa/3Wuu7/hwzSiG2NumSVtrIEOaUefImzFBtMTp54994NEYI05VpeeppMo3t",
	"Up5HylGc4HeCRsFtPUn+vRbeH2OqlTdh7vgJJZLglPxmbsXKfBHAM0Jx2ithlsw16yGQcdca4uScpnPD",
	"dRtE3JhVz0PgmuvrG2JD8akWFebAhB3xJXXzbena0FpYifkU5BYKmw/fte4sfM9rxtli8l7nbRlUuhWZ",
	"DSjUsC0kZCBnLKlvU//25YYab399txJLxueXIGpAL7rDWASx1/OiavVRF6PmRGk6nMj50Qziuy7O1123",
	"yRHqvJG4FihWTVAOXO0y4zK5oVjqB8VSddJvjmkg2rU06sbIDsVRZ/dLLkXXQHtFtC6S5oYKZzTzbwfL",
	"y6l1yDg0gWqkRXV8GLrrldB1V6ngXhHXnffOVt3qovAWP8gbhi89SqLO5XK+Y5rToT3ranLVltFaXDWT",
	"JTqcql1itS3HSaZU4yx3CGl03gx/Ws0/ZHc71QbKm8V0pxKZZztfkd1ygDbYK/OATkHl3TeXGynMBzba",
	"84391wuXd23hJcyizSeW7O/3ZALxPE5hI+0+da13cIJqGqWrzr+orGogYIdiKtRzF3X62dVCuG3LI+O4",
	"YUmk7k1Q/7ImnTagblJao7gGRaA8BNqSastp9lyEQ1P8UmSKxlZpNQoyOr8qT1CdKlb4nvq61om5pDZG",
	"Lo5uLt8vP4h2XeEum+km2/L8auV5/VQ/Xbu5dUXJTuENmXZGiiS6rNmXuXNDJgL3AO8NBoMXq+KrPuia",
	"2CsdfNbCYXnDskx1sfmUNuQ7deCcxE2IuNt5p1X6pR122/Sdz4uoHMnOY6vlWux4IGqeB2YBzZ1YO8D/",
	"Z8wt7zniRJIYp4FQ/3VYZB1QP5NAu7QaPFTqARQqdkCGypa6TXpXRx2cssEn8YKLWi9VwEopSHLrDLRD",
	"75u6e1HLC8cYBLuhM+W7AizooxaCSbAUOu5JUoe3WJL7yqRnbVlbAlg3XwajD+uSeTc2Ku1Hvg3EVrY3",
	"3aoaVks1iRoHsP5EdpVtyOeWKGx4FIWQaK62kg6zrSnUAW1EyZO6g1TD3QrLeHZhUoQGrzUcteiKyCYT",
	"rc+wdRNiHF8cHAUlUussPZtrz+T6Ulq3KCYT8rmHTPKAGaRpX8h5CmiasrEbTMOvR8dTTKiQLgoknaOU",
	"4QTMEBqmDH9+D3QqZ9HBy2+/qyU//bDX/zvu/3bY/++D0aj/y2Ck//dhNLr9H6NRfzT662j0j9u/Pf+P",
	"1eq9+Mfz0WjwwVQMFQdTrC7PY2RcErbIm+W5CNtuDGE/ricUF5se28bG8IlKeLmILJNHtm2GtWWDpOYS",
	"NZYFTquwnm1lglVIa1npPGG9LX9rOxsENilu35DtZsjGXeTqkZHleplUVfry3d1LKpwHI6z8pfgi0ZC+",
	"DN1c3lQXhdr4Zu0SuzNROVPbFQBdJTrLUqAJRgLqIo0tU0bPz86vjw/MZXrpYGfTI3KQBae16OQXK9rm",
	"rDfBr4LRPplSxqF0HyjP9bszWuxC6pYdbefOHDx5KUm59cZrbTYj15xn5aa9Vp0skueOn9Vk6W44mYEg",
	"uaFEdvMw6yG3tSRKOsywHuOqIbbOPaMwM/Vpxt/zJUPR1FlNoqIGfzeseVrc3A/E4wozzJMHzEF7dhpX",
	"aEKnzmOp5mu5e/8QC4MLD/1iHiIBfO3QyrlWfr6wwf1ch/2EU/FdwpgxG2R1wR6AQ3I+mdQs8ocPmEgd",
	"MWa9IUyM4SQlsbzAhVjTAFqbkAdaq8yDNlBaP7vXivw5BYpr0wyUN02ytcIQMgLVmvhZssY1TruaD/u5",
	"y+RtN5OX2QY+58zL06cd9wYjeozjmc5XEjPOQeSMJiZqujrVmV1lnbJjnOMxSYmcD0Z0uTe8mURtU8Ys",
	"Tc0LFaX3cqe6q4DsdFZSasfh1KYxFF172HdI7ujDq6G0RBOjYfHU8tWvelb0FPIe+p4xiU7erNOVCTbY",
	"WKq2gh6UauIYq1mC8NTPS+575bjvijA3nZl9LJeoaUPRq6/pmmyvdbBb4jWT65r69iHDFE9NiL4WAEYs",
	"6vdS4rRIVIlOY2u/e2m8E/ZA7UlbCSybYCVwqW7rXZlQpc00TTPDsotSCdlpp4+bYD3Z6FLEQL/Ti0pf",
	"jJvuv7gYr2Fgh2K83e8aV5UVast7yvyavcE6fdB5Ic8n9rcXMb2J4b0GpDdEoNQfNdi4EbpdL11qWyfi",
	"bmk85W5CGHt/ssDMIJOzph3N3UwHmr8RcWeSj63zaFpCOGhHvfLVNGfc1YmDa30unsu6b2e9KRalPcnw",
	"Z5IVWZVQEKcpe/BjJoynr2Qoto9AmJeuygYVIy9fOUBYR8oxxTLurXcKcJvqxiYLN7YM8yBKFbhZftT5",
	"sw7QR2FiIIVJidhDHzPzwYQ1qg8z80EHcA7qL1I9/8fBh/3+329Ho+SvL/4xGiUfRDa7Xf15qmMaMyW5",
	"VnEgBVvXEKp2H9YriyVuhPH5HCVPTVp4k41w5cwXZqgL29j9/b3tpHs6jawY7Tm1qizIx2vTwinSMJ6q",
	"C+2qT0GRT0GRT0GRC7ppbb0dxEe2+/wDUu92JObB6QrsxlWtMraFddSS+XhXCH7e/c7YBewy/CxIePng",
	"BVo6jjfDAo0BKHIdhOMqUzyGdJs3KA9dilPTk7YU5Hk6r9626Ahtbz8DaOa5/bJV55IttMBuomirX0sg",
	"WUYb3rXgtlRy2OESptUULG0Uq08nD1jUSGQ1j2fX4vuuENp6JK6qy1d6CtL12vOntELqxGVLsMHdbADx",
	"5QINVqfKsFkiWM0IQq+iAadV95lwTpD6WjJADu3nQtZ3+mn0oSYseHi5Q8mo/RS6wiQT8+k3wFbqF+1b",
	"xtb3In14vFwW4Hit98LCIEetPth4q8GvgtFl73vsnqm6tI7uvlS/R+3xWSLKG9YZUKT0GY96iQhJgQ5G",
	"rBZ5cx7cZRPqqLjevmx10sUIjejeHc/3XAuWZXv2t0I75fNg7UTO7QyvEMbDnzU1s/8wdxBj7i0fvcQT",
	"EopiiBe110dSJOGzRM9vrt/2X79AjDfT5XuD6GhaknauharnTqgbkpF3Cl/dtqoQ1R0irErLoOA2hqac",
	"FXkYP2quzwTSNXqezQOIVhqxezXRvucMnMTo5E39HclRxBmTo2hhHoclCRsylsBCCHPg1n9Rv10xQP/F",
	"Cn2UMzCb+4dMHbwmOCMpwRyxWOK0epYaa4PGb8CZyzC1990332h6wEa0xiSzDUwocajNNy/3XqizpCxI",
	"MhQgp+ofSeK7ORpbQw8qI3t0qozak5kmZUZjMuYBJ5KCYtQVXhV44cwehX2TtBNb7EE/nvAF1/OLPu+p",
	"6HkHxtqtn/2v7brNUjCOBUsLCRdYznQPLeNnyVbWMYOGU4S2svhMibxUAIf1Gi+rI0bviKx75tpHHtYx",
	"CztjsM1+MCFTl6CgSgrbkQjHFS8/MVRd1R4hafuPaiX4Eu7JIt3OlCqgC+E9wLUQ3lb6ihL41qi9LgP3",
	"ogf4/dk2XOJXftHRrvzKgrj5BPqXS6m6WcrReIa5rFKOziDNlqZX0ibmHMeLQ8XKWqHESvb1TaVN1R8v",
	"z+Z9nOf9aojA+May2q3pm6wZLQ9UbwuaHoIZn9w1g5I4YyI55iSdI2ofz3EJ+UUNag/d/o6L6JTQz5p4",
	"p9FBtD94uW8cQ00q5YPfI6B4nCr6MiDPmJBCU4b6FR24EQYxyyzJm2LDKqKh/WhuHqILDhPy2T29y0FP",
	"6ogVSod71YvsMUazGsZldPB6r0TuUVoICfzkIqw6GXwprr3A39khVcvb0iKVFOY+rFpvpPuxWb1SrC9/",
	"9NT8i339ZJIJdeAJcDSGidJBdG5Iu2kT7/nEcik+WFhVpaQw2WHmOEsjN4k+uwfOSQJiMM9StZFXffRn",
	"13lpO3I0t4TNTMp8RWlD0Q/X1xcryhu1UBdBmaO+OgljTrjPzLo6hybJPKOW0/KbLsMaFAH3wL3bvwdO",
	"pAS6tbTibWnlhI1LkjanMVogx0zcR2jyvDyx3Fy+t883sUyR7ERag6866OjYV3QidTIg478C6FMB+vaW",
	"4wykvmIq4hnC4gCNoqGi8qFkQ3cj8g9d+9917ZBauFAilsv3xwtBR5Erk/rCZ24WJGJeVYqdH50EHm4O",
	"yZ0cx3crXaBvvb0XPo/ejkU2r2RrRamaTaaaQ4Kwd9LRvHJBjPM2L8xf6e2i77qM2NigO9OTnnhnYLPp",
	"fT1UXhRpGno0/WRyxuSFsWe1nk53npj1g9gzv82zAfp5BlQb/1TZYfqA5+JZz8vITgTKizRVxz2dZVmS",
	"DBqtzlRJrVFWCIlwahJX6nfMulPtmDGjXnMyutcV7/sVfsp+1B+NvtQn299CPIeplTJp1BvfXUYv4uMX",
	"pcTtMgm0OwwEk/m5EqwkMd4CSx6GD5zgaiS62fQ9Ml/jQfvl0Jo3KDlMiZB8PkDXSt3P8FwJZVzlXPUa",
	"mgebSpcqxZVcZz0lZFNGp+pfe8BlPBNtfix8J6lVJNzaD+YvfvBskXAx/u0L4k19wWG1nJ3FdFf2kyVq",
	"poFyG0HU9bLIwfoYKZV7855lm6NtjpvSNhUIAfqy6kwnijsQuvDxlxZSdwW7OsCp0VY1PHkPxZmG/6T2",
	"64LKDU8ptat3gwPvJGJ1q04Lx/I1q9C6romkso0s7+qf1yYd2Gq+Xada2ttl16O2dbUBVt6rpzory9P7",
	"Lz5KVj2TnOEMEpt722yXumVBTTWgF1odraUXfpkjxZpHCc8Nrx22VZYpjb/MBawNADhNUQ5cEG0HrPIk",
	"aS1/hu+hZ3mNNQQI3cIAo/OWc1vXCM7AHTqlTFYpBTb0Yagqm+cnawHf4adO7EPTZZLGBb5MJmJfO4A+",
	"YOHetF7dgSmBFDYZi6SpDgFSzdcZb7rgNc9DJOBTocWlfXqg5v7qPZrqvfRZuqiYNMDGEQhdNJ/yNvJn",
	"gC4BJ31G0/mKj39u7cJyinWOTevVewdzY1O1llljyapnrmZ8iin5zUQBx1jClHH153MRs9x8FZBCLF84",
	"Yg5S0WoC07pfBx9gVUIstEqe+zGWStYJ599tvveUCjDS7qhDNdYoss9Rdb0MoVt1u5lTxHL8qQCHRD0s",
	"0TlaSy9+Y1F9Jjx/8MqHqXIzD0qC1djUBZbxzPO/L9XqMGFM9NOmDY7COraXDQY0t3M2D7BvjMBJEpnr",
	"AyOnOWTsXu+veh467ym6oH52iP7X1fkZujBqQWm2Cl/nhEE1fun2HWOmt6gCatCSAixfdCXYzvURQPl/",
	"FjhJQT69f/j0JHonjVza+6rwgeSyHgRjr7b0iSRss+3aN+227qDtJMsZk5YjYmqti4pZ6fpOXLJ74N51",
	"S3XHKng8JDSBz4NfxRY8ymmdhylweWmjYvPusPj2PGf15O0NH1xtuld9hz1XOwPWXCibUuKkUycUMrzT",
	"IL4HjqdgoukQ8V4BsheNemBCpwP0VkuTg8WBas/Es3oE2rPsWT0C7dnsWWcE2miU/K076CwHHgOVnalZ",
	"q3KFNTMj47vKyXSqFM8QJo3SY8wK97BxnqIaEVzZnsKxuW4Yb+1qk6srM7cbkWENgnYsni1tUZcTfcF0",
	"mTqUfzUbfCcsVcedVbwRO+sYUJZhwiXtU/Mnav4Zodh+sC/Dqp9HFzddS93xZGoveqNztIYbdQUG96JT",
	"m4Q13K77iF4dIednWsGsnZ2V1ri5mOmY4kYCZtEMNvGp70CkklOdhoQViWJhvoZwKDOu+YM1Tq2O9y/K",
	"VKkrIa5qDdA5Tef6XX7zNQeOHGfQLvOGp+4me2UlmUL5K5U4JHR6orTTYNxZKUjGIB8AaBmMrZuqyfwB",
	"sqEMTe4SEAusSz1/fQIzXpnHdj6AYeIEiFF4ZMGta5WeTYxTF0WRMPrMOYggc63knSafgoC/bBBwHPQB",
	"vyqmU+PVph117OLEzm1a48/EgfTQHiLW39oYqX1bxquXQVvGU+TxTiOPhQjqf6vo0H5GGIVHd/zveqFT",
	"hJX1DMczQqFzqIfZvDGAWmh7PzPSz4kUHEaRe9ECnViADAno90lzqQ1oHEwaynp00j0mqRp4gA7RpQYT",
	"xSnmxizjXN+EC/5MAI0LxXnAJLR0bn+IyCXZaRYlcKuQh86p0rcP0Ci6KuIYhBhFiHF/pl+cbEQOcR/T",
	"pN/5SMgKEdzlW5WaTZQUUBHd6lLCZHM81Dm9Fd6g+wZlRqazfqpmavJJ6kTgVZLcmneMSRKuQUuZjhzR",
	"l7bl54l7L8Z1oiskUPszw4o5UUytTWvCQcxMUbFWOp72LA8dIO2iSw/idulJNYd2YfkKTseAbmLt4jf1",
	"mbcrnNZwEYLaw067eGmKINvkWHs3LyEE4wJdD7XTFOGixRwVOF/pnvvV5wW1lv+U0DtdZH54JTglWOjl",
	"F6aG+eHV0OG2sXm3wY1AqMnEE5V3CPqzSXBl3KnGOPFIpxetRz0eao7LeXWWXZbAtqu8d1PvKlrU+NBi",
	"p11y6vDVVbSo2yuH0nbRmwrJ7cKTCu3twnfeQgQIzFuadun3ONyqSicZwL2SRktp/D3DyRIKVxxgBfoW",
	"shgrCmY2ryZlsj9hhebRY5z0BUi7ocGm18yATz2a3pSTlVO4MhA0P793EDULzph8awFsFn2Pk6sS3mah",
	"Sw/a/H7q5tMqaBBjWbAqJ/ISDLdfZK8Y2zY5jJtSr3k3FxSC3bqb813Wqa9q1tvzHOjV1Q/2EgolGDIj",
	"rr1nB/a+eR1QcaAi7m1m2mTrj4Zot+63vpW0h/647DS0rR6MAtHTSLIeKe7StlIiSsTxglKnC5So+u6b",
	"+mkb93/b6/+9f/u3oClWDdTx8Lt7YMLFs44iIWbJwF69j6IXDRu8V7hUbdPD1umpvpr+CvRqFO1hcWU9",
	"7ppk8N/MOQI6P+v3zBgn2287ot8YheqOlAtr/tAEfHJ4dmhvZNHh5fHh8P350eH1yflZDz1oTV99rOcP",
	"U9owoTpwnCMWA6bmkO1alq5OOn8c5pLERYo5EkSCjjLWhw4sEeaAe3orWcSjQ+0FhYdn8PDLfzF+10PH",
	"heIGwwvMibNOFRRnYzItWCHQq348wxzHOvDDzbURjYyej6J3p9ejSK36zfWRXezVssfdtBKLNv2TKzuH",
	"sLVMZrVCMnU0isvUqNpYR5NQUlVJMlfq/LX0dFgRSuewmZfOEWf0+LNaR/cajn4P/x3HMfjpBde3h7rG",
	"j71IerS5dkclYbfORTIKQrvylvE9lNpPabddp8wKWt+qVS8GTT+55/ZYuW3raHxLkbpzs8z14LhoCDIe",
	"6qhEdeScDJIDzjZNJfnoPTCr4Yj11CHDJI0OIgk4+49JSqYzGct0QFjkvEQ0v3yrS9CROviyFF0DzpT+",
	"wlVTd1SutW75unyod3H7PNTshTU22QwuOtcixCnm5n5VpyOGzOaomKQAUh/1IZk6n1LjQSNnQDh6YPxO",
	"bTRhkm6nJAYqoHLyjQ5zHM8AvRzstSbz8PAwwLp4wPh0aNuK4fuTo+Ozq+P+y8HeYCaz1BC51MvVQNLh",
	"xUnUi+6dcTSyRGjTTCs6jA6iV4O9wX4VLPp7NPQyodiUQM72ZUJBQxkej4x7N0ZHVeMr07hK+VhdCpRm",
	"kZOkbNzZMjLkBUJ+z5J5I9OI53I//NVaosye3owndQLxWCdz625scq8Lswtf7u1/VehCS5Ko1f5mb+/L",
	"AlYmAGxB8T1OUAmkgmT/a0FyQ3EhZ9pbzSLl1dcC5S3jY5IkQA0cf/9acNTfN9DAvPxqwFwzhk4xnTty",
	"0Zmcvv16i3RlZMANLQ3JxtcFT/VhuJNLRreq2gIuOvxdcf9HHVABMuQWhBOjvpUe+p0bv81M34FcxEmr",
	"SGN9Db7Y/3I5M0eSoam54yGqB5tJxYo364Zf55o9b7maRoeCkk8FnJiLXBMWcNtisnt/IiZ7/uMTV+vg",
	"at98LThKM9MTP9shP7ParWVeQ5eNsZOLvQNpEy/YtI029WG3GvgOpEsEabJErsuuTCvLkuqDi6bDym44",
	"1mM7zWz5qp62NJYQ/FS9daOH1ZkcqnGDaTAXjfuHs0W7JJ088KXZ8M2tiLy41T8Vm/ya7AlV/OnrKX9/",
	"XrXP40qGaYRZUHUDn2MZhwM+XTCnl5/0zTI+pJvV8tRuxod8HUlDuCuec7vOgbivh/7bDtawFmOy0nH4",
	"K7Okp2Pvk4K4nAM/aYgNDRF1qYglM+5FeRFQ+W7ss17rMtxLE6W1Y5ZbPbT1h/PcHfK1Jxb7z8hin1jb",
	"6lpdlQJ/9WsGikJPSi2+X2i/U/UHbun24H+G+4QOqJ7uEZ7uEf5FjpJ/an2qxfk6OeKyK4N3INdliu9A",
	"hjjiWlpX93g7vRf4CtaulTjjk/H/6Wz3L82LHk0ScMcMjIPKEOdkeL9vEgqa1u337C2nEYjR5tlMuxhZ",
	"RmAVwbYVvd5DN5/xO2tP4fH28f8HAAD//64Ktgnx5AAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
