// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9iXLcOLLgr2A5L8L2TB2S+1iPIl7MU8uyW9uWpaejJ97r0rZRZFYVRiTABkDJ1R2K",
	"2H/YP9wv2cBFgiRYxTrc7pnwTES7RFyJRCKRyAu/RTHLckaBShEd/RaJeAEZ1j9jxuHnh8MpSHz4M8uB",
	"4pz8fDwVLC0kXGK5UJUSEDEnuSSMRkfRFeQchOoLYYqwrYtmJAWUY7kYRYMo5ywHLgnoQfJgPzcLqFqr",
	"KkgyhE0/jCK5ACSWQkI2Qu+ZBCQXWCJMlwg+EiEJnZuqjyRN0RQQewD+yImUQBUE8BFneQrRUTR+wHyc",
	"svkY5/koZfNoEMllrkqE5ITOo6en8gub/gNiGT0NOhCTkx+BCw1/czrHl2e2DCUwIxSEnsKD+QYJMlhH",
	"bIbkggjEHRqx6kB9xhSZ8UfoGrhqiMSCFWmCYkYfgEvEIWZzSn4texMKZ2qYFEsQEhEqgVOcogecFjBA",
	"mCYow0vEQfWLCur1oKuIETpnHBChM3aEFlLm4mg8nhM5un8lRoSNY5ZlBSVyOY4ZlZxMC8m4GCfwAOlY",
	"kPkQ83hBJMSy4DDGORlqYKmalBhlyZ84CFbwGIReFVpk0dFPkUVsNIhmKZkvZCxTNVj1ObprrtIg+jhU",
	"zYcPmFOcKcr6KaoW5MeyafXtjev7jIWKT7NcLtVAH4dzNmzQRCcF5De6YoiaVRdmfQHhPE9JrNfWn7je",
	"iAKiQfRLgZMUZKQGohITCjwaRAtIs95z16CclD3aD/9ZdlzWqPq3n77Xw6yYpINdtQUq1Xxxml7MoqOf",
	"fov+jcMsOor+NK7YytjS4zjY4RuSguvpabBFB1eQYkkeDEdSPXD4pSAcEoUIzV7uWnu4z/RO6cOPmBsm",
	"VWNZUBXgJCGqLk4va1VaBFMniFP6QDijGVCJHjAneJoCuoflUO87lGPCxQARqoCFBCWF6gbxgkqSwQgp",
	"erqHpd7BpgXgeIGyQkjF7aYgHwEoOtQVXn7zFYoXmONYAtcbrYGLDThciZtLxmWbztVXlOE8V9ASimaM",
	"Z1iiSbRgQqrCo5Kc1V+TCD2H0Xw0QJPo1cGrg6NXB5PoRZ1B2+/q2MBS8a/oKPrfk0nylyP1n39r8+se",
	"sHP2QBLg32ER2KsnLMsYRdWKq1kgnKb+rtW7WbQPM1xxgI3J2HGPp0GktnHHmejBoGqVa374//7P/62v",
	"NEoZnQ+QkJhL9EjkAmGUgsIhYhzRIpsCN4eAXRREGXpU7FrkOIZR8Cj0t5ab7N029GPX4DqHWM+UqJlm",
	"hGLJuPpgqciIIYaJdSDT8jiv8xrb7GxlK9TbaRbb0UTxxXptx6Y7Glhm67d5Kilm+V4vconFp0HEKGzL",
	"RANI2IqXBkHeCp4AerfqqYn1Xqz7ysoV70hGjFjbFFNNOUp1Bb3FAwdzfXPHeRFgF5e3phPF7xRYYoTe",
	"GLbHQW0czcCnWECiBNcmD6kzu4PR//wmxNEyyBhftgc/19/t+HqLs9ycRkiJZTtA8vKbb7OdZOHWUqxa",
	"hZhRITkmtO9SpOW6bsNmO6hkq+ldSywLERb7TJmW3pEgdJ7W+be9xyTwQAy7dXLgJYccW9nuWrFv8/Oq",
	"oNT8OuWcKYHtlt5T9qg4kdr/KUhI+suH9Rn4Y7YKPSBaZRVUrSIHZquggrtV5E2kB/ZvBfC2fMYLeizC",
	"52chQCPBSeLmEqk/m5uXv0D2gjUFJXmhgibAlexFBCICUSZND6o3bO5zuhu1DwnVl9HyFBIByR89JzP3",
	"9zSFFyP0Gma4SGV5b7NQYTMQnitpkRdUqOGez4ECx2m6RJwx+QKRmQZJ5BCTGYGkfX7X7zK3FhP+56G4",
	"J/nQ8ZBhzvSVMTqSvICtdsePLC2MKFNdEOqL8tpeh7EWZxL0oFuoqSdoutRKhFWMICwp3VLySwHIX2i/",
	"X7tCAS7T4rwc4hST7JKlJF7uym8MNq5qXTaFKj2hgET12y7SwVmG52BGrwleWx3I56ygcl+dacg6e7zr",
	"ddgHWrZYgln+AFN4R4TUHNrbmLayIggiIRP7Wfeo2kCYc7yMdthRV02yTAzr0IeqYjnRoGOfLdijx00W",
	"mCap3n12fzwuwGwM9qi4eg0tWi+VsQfDW9xhZce72+IiZuZi+P7q03MvXOF9ix10bPkZcKAxhAQWW+Q4",
	"dAJ5ypaQoIuTs6GijJRgKhFRVK1uWerYnOFYoimO7xU+V44dYgU+PNtctMR1kWWYL3vKKfVrruiWUb4H",
	"nMrFMhpEr2HOcQJJUC55z3xYNhdO6uBXg3ZW8aDprBOQS+oVgvJJvUpzYp1LISUIo8Z9jSUOqIbrFZzM",
	"INDN5TnCVSECxd4U7SkJ2SwIAspZmho1EnAy69wRCywWx+m8Pfz3WCwQTueME7nIyh2mFl0BUOpnxAK/",
	"/OZbq55p7RmS4XPAouCgYFE8NTDR65OzMz09Be6MswyNxVKM74FTSMcC4oITuRyTDI+xiAn52eq7fs6q",
	"rgV67sSTMCTZ9B0LTPM7LODbr4dAY5ZAgmyPCZoyJtGUUKyuUWy+rnfKgnzhvfpscGflCoW7XwomzWrN",
	"OIgFBSGCnep6a0GuerQUotjJ5cmVU9WHepZ5dnzfq2ePCtEPsER5MU1JjO5h2dXxab+OT2nCuNBrt77j",
	"3gfiiaJsTe1wTeYKFVfwSwEhsuusWhlZ1PnH7Uet7EOCzCkkKK7aGoJVS3tyHNL7+bafLWSFsvnTILon",
	"NGnP4wdCE3UEY2SwZRW/5STc6XJ1en2DnF3F3GkMMr35VjakDC8RoTN3+yknCTTR0r/+I06JWj5RTLWy",
	"xKJKXVNG6ARTde2YAiryBEtIRuiMohOcQXqCBXxyC5JWxA4VysJbIAOJE8t4N16XC424c5BYdSWsZLm5",
	"MqyLBK3cHIlSBNpj36bPttK2JDVLaR6O7Bzvdt6GpVq3RsJ/5zjPQUlFrKAJwvqCO4w5KLpBJ9dXA5Sx",
	"BFKjoLovpupkkCAQYZpecE5G3pYUo4fD0UoQ2hsVPuaEG3UDxIwmQa2Ubm/MLqX99QGnJCFyWeqnPEDU",
	"MMbUER1FhMqvXlaUqG7Qc+AKhfBRcrzKaFReNtr8tnZvaFmTVMdKVtD7B0plQ6U/cDjW/EvhOWd5kepP",
	"9rA/vjxDQjMFhXtdX80cK6aTZYXE0xQCtiNDXEHGe7MArW30DoTL0/Pq9w8n1386PFDgjNA5lvHCGsUV",
	"CY5Kdkwg1Ycq9ulhFU83jK+2JNOlhBBv0Fyevw9eFs5oYohMw8RLmjBtjN1Ec+NfCpxqhYtWNwR5UEEC",
	"/Pz27PXvsE4eEALPQxfgW/291BvpAwb0lfgelsi08uZv5RsiRFE/IGu35bUE7PRwq29pvwNiGuzRUXON",
	"OPbADzvuuBWV4Tzn7AGn4wQowel4hklacECivJuVU/dMdqJjMRCZVd4wATulVzW8cW2XbTloUGETaam3",
	"XIheW07xXGKuTAHLqyszd1C13MzffiP0g7qWodiryAEda9RBMkCvgRL1r8LQG0xSA9T2OpwSoqDuxqcb",
	"b179qaVts9vNk6LLxr2VZi7gCLFrPx1Kw10Vm11m5e0UkjQltLvLu6cNltcRz26rWvZTrmUecDXZpWNj",
	"f25QtAyb9u8GXbu24kkJSExSY8pjFBBWh4t0PCwuONfXCakYlfN4U+z7qjy81+I07LuhvlbcQV2UCn1x",
	"QDOWpuxRXZF+qKQINaR/m0C3AqyjhFot7XGYKDHVno2x8eECWmQBiyQW8oZjKgxGSZcDh6qHJMnA4KKE",
	"VZZtITHXMIU5y/0VJJTJBfAak1X3raHqK3zxEersDmh8igxTxAEnmonbeoiYo0jhyK0fnrJCWohL8ILC",
	"BZvqozd5q41SMugDqWY/cleN0bysWVm4Kmw8YqGlEGOtLnIzrC9jf/t1UMbmgEXQARM9n3ICsxfI1KjE",
	"eDfmM9Frprtc1dxQHVcz2/UgREvlzKqF3ZwRrde01zAy0CTIZuiGFzBAb3AqYICsbtTXBavyaBDpCp72",
	"t5+ytwGd7avx1XXd+FyOtHbqHX6Z1iezIjzi6y68KToZIxpEN5fnP2pdq1MyuwIjfWhEKNGjXTWOQQgy",
	"TaH5h2N8l5gLXfV6SWP940d17VQ1FAMr5Jk6juYchCKT2zzB1iqvDidX9bxIJclTuHikwIWG64HE8Bpi",
	"lmVEqKu/atRvdU5LBbOVZL35tsrq0+0Uhr0uOuuUuOysUSK5s0YdnCvImSCS8WUQ9QrjnQWt9fELy7V6",
	"kwJItwr6j9CqmdXw1s588FfQfOm7jitof0bmTbPoDsLWWyIDfW4lZVWn8DXEHOS+5LZ9wfe9lHmor1XI",
	"bvu7/WtL89r35hNdCeqylTan9rDGGrOrOdmJqLxvggd5znjIM9B3Yd6fB4B2lw6oQbjvHLcPV7a2VGGQ",
	"FxTke4oPeeF6P2dUcVDHSyrirq9XZqqtj4WozBQM2UbrVTR+70FHmS0CCNrTW7HVOaOnH3PFzoNyripH",
	"UFZwTvCKLBUUSZFqUw3JQIwmVKHD1iACffgzsv//cISG6JzQQoI4Qh/+/AFlVkd6MPzmryM0RN+zgreK",
	"Xn6lil7jpULvOaNyUa9xOPzqUNUIFh2+9Br/HeC+2fu3owm9LnK1dSBBasmxZAqIoap4VKpxMV1a85S1",
	"H6tuCEULBXLZHzwAX+pvL9S4H4YfjtAVpvOq1cHw1QeNuMOX6PhcUckrdHxuag8+HCHtvOMqHw4OX9ra",
	"QmoV0OFLuUCZxqFpM/5whK4l5BVYY9fGANNscW28NutzeVWhRHGdV16TCT01LrQKc+hg+Gpw+O3w5Vd2",
	"SUe9oxVOCiFZZg78Mzpjq6wGzYuONqqYKLMExbojF81gVyUIR1Mr7HVCqKFQrU/Vd8K6T0g/PmJm04bY",
	"fK9bY/PFUpAYp94gXwyuXwyufbupROodr+y2oy1MqXebbYuWH3TbhXFPsUWQTSFJIEDwf1+AXEDL+17t",
	"AdfImX+mjMnYyFseEUwZSwHT7gimhurJ989d74iLk2VYmjChTPYe7/ytHxckXmjzgG6Jevv76nipAGN9",
	"X47i6iCn9eqKWQiop/bkmU4E4oX2ALJe6WczNE0xvR+EVo8X1Hmoa2913af9YPxAm97ke3ce32kXhsMt",
	"ngbdXr2VRstW8Rzb6qjcs5OvYxVrzEWla6ciao/qBpUSsNyng80D7Vo8pe67GJIahKngqG+hPS0bjtEB",
	"d9DGRc2KKit3vS9NGE2zO0m1/rUWl/TJdLGrPWQ7NLMb4t8oELpQfuKZQSrlq/XrjHXTNoI5qO0OSWei",
	"gStbwaUW6Ox3nRm8Ps7mMxcs7ZT1bLEv8lnFs/4cM0ohturYklbayBDmgnX2OsxQbTE6e+0r+xsjhOnK",
	"tDz3JJnGdilF8XIUd/C7g0bBbZ0o/r0W1B1jqoU3YczbhBJJcEp+NQahMksA8IxQnA5KmCVzzQYIZNy1",
	"hji5oOnScN0GETdmNfAQuOH6+jrIUFSiRYW5K2BHfEldc1la9VsLKzGfg9xBYPPhu9GdhU2cZpwdJu91",
	"3j6DSo8aswGFGraFhAzkgiX1beobHm6p8fHWZoVYMr68AlEDepX6fhXEXs+rqtVHXY2aMyXpcCKXJwuI",
	"77s4X3fdJkeo80biWqBYNUE5cLXLjLfglsfSMHgsVZfc5pgGon2fRt0Y2eNx1Nn9GnvgBmiviNbFT9xS",
	"4fRFvmGstMtsQsahCVQjrarjw9Bdr4Suu0oFd09cd5pcrbjVReEtfpA3dD56lETdy+VyzzSnAzo2leSq",
	"LaOluGoma2Q4VbvEavscJ5kSjbPcIaTReTPopZ9rxP52qg2PNovpbiUyz/a+IvvlAG2we/OAzoPKM7WW",
	"GynMB7ba8439NwiXd23hNcyizSfW7O93ZAbxMk5hK+k+da33cINq6mOrzj/pWdVAwB6PqVDPXdTp59QK",
	"4bZ9HhmfBUsidUN6/cuGdNqAuklpjeIaFIHyEGhrqq2n2QsRjsrwS5Epmlqh1QjI6OK6vEF1ilhhE+1N",
	"rRNjnzVKLo5ur96tv4h2WS/XzXSbbXlx3XteP9Zv125uXbGRc3hN5p1BEokua/ZlzE3IxF0e4YPRaPSi",
	"L77qg26IvdK3ZSMclpbsdaKLzaKzJd+pA+dO3ISI+713WiXd2WO3TbfxvIjKkew8dlqu1TZ3UTO6mwWs",
	"516sIqz/jrnlPSecSBLjNBDgvQmLrAPqx4+3S6vBQ6UeQKFiB2SobK3HoGc66uCUDT6JV9govQDxXokn",
	"cusHs0fHk7pnTcsBxSgEu6Ez5fsCLOieFYJJsBQ67CSpw1ssyUOl0rO6rB0BrKsvg4F39ZN5Pzoq7UK9",
	"C8T2bG96FDW0lmoSNQ5gXWnsKttoxx1R2HCmCSHRmLaSDrWtKdSxXESdJ3XfoIanEZbx4tIkhgyaNRy1",
	"6IrIppCsz7BlCTE+Hw6OghKpZZaBzbBmMjwpqVsUsxn5OEAmZHwBaToUcpkCmqds6gbT8OvR8RwTKqQL",
	"gEiXKGU4ATOEhinDH98BnctFdPTym29rKS9/Ohj+FQ9/PR7+99FkMvx5NNH/+2kyufsfk8lwMvnzZPK3",
	"u788/49+9V787flkMvrJVAwVBxNrrs9eY1wSdsiW5HnH2m4MYT9tdiiuVj22lY3hG5XwMtBYJo9s2wxr",
	"zQZJjRE1lgVOq4iWXc8EK5DWcpF5h/Wu/K3tbBDYpLhtIdvPkA1bZP+gwHK9TIIibXx3dkmF82Bwkb8U",
	"nyQQ0D9Dtz9vKkOhVr5ZvcT+VFRO1XYNQPsEJlkKNHE4QF2QrWXK6Pn7i5vTI2NML33LbFI8DrLgtBaY",
	"+6Knbs56E/xDMDokc8o4lO4D5b1+f0qLfZy6ZUe7efIGb17qpNx547U2mznXnFPhtr1Wnaw6zx0/q52l",
	"++FkBoLklhLZzcOsh9zOJ1HSoYb1GFcNsXXuGYWZqU8z/p4vGYqmzmoSFTX4u2HD2+L2fiAeV1hgnjxi",
	"DtrJ1ngBEzp3Hku1nP779w+xMLjIyE/mIRLA1x61nBtlZQsr3C90xEs4AdsVTBmz8UWX7BE4JBezWU0j",
	"f/yIidTBUtYbwoTXzVISy0tciA0VoLUJeaC1yjxoA6X1u3utyJ9ToLg2zUB5UyVbKwwhI1CtiZ81a1zj",
	"tP3cty9c/ma7mbykLvAxZ152Nu24N5rQUxwvdKqOmHEOImc0MQHD1a3O7Cr7+EeMczwlKZHL0YSudwQ3",
	"k6htypilqXmXoPRe7hR3FZCdzkpK7Die2+R1omsP+w7JHX14NZSUaMITLJ5abupVz4qeQt5D3zEm0dnr",
	"TboyfvZbn6otf38lmjjGapYgPPWLkvteO+7bE+amM7OP5RI1bSgG9TXdkO21LnZrvGZyXVNbHzJM8dxE",
	"p+sDwByL+pWMOC0SVaKTl9rvXvLmhD1Se9NWB5bNLRIwqtt61yZKZztJ08yw7KIUQvba6dM2WE+2MooY",
	"6PdqqPSPcdP9Jz/GaxjY4zHe7ncDU2WF2tJOmd+w11hnzrko5MXM/vaChbdRvNeA9IYIlPqjBhs3opbr",
	"pWt160Tcrw0l3E/03uAPFpMYZHJWtaO5m+lA8zci7k3erU0eS0sIB+2oV76W5pS7Ol1src/Vc9n0xaTX",
	"xaqMHxn+SLIiq3Lp4TRlj37MhPH0lQzFNvW/ed+obFAx8jK3PcI6SIwplvFgvVOA2ywvNkW00WWYZzCq",
	"mMXyo04ddYQ+CBP+J0w2wAH6kJkPJqJPfViYDzp2cVR/h+j5345+Ohz+9W4ySf784m+TSfKTyBZ3/R8l",
	"OqUxUydXHwdSsHUNoWr3Yb2yWOLGc3E+R8lTkwzcJOLrnfTBDHVpG7u/v7OddE+nkRCiPadWlRVZWG1G",
	"NEUaxlN1pV71Szzgl3jArm5aVLeH0MB2n79DwtWOdCw47bHTXNUqT1dYPCv3nac99xONd7rtY5fXZUWa",
	"w0cvxtBt9gUWaApAkesgHFKY4imkuzy6d+wSW5qe9CU5z9Nllcy/I6C5/e6Zmefuy1aJ5DsIQN1E0ZY8",
	"1kCyjjY8i9iuVHLc4Q2lT2gsbQCnTyePWNRIpJ+zr2vxXVf0aD0IVdXlvd6+c70O/Cn1SJi3bgm2MEsG",
	"EF8u0Kg/VYZv5MFq5iD0KhpwWnWfCef/py1yAXJov4+w+end6ENNWPDwcodSEPuJU4VJIeXTb4Ct1G3M",
	"O4aVDyJ9b7paF9t3o/fCyvg+LT7YUKPRPwSj6x402D9Tdcn8nKlQP8Hs8VkiSuPiAihS8oxHvUSEToEO",
	"RqwWeXse3KUO6ai42b5sddLFCM3RvT+e71nV1+X49bdCO9HvaOP0ve28nhDGwx81Ia//EnEQY+7xEr3E",
	"MxJy4I9Xtde3MSTho0TPb2/eDF+9QIw3k6R7g+hAUpJ2roWq5y5nW5KRdwHtr1ZUiOqOjlWlZTxsG0Nz",
	"zoo8jB8112cC6RoD77oPRAuN2D0TZx+wBU5idPa6/nDeJOKMyUm0MoXBmlwFGUtgJYQ5cOu6p18sGKH/",
	"YoW+yhmYjeo9UxevGc5ISjBHLJY4rd7hxfou/ytw5vIKHXz79deaHrA5WmOS2QYmijbU5uuXBy/UXVIW",
	"JBkLkHP1jyTx/RJNrY4DlUEtOktE7Y1Aky2iMRnzYg1JQTHqCq8KvHBSi8I+wtiJLfaoU+Z/wvX8pO8Z",
	"Knreg55y53fOa7tuu8R7U8HSQq54Kb1kK5toAMOJIVsJbOZEXimAw3KNl8sPo7dE1p1SbWr/TTSiTg9q",
	"A/9nZO5i86tUoB05YFzx+htD1VXt6Ym266QWgq/ggayS7UypAroQ3otDK+FtZW4ogW+NOujS7a56cdyf",
	"bcMbvPcTdnblex/EzTefP10ize0STcYLzGWVaHIBabY2s5DWruY4Xh0lVdYK5RSyzw0qaar+WnO2HOI8",
	"H1ZDBMY3z4R1S/omYUTL+dLbgqaHYLIjp2FXJ86USI45SZeI2idTXBp2UYPaQ7e/4yI6J/SjJt55dBQd",
	"jl4eGp9Ik0D36LcIKJ6mir4MyAsmpNCUoX5FR26EUcwyS/Km2LCKaGw/GqV7dMlhRj66t0Y56EmdsELJ",
	"cF8NInuN0ayGcRkdvTookXuSFkICP7sMi04GX4prr3D1dUjV522pkUoKYwqq1hvpfmxCqxRru4eemm/T",
	"1g/lGC9/ngBHU5gpGURnBLSbNvHeiyuX4icLq6qUFCYxyhJnaeQmMWQPwDlJQIyWWao2ct+nXvadjbQj",
	"M2/rsFlImfc8bSj6/ubmsud5oxbqMnjmqK/uhDE33GdmXZ0vj2SeUstJ+U1vWQ2KgAfgnuHrkRMpge58",
	"WvH2aeUOG5cfbEljtOIcMyEPocnz8sZye/XOPtrDMkWyM2kVvuqio8M+0ZnUeXCM6wagXwrQhkuOM5DA",
	"BRJFvEBYHKFJNFZUPpZs7Cwif9O1/13XDomFK0/Ecvl+/0PQUWRvUl/5uMmK9Lt9T7GLk7PAS7WhcyfH",
	"8X0v2/HO23vle9DtMFzzLLAWlKrZZKo5JAh7Nx3NK1eE9+7ypPa13i7a1mWOjS26Mz3piXfG9JreN0Pl",
	"ZZGmoVeiz2bvmbw0+qzWW9HOCbF+EXvmt3k2Qn9fANXKP1V2nD7ipXg28PJwE4HyIk3VdU/n1pUkg0ar",
	"96qk1igrhEQ4NTkb9etV3VlmzJjRoDkZ3WtPU7fCT9mP+qPRl/pk+1uJ5zC1UiaNeON7iuhFfPqklLhb",
	"EH27w0AclZ8mwJ4kbKbO0jUvYQducDUS3W76Hplv8IL3emjNy4Mc5kRIvhyhGyXuZ3ipDmVcpRv1Gppn",
	"ekpvIsWVXGcDdcimjM7Vv/aCy3gm2vxY+P5BfU64jV8IX/3M1arDxbh2rwi19A8OK+XsLZy50p+sETMN",
	"lLscRF3vSRxtjpFSuDevGLY52va4KXVTgeiXTyvOdKK4A6Ern/xoIXVfsKsLnBqtr+LJex7MNPwn1V8X",
	"VG55S6mZ3g0OvJuIla06NRzr16xC66Yqkko3sr6rf16ddGCr+Xqdamnv1plHbetqA/Teq+c6IcmXVz98",
	"lPS9k7zHGSQ27bTZLnXNgppqQC60MlpLLvw0V4oNrxKeG147YqksUxJ/mQZXKwBwmqIcuCBaD1ilCNJS",
	"/gI/wMDyGqsIELqFAUan7Oa2rjk4AzZ0Spmsoum39GGoKptHB2uxzuEHLuzzwmV+whW+TCZYXTuAPmLh",
	"XjLu78CUQArbjEXSVEe/qOabjDdf8YbjMRLwS6GPS5t1v+b+6j2V6b3vWLqomAy4xhEIXTYfcDbnzwhd",
	"AU6GjKbLnk8+7uzCco51eknr1XsPS6NTtZpZo8mqJ21mfI4p+dUEwMZYwpxx9edzEbPcfBWQQixfOGIO",
	"UlG/A9PUDz+7qQ6x0Cp57sdYqrNOGEuF+z5QIsBEu6OO1ViTyD5C1PUogm7V6Zl0TBHL8S8FOCTqYYlO",
	"T1o6sBuN6jNRhSJ6PkyYds+zt6H2Est44bmel2J1mDBm+kHLBkdhHdvLxsEZ65xNgesrI3CSRMZ8YM5p",
	"Dhl70PurnoLNe4AsKJ8do/91ffEeXRqxoFRbhc05YVCNX7p9vZbpLaqAGrVOAZavMgm201wEUP6fBU5S",
	"kF9evfvyEHYnjVxZe1X4QnJVj/+wpi19IwnrbLv2Tbutu2i7k+U9k5Yjlm/jK2al67vjkj0A98wtlY1V",
	"8HhMaAIfR/8QO/AoJ3Uep8DllQ0IzbsjwtvzXNTzljd8cLXqXvUd9lztjNVyUVxKiJNOnFDI8G6D+AE4",
	"noMJJEPEewDHGhr1wITOR+iNPk2OVsdoPRPP6sFXz7Jn9eCrZ4tnncFXk0nyl+54qxx4DFR2ZiWtyhXW",
	"zIyM7yon87kSPEOYNEKPUSs8wNYpempEcG17CoelumG8tatNri7M3G1FhjUI2mFotrRFXe7oC2aK1FHs",
	"/XTwnbBUHXdW8UbsrGNAWYcJl69OzZ+o+WeEYvvBvgeqfp5c3nYtdcdDmYPotU5PGm7UFRM7iM5t/tFw",
	"u+4renWFXL7XAmbt7qykxu2PmY4pbnXArJrBNj71HYhU51SnIqEnUaxMVRCO4sU1f7DGrdXx/lVJGnUl",
	"xFWtEbqg6VK/xm6+5sCR4wzaZd7w1P0kbqxOplDqRnUcEjo/U9JpMO6sPEimIB8BaBmHrJuqyfwOZ0MZ",
	"ldt1QKzQLg389QnMuDePXfPcPjECjyy4da3Ss4lx6qIoEkafOQcRZMxK3m3yE8a/xkH35+tiPjcOXdpH",
	"xcIVO49hfb80IRADdICIdTU2+ln/Gv/Vy+A1/kvQ7V6DboUIij59xEc/D4jCo7v5dr3LKMJyaobjBaHQ",
	"OdTjYtkYQC20NU1M9CMSBYdJ5N4xQGcWIEMC+lXKXGrdEQeTfLAemPOASaoGHqFjdKXBRHGKudFIOK8v",
	"4eIeE0DTQm06MGkMnccbInJNTpJVabsq5KELqkTNIzSJros4BiEmkbqdezP95GQjcoiHmCbDzqchegQv",
	"ly8UajZRUkBFdP0ZpMnhd6wzOSu8QbfxYEHmi2GqZmqyCOr0z1Vq1JpjiEkNrUFLmQ6a0PbK8vPMvRLi",
	"OtEVEqj9mWHFnCimVp0z4yAWpqjYKAlLe5bHDpB20ZUHcbv0rJpDu7B8+6RjQDexdvHr+szbFc5ruAhB",
	"7WGnXbw2MYxtcqode9cQgvH+rUeZaYpwgVKOCpyb8MD9GvKCWqV3Sui9LjI/vBKcEiz08gtTw/zwauhI",
	"09hk63cjEGryr0Sl+lx/NmmNjCfRFCce6QyizajHQ81pOa/OsqsS2HaVd27qXUWrGh9b7LRLzh2+uopW",
	"dXvtUNouel0huV14VqG9XfjWW4gAgXlL0y79DodbVUkEA7hXp9FaGn/HcLKGwhUH6EHfQhZTRcHMZlOk",
	"TA5nrNA8eoqToQBpNzTYpIoZ8LlH09tysnIK1waC5ud3DqJmwXsm31gAm0Xf4eS6hLdZ6JJCNr+fu/m0",
	"ChrEWBb05UReWtn2O9wVY9slc23z1GuapYKHYLfs5tx2dcKjmuLyIgd6ff29tb+gBENmjmsv2fzB168C",
	"Ig5UxL3LTJts/ckQ7c791reSdk6flp2GttWjESAGGknWGcPZKyshokQcLyh1skCJqm+/rl808fDXg+Ff",
	"h3d/CWoh1UAdz327ZwVcKOckEmKRjKzVeRK9aKifvcK1Ypsetk5P9dX0V2BQo2gPi73luBuSwX8z5wPn",
	"XIzfMaOXa7/oh35lFCrzIBf25q8J+Oz4/bE1RqLjq9Pj8buLk+Obs4v3A/SoJX31sZ41SknDhOqYaY5Y",
	"DJgOtA3WtSy9fHTWMMwliYsUcySIBB1gqy8dWCLMAQ/0VrKIR8faAQiP38Pjz//F+P0AnRaKG4wvMSdO",
	"MVNQnE3JvGCFQF8N4wXmONYxD26ujUBc9HwSvT2/mURq1W9vTuxi98sZdttKJ9l0zZ0R6kyutpbJp1VI",
	"pq5GcZkQU+upaBJKpSlJ5kqdq5KeDitCmQy2c1A54YyeflTr6BQP+hX0txzH4CeV21wV6Bo/DSLp0ebG",
	"HZWE3boXySgIbe8t4zvntB9QbnsNmRW0bkV9bWKmn9zz+Ks8lnUguqVI3blZ5npcWDQGGY91QJ66cs5G",
	"yRFn2yYQfPKeFdVwxHrqkGGSRkeRBJz9xywl84WMZToiLHIOEppfvtEl6ERdfFmKbgBnSn7hqqm7Ktda",
	"t9w8fqp3cfc81OyFVTbZ5CU6wx7EKebGtKiT0EJm0zPMUgCpr/qQzJ07pXEekQsgHD0yfq82mjCpllMS",
	"AxVQ+bdGxzmOF4Bejg5ak3l8fBxhXTxifD62bcX43dnJ6fvr0+HL0cFoIbPUELnUy9VA0vHlWTSIHpxe",
	"MLJEaJMLKzqMjqKvRgejwypO8rdo7CUBsdlwnO7LREGG8vqdGM9mjE6qxtemcZXor9KHl2qRs6Rs3Nky",
	"MuQFQn7HkmUjyYbnbT7+h9VEmT29HU/qBOKpTubW09Zk3BZmF748OPys0IWWJFGr/fXBwacFrMx914Li",
	"O5ygEkgFyeHnguSW4kIutKOWRcpXnwuUN4xPSZIANXD89XPBUc9qr4F5+dmAuWEMnWO6dOSikxh98/kW",
	"6dqcAbe0VCQbNw8815fhTi4Z3alqK7jo+DfF/Z90LAHIkEcMToz4Vjqnd278NjN9C3IVJ62CbLUFeLXr",
	"4XpmjiRDc2PjIaoHm0TEHm/WA73ONQfecjWVDgUlvxRwZmyYxiP+rsVkD/5ATPbihy9crYOrff254CjV",
	"TF/42R75mZVuLfMau0SEnVzsLUibc8BmLLRZ/7rFwLcgXQ5EkyBxU3ZlWlmWVB9cNH019sOxntoZVsu3",
	"1LSmsYTgx+qFEz2sTmJQjRvMALlq3N+dLdol6eSBL82Gb25F5IVs/qHY5OdkT6jiT59P+Pvjin0eVzJM",
	"I8yCKgt8jmUcjnV0cYxeas7X6/iQblZL0bodH/JlJA3hvnjO3SYX4qEe+i97WMNaeEWv6/BnZklfrr1f",
	"BMT1HPiLhNiQEFGXiFgy40GUFwGR79Y+5rQpw70yAUp7ZrnV80q/O8/dI1/7wmL/GVnsF9bWX6qrsr/3",
	"NzNQFHpIaLV9of060e+4pduD/xHsCR1QfbEjfLEj/ItcJf/Q8lSL83VyxHUmg7cgN2WKb0GGOOJGUlf3",
	"eHu1C3wGbVcvzvhF+f/lbvcvzYueTP5rxwyMg8oY52T8cGhy6ZnW7VfMLacRiNHm3Uy7GFlGYAXBtha9",
	"3kM3n/E7a0/h6e7p/wcAAP//wSsoUd/iAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
