// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i3LcNrLor+ByT5Xt3XlIdpLrVdWpPYosO7qxHkePpM7x6MYYsmcGEQnQACh5klLV",
	"/Yf7h/dLbuFFgiQ4b8fZLe1WxSPi1Wg0uhuN7sbvUcyynFGgUkQHv0cinkGG9c+Ycfjlfn8MEu//wnKg",
	"OCe/HI4FSwsJF1jOVKUERMxJLgmj0UF0CTkHofpCmCJs66IJSQHlWM4GUS/KOcuBSwJ6kDzYz/UMqtaq",
	"CpIMYdMPo0jOAIm5kJAN0BmTgOQMS4TpHMFnIiShU1P1gaQpGgNi98AfOJESqIIAPuMsTyE6iIb3mA9T",
	"Nh3iPB+kbBr1IjnPVYmQnNBp9PhYfmHjXyGW0WOvAzF5fq0rhuaiukBsogHHeZ6SGKtSDQwtsujgg1kG",
	"AVEv+lTgJAUZqYGoxIQCj3rRDNIsum3C14s+91UP/XvMKc4UTj9EFpSjskf74T/LjssaVf/20w96mAWT",
	"dLCrtkClmi9O0/NJdPDh9+jfOEyig+gvw4qohpaihsEO35IUXE+PvQ06uIQUS3Jv6FH1wOFTQTgkChGa",
	"uG5bK7jK9I7p/U+YGxKtESxUBThJiKqL04talQYJ9RoEcUzvCWc0AyrRPeYEj1NAdzDv3+O0UOROuOgh",
	"QhWwkKCkUN0gXlBJMhggRU93MEeYJsi0ABzPUFYIqWh9DPIBgKJ9XeHlt69QPMMcxxK4GEQtXKxD3w43",
	"F4zLNp2rryjDea6gJRRNGM+wRKNoxoRUhQclOau/RhF6DoPpoIdG0eu913sHr/dG0Yv69rTfFdPAUgJX",
	"w/zv0Sj524H6z7+1d+sKsHN2TxLg32MR2KtHLMsYRdWKq1kgnKb+rtW7WbRZGa44wNpk7LjHYy9S27iD",
	"I3owqFrlmu//v//zf+srjVJGpz0kJOYSPRA5QxiloHCIGEe0yMbAe5pC7KIgytDDjEgQOY5hEGSE/tZy",
	"k73dhH7sGlzlEOuZEjXTjFAsGVcfLBUZIWSYWAcyLY/zOq+xzc5WtkK9nWaxHU0UX6zXdmy6o4Fltn6b",
	"x5Ji5md6kUssPvYiRmFTJhpAwka8NAjyRvAE0LtRT02sr8S6L0GwgsfwnmTEKDVNJcWUo1RX0Fs8IJjr",
	"mzvOiwC7uLgxnSh+p8ASA/TWsD0OauNoBj7GAhKltjR5SJ3Z7Q3+57chjpZBxvi8Pfip/m7H11uc5UYa",
	"oYISuQUkL7/9LttOE2ouxaJViBkVkmNCV12KtFzXTdhsB5VsNL0riWUhwmqfKVNKH0aC0Gla599Wi03g",
	"nhh26/TACw45trrdlWLf5udlQan5dcw5UwrbDb2j7EFxIrX/U5CQrK4f1mfgj9kq9IBolVVQtYocmK2C",
	"Cu5WkTeRFbB/I4C39TNe0EMRlp+FAI0Ep4mbI4T+jOSMiNoCiRkr0kRJV15QVNAEuNK9iEBEIMqk6UH1",
	"hoX+rbtR+5BQfRQppZAIaP7oOZm4v8cpvBigNzDBRSqFOumU3elzjW46VdoiL6hQwz2fAgWO03SOOGPy",
	"BSITDZLIISYTAklbfitCmLK+/XhjMeF/7os7kvcdD+nnjFCpECx5ARvtjp9YWhhVpjog1BflDUwIBYGw",
	"VmcSdK9bqKknaDzXR8hFjCCsKd1Q8qkA5C+0369doQCXaXFeDnGKSXbBUhLPt+U3BhuXtS6bSpWeUECj",
	"+n0b7eAkw1Mwo9cUr40E8ikrqNxVZxqyzh5vVxL2gZYtlmCWP8AU3hMhNYf2NqatrAiCSMjEbtY9qjYQ",
	"5hzPoy121GWTLBPDOrRQVSwn6nXssxl78LjJDNMk1bvP7o+HGZiNwR4UV6+hhQjEIWP3hrc4YWXHu93g",
	"IGbmYvj+Yum5E65w1mIHHVt+AhxoDCGFxRY5Dp1AnrI5JOj86KSvKCMlmEpEFFWrU5YSmxMcSzTG8Z3C",
	"58KxQ6zAh2eTg5a4KrIM8/mKekr9mCu6dZQfAKdyNo960RuYcpxAEtRLzpgPy/rKSR38atDOKh40nXUC",
	"ekm9QlA/qVdpTqxzKaQEIXWtN1jiNvIbFZzOIND1xSnCVSECxd4U7SkN2SwIAspZmhozEnAy6dwRMyxm",
	"h+m0PfwPWMwQTqeMEznLyh2mFl0BUNpnxAy//PY7a55p7RmS4VPAouCgYFE8NTDRq6OTEz09Be6EswwN",
	"xVwM74BTSIcC4oITOR+SDA+xiAn5xdq7fsmqrgV67tSTMCTZ+D0LTPN7LOC7b/pAY5ZAgmyPCRozJtGY",
	"UKyOUWy6rHfKgnzhTH02uLN6hcLdp4JJs1oTDmJGQYhgp7reUpCrHi2FKHZycXRpDIDhnmWeHd6t1LNH",
	"hehHmKO8GKckRncw7+r4eLWOj2nCuNBrt7zjlQXikaJsTe1wRaYKFZfwqYAQ2XVWRdy7qUDcftTGPiTI",
	"lEKC4qqtIVi1tEeHIbsf+Qm40CO26P7ixJahxAphLQXMN0iQUSOMZNIy1oJlT4kTJe4MPgboCrhq6I4m",
	"MaP3wNVUYjal5Leyt/IMkWK1sEgr8hSnhlqM2S/Dc8RB9YsK6vVgCQqdMg6I0Ak7QDMpc3EwHE6JHNy9",
	"FgPClB6UFVRtWEWPnIwLybgYJnCvNjOZ9jGPZ0RCLAsOQ5yTvgaWan45yJK/cGcYCFLYHaFJG5c/Epoo",
	"PQQjU9Nav0uUORF7eXx1jdwABq0Gg96iV8hUiCB04o6A5UoDTfQRSP8Rp0TRsCjG2mJk6UXheYCOMFVn",
	"rzGgIk+whGSATig6whmkR1jAF0eltkb3FcrCyMxA4sRKn7UV2XONuFOQWHUlrHq9vkWwax/aw0MkSj1w",
	"h32bPtuW63K7WkrzcGTneLs1Lypt2zUS/pnjPAelGrKCJgjrU34/5qDoBh1dXfZQxhJIjZXurhgr8ShB",
	"IMI0veCcDDy+JAb3+4OFILS5FXzOCTc2F4gZTYKmOd3e3D2VjOgepyQhcl4a6TxA1DDmvic6iAiVr15W",
	"lKi4zxS4QiF8lhwvujkrT1xtoVM7PLWu1FTHSmHS+wdKi0tlRHE41kxc4TlneZHqT1bjObw4QUIzBYV7",
	"XV/NXDFLkmWFxOMUAhdohriC0ud6Btrk6knFi+PT6vePR1d/2d9T4AzQKZbxzEoHRYKDUiYRSLVmgX16",
	"WCTYDOOrLcl4LiHEG7So42fBE9MJTQyRaZh4SROmjZEimht/KnCqrU7a5hLkQQUJ8PObkzd/wDp5QAg8",
	"DVkBbvT30nimBQxou8AdzJFp5c3fKnlEiKKuJdRMBksJ2BkjFx9V/wDENNijo+YaceyAH3Yc9Csqw3nO",
	"2T1OhwlQgtPhBJO04IBEeUAtp+7dW4qOxUBkUjmEBC5rvarhjWu7bCuDvQqbSKv+5UKstOUUzyXm3Bi4",
	"fnZl5iCulpv522+AflRnUxR7FTmgQ406SHroDVCi/lUYeotJaoDa3JBVQhQ0YPl0481rdWppX1xu507S",
	"ddG/kXky4A2ybT8dltNtrbtdd+ubWWVpSmh3l7ePayyvI57tVrXsp1zLPOBvs03H5hK+QdEy7N9w2+va",
	"tRVPSkBikpr7TEYBYSVcpONhccG5Pk5Ixajc0U+x78tSeC/FadiBRX2tuIM6KBX64IAmLE3Zgzoi/Vhp",
	"EWpI/zSBbgRYbxG1WtrpLlFqqpWNsXFkA1pkgWtZLOQ1x1QYjJIuLxZVD0mSgcFFCass20JijmEKc5b7",
	"K0gokzPgNSarzlt91Vf44COU7A6YvYoMU8QBJ5qJ23qIGFGkcOTWD49ZIS3EJXhB5YKNtehN3umbORk0",
	"BqjZD9xRYzAta1bXfBU2HrDQWoi5si9yM6yvY3/3TVDH5oBF0BKBno85gckLZGpUarwb85lYaabbHNXc",
	"UB1HM9t1L0RL5cyqhV2fES2/bqhhpKdJkE3QNS+gh97iVEAPWQOxbxBX5VEv0hU8E/hqFu8GdLavxlfX",
	"deNzOdLSqXc4p1rH1IrwiG+78KbodIyoF11fnP6kDc7G0l5ZD/2vVXWjk2j0KIWk3UEcgxBknELzD8cO",
	"LzAXuurVnMb6x0/qMKpqKLZWyBMlpKYchCKemzzB1mFBiSxX9bRIJclTOH+gwIWG657E8AZilmVECMK0",
	"K8Nqa3Zc2t6tfuvNt1VWn267aRCBnZq0N1JnnRLlnTXKteisUYf6EnImiGR8HlwhtTCdBa1l9AvLJX2b",
	"Aki3WPqP0OKaRfOW2HzwF9p8WXW5F2ycCZk2L5a30NTeERnocyMVrRLhVxBzkLtS+nYF3w9S5qG+FiG7",
	"7TH4r30U0N5LX+g8UVfM9IX0CvfZ5uLaqAVEVP5LQS0gZzzkW+k7ge/Oh0I7nAdsKNx3L9yFM2BbJTHI",
	"C54CVtQ98sL1fsqo4qCOl1TEXV+vzFRbHk1S3XEwZBstt+/4vQddjTYIwWhPb8FW54wef84VOw8qyaoc",
	"QVnBhREoslRQJEWq73lIBmIwogodtgYR6ONfkf3/xwPUR6eEFhLEAfr4148oswbWvf63fx+gPvqBFbxV",
	"9PKVKnqD5wq9p4zKWb3Gfv/VvqoRLNp/6TX+GeCu2ft3gxG9KnK1dSBBasmxZAqIvqp4UNqAMZ3buy17",
	"A6+6IRTNFMhlf3APfK6/vVDjfux/PECXmE6rVnv91x814vZfosNTRSWv0eGpqd37eIC0+5OrvN/bf2lr",
	"C6ntR/sv5QxlGoemzfDjAbqSkFdgDV0bA0yzxZXxe63P5XWFEsV1XntNRvTYOCErzKG9/uve/nf9l6/s",
	"kg5Wjvc4KoRkmRH4J3TCFl05NE9J+kbG3NUmKNYduXgQuypBOJomZa8TQg2FamOsPlDWvWpW4yNmNm2I",
	"zff6fXY+mwsS49Qb5OnK+unK+unKeo1uqnPFlkYP29EGl9G36/GGljt92xN2RyFqkI0hSSBA8D/PQM6g",
	"FcSh9oBr5C7QxozJ2CidHhGMGUsB0+5AuIbxznfzXu7PjZN5WKUyEXHWEuLc9h9mJJ7pCxbdEq3sNq7D",
	"7gLS5awcxdVBzm7YFfoSMPDtKMBBse5CO5LZ4IaTCRqnmN71QqvHC+oCHXTQg+7TfjDuxM2ghJ3HIGy1",
	"C8NRO4+9bufwyiZoq3j+kXVU7thX3LGKJRdupYewImqP6nqVGbXcp7314zVbPKXuAhtSnYSp4Khvph12",
	"G/71Aa/ixmnV6msLd72vUhlbvZOk2oJdC2/7YtbsxY7WHbbtNfFvrChdKD/yLpIq87V1D4510zaCOajt",
	"DkmnAnhpKziVr7PfZY4E9XHWn7lgaafCa4t9vdea7vXnmFEKsTVol7TSRoYwp8yTN2GGaovRyRv/uqQx",
	"QpiuTMtTT5NpbJfyPFKO4gS/EzQKbuuG8u+13AAxplp5E8ZBgFAiCU7Jb+ZKrUw2ATwjFKe9EmbJXLMe",
	"Ahl3rSFOzmk6N1y3QcSNWfU8BK65vr4hNhTcalFhDkzYEV9SN9+WfhGthZWYT0FuobD58F3rzsKXxGac",
	"LSbvdd6WQaVPktmAQg3bQkIGcsaS+jb1r25uqAkV0FcwsWR8fgmiBvSiq45FEHs9L6pWH3Uxak6UpsOJ",
	"nB/NIL7r4nzddZscoc4biWuBYtUE5cDVLjP+lhuKpX5QLFUn/eaYBqJdS6NujOxQHHV2v+RGdQ20V0Tr",
	"wnBuqHBGM/8SsbycWoeMQxOoRlpUx4ehu14JXXeVCu4Vcd15aW3VrS4Kb/GDvGH40qMk6lwu5zumOR0X",
	"tK4mV20ZrcVVM1miw6naJVbbcpxkSjXOcoeQRufN2KnVnEt2t1NtlL1ZTHcqkXm28xXZLQdog70yD+gU",
	"VN59c7mRwnxgoz3f2H+9cHnXFl7CLNp8Ysn+fk8mEM/jFDbS7lPXegcnqKZRuur8i8qqBgJ2KKZCPXdR",
	"p5+aLYTbtjwyDhyWROreBPUva9JpA+ompTWKa1AEykOgLam2nGbPRTiuxS9FpmhslVajIKPzq/IE1ali",
	"he+pr2udmEtqY+Ti6Oby/fKDaNcV7rKZbrItz69WntdP9dO1m1tXiO0U3pBpZ5hJosuafZk7N2TCdw/w",
	"3mAweLEqvuqDrom90sFnLRyWNyzLVBebjGlDvlMHzknchIi7nXda5W7aYbdNx/u8iMqR7Dy2Wq7Fjgei",
	"5nlgFtDcibWzA/yMueU9R5xIEuM0kCdgHRZZB9RPQ9AurQYPlXoAhYodkKGypT6X3tVRB6ds8Em84KLW",
	"yzOwUv6S3DoD7dD7pu5e1PLCMQbBbuhM+a4AC/qohWASLIWOe5LU4S2W5L4y6Vlb1pYA1s2XwdDFumTe",
	"jY1KO6FvA7GV7U23qobVUk2ixgGsP5FdZRsvuiUKGx5FISSaq62kw2xrCnU0HFHypO4g1XC3wjKeXZj8",
	"osFrDUctuiKymUjrM2zdhBjHFwdHQYnUOkvPJuozicKU1i2KyYR87iGTeWAGadoXcp4CmqZs7AbT8OvR",
	"8RQTKqQLIUnnKGU4ATOEhinDn98DncpZdPDy2+9qmVM/7PX/jvu/Hfb/+2A06v8yGOn/fRiNbv/HaNQf",
	"jf46Gv3j9m/P/2O1ei/+8Xw0GnwwFUPFwfysy5MgGZeELZJueS7CthtD2I/rCcXFpse2sTF8ohJeIiPL",
	"5JFtm2Ft2SCpuUSNZYHTKiZoW5lgFdJaSjtPWG/L39rOBoFNits3ZLsZsnEXuXpYZbleJs+Vvnx395IK",
	"58HwLH8pvkgopS9DN5c31UWhNr5Zu8TuTFTO1HYFQFcJ7bIUaCKZgLowZcuU0fOz8+vjA3OZXjrY2dyK",
	"HGTBaS20+cWKtjnrTfCrYLRPppRxKN0HynP97owWu5C6ZUfbuTMHT15KUm698Vqbzcg151m5aa9VJ4vk",
	"ueNnNVm6G05mIEhuKJHdPMx6yG0tiZIOM6zHuGqIrXPPKMxMfZrx93zJUDR1VpOoqMHfDWueFjf3A/G4",
	"wgzz5AFz0J6dxhWa0KnzWKr5Wu7eP8TC4GJLv5iHSABfO7RyrpXcL2xwP9dhP+E8fpcwZswGWV2wB+CQ",
	"nE8mNYv84QMmUkeMWW8IE6A4SUksL3Ah1jSA1ibkgdYq86ANlNbP7rUif06B4to0A+VNk2ytMISMQLUm",
	"fpascY3TrubDfu7SgNvN5KXFgc8585L8ace9wYge43imk53EjHMQOaOJCbmuTnVmV1mn7BjneExSIueD",
	"EV3uDW8mUduUMUtT87xF6b3cqe4qIDudlZTacTi1ORBF1x72HZI7+vBqKC3RxGhYPLV89aueFT2FvIe+",
	"Z0yikzfrdGWCDTaWqq2gB6WaOMZqliA89fOS+1457rsizE1nZh/LJWraUPTqa7om22sd7JZ4zeS6pr59",
	"yDDFUxPfrwWAEYv6sZU4LRJVonPg2u9eDvCEPVB70lYCy2ZnCVyq23pXJlRpM03TzLDsolRCdtrp4yZY",
	"Tza6FDHQ7/Si0hfjpvsvLsZrGNihGG/3u8ZVZYXa8p4yv2ZvsM49dF7I84n97UVMb2J4rwHpDREo9UcN",
	"Nm6EbtdLl9rWibhbGk+5mxDG3p8sMDPI5KxpR3M304Hmb0Tcmcxl67y4lhAO2lGvfHLNGXd11uFan4vn",
	"su7DW2+KRTlTMvyZZEVWZSPEacoe/JgJ4+krGYrtCxLmmayyQcXIyycSENaRckyxjHvrnQLc5smxmcaN",
	"LcO8plIFbpYfdfKtA/RRmBhIYfIp9tDHzHwwYY3qw8x80AGcg/pzVs//cfBhv//329Eo+euLf4xGyQeR",
	"zW5Xf9vqmMZMSa5VHEjB1jWEqt2H9cpiiRthfD5HyVOTU96kMlw5QYYZ6sI2dn9/bzvpnk4jO0Z7Tq0q",
	"C5L52pxyijSMp+pCu+pTUORTUORTUOSCblpbbwfxke0+/4C8vR35e3C6ArtxVat0b2EdtWQ+3hWCn7S/",
	"M3YBuww/C7JlPniBlo7jzbBAYwCKXAfhuMoUjyHd5gHLQ5cf1fSkLQV5ns6rhzE6QtvbbwiaeW6/bNW5",
	"ZAstsJso2urXEkiW0YZ3LbgtlRx2uIRpNQVLG8Xq08kDFjUSWc3j2bX4viuEth6Jq+ryld6RdL32/Cmt",
	"kHdx2RJscDcbQHy5QIPVqTJslghWM4LQq2jAadV9JpwTpL6WDJBD+62R9Z1+Gn2oCQseXu5QJms//64w",
	"ycR8+g2wlfpF+5ax9b1IHx4vlwU4Xuu9sDDIUasPNt5q8KtgdNnjILtnqi4npLsv1Y9Ze3yWiPKGdQYU",
	"KX3Go14iQlKggxGrRd6cB3fZhDoqrrcvW510MUIjunfH8z3XgmWpov2t0M4XPVg7C3Q7PSyE8fBnzevs",
	"v+odxJh7CEgv8YSEohjiRe31kRRJ+CzR85vrt/3XLxDjzVz73iA6mpaknWuh6rkT6oZk5J3CV7etKkR1",
	"hwir0jIouI2hKWdFHsaPmuszgXSNnmfzAKKVRuyeXLSPQQMnMTp5U3+EchRxxuQoWpjHYUnChowlsBDC",
	"HLj1X9QPXwzQf7FCH+UMzOb+IVMHrwnOSEowRyyWOK3etMbaoPEbcOYyTO199803mh6wEa0xyWwDE0oc",
	"avPNy70X6iwpC5IMBcip+keS+G6OxtbQg8rIHp0qo/bepkmZ0ZiMef2JpKAYdYVXBV44s0dhHzTtxBZ7",
	"0C8vfMH1/KJvgyp63oGx1ucuGyWsq+26zVIwjgVLCwkXWM50Dy3jZ8lW1jGDhlOEtrL4TIm8VACH9Rov",
	"qyNG74ise+baFyLWMQs7Y7DNfjAhU5egoEoK25EIxxUvPzFUXdVeMGn7j2ol+BLuySLdzpQqoAvhvd61",
	"EN5W+ooS+NaovS4D96LX+/3ZNlziV34O0q78yoK4+X76l0upulnK0XiGuaxSjs4gzZamV9Im5hzHi0PF",
	"ylqhxEr26U6lTdVfPs/mfZzn/WqIwPjGstqt6ZusGS0PVG8Lmh6CGZ/cNYOSOGMiOeYknSNqX95x2fxF",
	"DWoP3f6Oi+iU0M+aeKfRQbQ/eLlvHENNKuWD3yOgeJwq+jIgz5iQQlOG+hUduBEGMcssyZtiwyqiof1o",
	"bh6iCw4T8tm928tBT+qIFUqHe9WL7DFGsxrGZXTweq9E7lFaCAn85CKsOhl8Ka69wN/ZIVXL29IilRTm",
	"Pqxab6T7sVm9Uqwvf/TU/It9/d6SCXXgCXA0honSQXRuSLtpE+/txXIpPlhYVaWkMNlh5jhLIzeJPrsH",
	"zkkCYjDPUrWRV30xaNd5aTtyNLeEzUzKfEVpQ9EP19cXK8obtVAXQZmjvjoJY064z8y6OocmyTyjltPy",
	"my7DGhQB98C9278HTqQEurW04m1p5YSNS5I2pzFaIMdM3Edo8rw8sdxcvrdvP7FMkexEWoOvOujo2Fd0",
	"InUyIOO/AuhTAfr2luMMpL5iKuIZwuIAjaKhovKhZEN3I/IPXfvfde2QWrhQIpbL98cLQUeRK5P6wjdy",
	"FiRiXlWKnR+dBF59DsmdHMd3K12gb729F76t3o5FNk9sa0Wpmk2mmkOCsHfS0bxyQYzzNs/TX+ntou+6",
	"jNjYoDvTk554Z2Cz6X09VF4UaRp6cf1kcsbkhbFntd5dd56Y9YPYM7/NswH6eQZUG/9U2WH6gOfiWc/L",
	"yE4Eyos0Vcc9nWVZkgwarc5USa1RVgiJcGoSV+pH0LpT7Zgxo15zMrrXFe/7FX7KftQfjb7UJ9vfQjyH",
	"qZUyadQb311GL+LjF6XE7TIJtDsMBJP5uRKsJDHeAktelQ+c4Gokutn0PTJf4zX85dCaByw5TImQfD5A",
	"10rdz/BcCWVc5Vz1GprXnkqXKsWVXGc9JWRTRqfqX3vAZTwTbX4sfCepVSTc2q/tL34tbZFwMf7tC+JN",
	"fcFhtZydxXRX9pMlaqaBchtB1PWyyMH6GCmVe/MYZpujbY6b0jYVCAH6supMJ4o7ELrw8ZcWUncFuzrA",
	"qdFWNTx5r8yZhv+k9uuCyg1PKbWrd4MD7yRidatOC8fyNavQuq6JpLKNLO/qn9cmHdhqvl2nWtrbZdej",
	"tnW1AVbeq6c6K8vT+y8+SlY9k5zhDBKbe9tsl7plQU01oBdaHa2lF36ZI8WaRwnPDa8dtlWWKY2/zAWs",
	"DQA4TVEOXBBtB6zyJGktf4bvoWd5jTUECN3CAKPzlnNb1wjOwB06pUxWKQU29GGoKpu3K2sB3+GnTuwr",
	"1WWSxgW+TCZiXzuAPmDhHsRe3YEpgRQ2GYukqQ4BUs3XGW+64CnQQyTgU6HFpX16oOb+6r246j0TWrqo",
	"mDTAxhEIXTTfATfyZ4AuASd9RtP5ii+Hbu3Ccop1jk3r1XsHc2NTtZZZY8mqZ65mfIop+c1EAcdYwpRx",
	"9edzEbPcfBWQQixfOGIOUtFqAtO6Xwdfb1VCLLRKnvsxlkrWCeffbb73lAow0u6oQzXWKLLPUXW9DKFb",
	"dbuZU8Ry/KkAh0Q9LNE5WksvfmNRfSY8f/DKh6lyMw9KgtXY1AWW8czzvy/V6jBhTPS7qA2Owjq2lw0G",
	"NLdzNg+wb4zASRKZ6wMjpzlk7F7vr3oeOu8puqB+doj+19X5GbowakFptgpf54RBNX7p9hFkpreoAmrQ",
	"kgIsX3Ql2M71EUD5fxY4SUE+vX/49J56J41c2vuq8IHksh4EY6+29IkkbLPt2jfttu6g7STLGZOWI2Jq",
	"rYuKWen6Tlyye+DedUt1xyp4PCQ0gc+DX8UWPMppnYcpcHlpo2Lz7rD49jxn9eTtDR9cbbpXfYc9VzsD",
	"1lwom1LipFMnFDK80yC+B46nYKLpEPFeAbIXjXpgQqcD9FZLk4PFgWrPxLN6BNqz7Fk9Au3Z7FlnBNpo",
	"lPytO+gsBx4DlZ2pWatyhTUzI+O7ysl0qhTPECaN0mPMCvewcZ6iGhFc2Z7CsbluGG/tapOrKzO3G5Fh",
	"DYJ2LJ4tbVGXE33BdJk6lH81G3wnLFXHnVW8ETvrGFCWYcIl7VPzJ2r+GaHYfrAvw6qfRxc3XUvd8WRq",
	"L3qjc7SGG3UFBveiU5uENdyu+4heHSHnZ1rBrJ2dlda4uZjpmOJGAmbRDDbxqe9ApJJTnYaEFYliYb6G",
	"cCgzrvmDNU6tjvcvylSpKyGuag3QOU3n+lF/8zUHjhxn0C7zhqfuJntlJZlC+SuVOCR0eqK002DcWSlI",
	"xiAfAGgZjK2bqsn8AbKhDE3uEhALrEs9f30CM16Zx3Y+gGHiBIhReGTBrWuVnk2MUxdFkTD6zDmIIHOt",
	"5J0mn4KAv2wQcBz0Ab8qplPj1aYddezixM5tWuPPxIH00B4i1t/aGKl9W8arl0FbxlPk8U4jj4UI6n+r",
	"6NB+RhiFR3f873qhU4SV9QzHM0Khc6iH2bwxgFpoez8z0s+JFBxGkXvRAp1YgAwJ6PdJc6kNaBxMGsp6",
	"dNI9JqkaeIAO0aUGE8Up5sYs41zfhAv+TACNC8V5wCS0dG5/iMgl2WkWJXCrkIfOqdK3D9AouiriGIQY",
	"RYhxf6ZfnGxEDnEf06Tf+UjIChHc5VuVmk2UFFAR3epSwmRzPNQ5vRXeoPsGZUams36qZmrySepE4FWS",
	"3Jp3jEkSrkFLmY4c0Ze25eeJey/GdaIrJFD7M8OKOVFMrU1rwkHMTFGxVjqe9iwPHSDtoksP4nbpSTWH",
	"dmH5Ck7HgG5i7eI39Zm3K5zWcBGC2sNOu3hpiiDb5Fh7Ny8hBOMCXQ+10xThosUcFThf6Z771ecFtZb/",
	"lNA7XWR+eCU4JVjo5Remhvnh1dDhtrF5t8GNQKjJxBOVdwj6s0lwZdypxjjxSKcXrUc9HmqOy3l1ll2W",
	"wLarvHdT7ypa1PjQYqddcurw1VW0qNsrh9J20ZsKye3Ckwrt7cJ33kIECMxbmnbp9zjcqkonGcC9kkZL",
	"afw9w8kSClccYAX6FrIYKwpmNq8mZbI/YYXm0WOc9AVIu6HBptfMgE89mt6Uk5VTuDIQND+/dxA1C86Y",
	"fGsBbBZ9j5OrEt5moUsP2vx+6ubTKmgQY1mwKifyEgy3X2SvGNs2OYybUq95NxcUgt26m/Nd1qmvatbb",
	"8xzo1dUP9hIKJRgyI669Zwf2vnkdUHGgIu5tZtpk64+GaLfut76VtIf+uOw0tK0ejALR00iyHinu0rZS",
	"IkrE8YJSpwuUqPrum/ppG/d/2+v/vX/7t6ApVg3U8fC7e2DCxbOOIiFmycBevY+iFw0bvFe4VG3Tw9bp",
	"qb6a/gr0ahTtYXFlPe6aZPDfzDkCOj/r98wYJ9tvO6LfGIXqjpQLa/7QBHxyeHZob2TR4eXx4fD9+dHh",
	"9cn5WQ89aE1ffaznD1PaMKE6cJwjFgOm5pDtWpauTjp/HOaSxEWKORJEgo4y1ocOLBHmgHt6K1nEo0Pt",
	"BYWHZ/Dwy38xftdDx4XiBsMLzImzThUUZ2MyLVgh0Kt+PMMcxzrww821EY2Mno+id6fXo0it+s31kV3s",
	"1bLH3bQSizb9kys7h7C1TGa1QjJ1NIrL1KjaWEeTUFJVSTJX6vy19HRYEUrnsJmXzhFn9PizWkf3Go5+",
	"D/8dxzH46QXXt4e6xo+9SHq0uXZHJWG3zkUyCkK78pbxPZTaT2m3XafMClrfqlUvBk0/uef2WLlt62h8",
	"S5G6c7PM9eC4aAgyHuqoRHXknAySA842TSX56D0wq+GI9dQhwySNDiIJOPuPSUqmMxnLdEBY5LxENL98",
	"q0vQkTr4shRdA86U/sJVU3dUrrVu+bp8qHdx+zzU7IU1NtkMLjrXIsQp5uZ+VacjhszmqJikAFIf9SGZ",
	"Op9S40EjZ0A4emD8Tm00YZJupyQGKqBy8o0OcxzPAL0c7LUm8/DwMMC6eMD4dGjbiuH7k6Pjs6vj/svB",
	"3mAms9QQudTL1UDS4cVJ1IvunXE0skRo00wrOowOoleDvcF+FSz6ezT0MqHYlEDO9mVCQUMZHo+MezdG",
	"R1XjK9O4SvlYXQqUZpGTpGzc2TIy5AVCfs+SeSPTiOdyP/zVWqLMnt6MJ3UC8Vgnc+tubHKvC7MLX+7t",
	"f1XoQkuSqNX+Zm/vywJWJgBsQfE9TlAJpIJk/2tBckNxIWfaW80i5dXXAuUt42OSJEANHH//WnDU3zfQ",
	"wLz8asBcM4ZOMZ07ctGZnL79eot0ZWTADS0NycbXBU/1YbiTS0a3qtoCLjr8XXH/Rx1QATLkFoQTo76V",
	"HvqdG7/NTN+BXMRJq0hjfQ2+2P9yOTNHkqGpueMhqgebScWKN+uGX+eaPW+5mkaHgpJPBZyYi1wTFnDb",
	"YrJ7fyIme/7jE1fr4GrffC04SjPTEz/bIT+z2q1lXkOXjbGTi70DaRMv2LSNNvVhtxr4DqRLBGmyRK7L",
	"rkwry5Lqg4umw8puONZjO81s+aqetjSWEPxUvXWjh9WZHKpxg2kwF437h7NFuySdPPCl2fDNrYi8uNU/",
	"FZv8muwJVfzp6yl/f161z+NKhmmEWVB1A59jGYcDPl0wp5ef9M0yPqSb1fLUbsaHfB1JQ7grnnO7zoG4",
	"r4f+2w7WsBZjstJx+CuzpKdj75OCuJwDP2mIDQ0RdamIJTPuRXkRUPlu7LNe6zLcSxOltWOWWz209Yfz",
	"3B3ytScW+8/IYp9Y2+paXZUCf/VrBopCT0otvl9ov1P1B27p9uB/hvuEDqie7hGe7hH+RY6Sf2p9qsX5",
	"OjnisiuDdyDXZYrvQIY44lpaV/d4O70X+ArWrpU445Px/+ls9y/Nix5NEnDHDIyDyhDnZHi/bxIKmtbt",
	"9+wtpxGI0ebZTLsYWUZgFcG2Fb3eQzef8TtrT+Hx9vH/BwAA//8KPZo/LuUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
