// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8/W/bOJb/CqFZoLtz/kh7vcWOgcMhTdqZYJrGsJM94JrcgpaebW4lUiUpezyF//cD",
	"vyRKomw5TXpYdH5pHZF87/Hx8X1LX6KYZTmjQKWIJl8iEa8hw/rneZ6nJMaSMDqXWBb6Yc5ZDlwS0H9R",
	"nIH6PwERc5KrqdEk+qXIMEUccIIXKSA1CbElkmtAuII5igaR3OUQTSIhOaGraD+I1KJdG+LtGhAtsgVw",
	"BShmVGJCgQu0XZN4jTAHjW6HCO2JRkjMzY7rmD6UWNwcxBYC+AYStGT8AHRCJayAK/CiZNefOCyjSfTD",
	"uOLy2LJ43OLvrQK01+R9LgiHJJp8NCx2jPEoL7E8lBSwxT8hloqAMOjJlwhokSmoUw451twYRHMF0Pyc",
	"FZSaX285ZzwaRHf0E2VbGg2iC5blKUhIPIyWo4Pot6GCPNxgrugVCkWLBh9na9AjojVWUdUacmS2Biq6",
	"W0PeRuqsEvMiyzDfdUk7oUt2VNrVJJ5peCgBiUlK6EqLTYqFRGInJGS+CCHJMRWkU1ZPFqb6NoJC1U90",
	"AoA8EfoFcCrXSiYvYcVxAklAbE4WlTrOCkfnFA9555yAlNQnlOTuB9HF9G4GghU8hmtGiWR8nkOsdo7T",
	"9GYZTT4ePonQ4r0GzGhCjNA0ZagccrpNWNkRWukwCgiLHGLp9GhccA5UInWQVrkSgc6nV8ihV7JUF18l",
	"f7elrN2SkOq+dXIqSQYGU0laJadKF3KWabqMKCHJEKZMroErxOYKRJMowRKGClZIsjMQAq+OGxA7DxGa",
	"6NOjq5I7eMEKaSk+fI2cFv8ZKHAcPga1+1EGEidY4tGqnInkGssGN7ZYIAESLbCABBW5QVtunFD519dB",
	"48ABixDyPy84geVfkBkvjU2J8YXotc9+6qIUOKvr9g5Sz2VBraIhlBQMQgJXbr86/ZASapLnqZ1bXigw",
	"73Aq4GRF04BrYTWeOtCNxzUdUeODR915nnO20droQt28pRJY8J5eAiX6xztMUqO14hiEIIsUmn+4qzzF",
	"XOip8x2N9Y+bDfAU5zmhqzmkEEvGFcP/jlOihu/yBFtjqtSPe3xdpJLkKdxsle9Uzu/HureUszTNgMoZ",
	"fC5AyPBW52SlbPUJc0qOdM4oWTWDnAmlVHdBPin2dA60mOkPlox9lwLIDu7qMcfLS9iQGDxGmwc+u82T",
	"FtNvIctTLOHvwAVh1J7B3s1vKwbzHHHIOQh1HRFG+XonSIxTlOjBtrLHObEI2gDPp1d2DCWwJBSE1jQb",
	"8wwSZK57aVZKzEYZsiXCFJnLOkJzpVW5QGLNijRR6moDXCIOMVtR8nsJTZsI4wZJEBIpjcgpTtEGpwUM",
	"EKYJyvAOcVBwUUE9CHqKGKFrxo2DNUFrKXMxGY9XRI4+/U2MCFP6KisokbuxMqKcLAp1cOMENpCOBVkN",
	"MY/XREIsCw5jnJOhJpZqd2CUJT9wKxEipFc/EZq0WfkroQki6kTMTENqxTHn+83ezm+Rg2+4ahjoHWvF",
	"S8UHQpfAzUxtaxUUoEnOCLWmKCXaAygWGZHqkPRdUWweoQtMKZNoAahQEgrJCF1RdIEzSC+wgGfnpOKe",
	"GCqWibDhNyb2mLm50Sy6Bom1ZbNu2KEV1S3sbwvtGmsIGzbNu0dWBjzyQ6bLQKt5mh3hhOMATowtwem0",
	"Nn5S7KhQ10XzGufqqgYCDsMWEJ7/UNEvjF/86HijxUG9zQpuN88uGF2SVRe3ONAEOCSdWs2pNOshJ05r",
	"mmVKMS3JKuAyNcht4jlIr2AptEldzaYXb+1VVX+3fTRlohi9ugyMNsipwfJXdtN1pXxNTmRnHNvziIPQ",
	"7Fm3I8qjx9sB6OujbBMDlBE2cXiexlM+RPypsfVRWH6GBgtRdxSrlMYdFUWeM94/GRPEXKIIjpZ4g6MV",
	"MR3DHoXlzm/mLpRuHHkWDAOZkBwA6VGbReTobvb++CU2ALuP4GbemeMJk9JQLjdzQ9XXU1J6oR30xHnR",
	"T0LrgIxkDqKEiE9fsz6DjPXVFCEIDW6o3ZRALXV9edOdf/pvzG1+8IITqdziR2eiQoj9RFd7tEIeGvUI",
	"Cg07IkNjfrzpuTVtCdGGrS2y74mQNlu+JKvS+dRWn0jIjA9C1JKMUCwZ92DvPujMvgXupIFR6JEA+5lI",
	"Y8qnnG1IAjYFNji86tdiAZyCBDGHmIM8afEVTQmFR2D9Rco8tCwklPYB5hzv1N9VGaJ9KBmW8XqKpYpx",
	"jF5xHM/Nw2gS/e9HPPz9Qf1zNvxp+I/Rw49/CpmpOtp9gDDW04hZ9WvqHzbSaQeHCo+tf5hoJTOJTCtI",
	"hUmJ1cXohHxoiJPGR01OYWOGf3sPdCXX0eTVf/x10GTr+fB/zoY/Te7vh/8Y3d/f3//4SObuO5VTpbBD",
	"0boZ9WP2sMdis6cqpHahPLJrVRAoOSapqTnFssBple/FByL/yjPvJxeBYMWIt4lLxIF8tbdFTabJshpQ",
	"hsxgttqnvpcQVbnz8EW0GvD4XmtBxn4Qld7io/xABUE5nXMAHZH0y3ufcF9LLLUbe6otPiGus+Jbj+jc",
	"Db2yrnkPANX8/SCySYh+S+/M5I5o0pPKGlWDutz7DPMPuRQWfQoVZRV/vAPt9ky+QaHQxq+uvPJ0ocxX",
	"VQe7QHh+2Y22xeGy4AwWjNmE6ZRtVZx9s1w+0kurUeFhbY15hARG6z5YbcgnNzBc20FgPODB1a5R0HCU",
	"M2xaEbQTRxIxLgqS6CxqQcnnAtIdIglQSZY7L+ERsAderi5c8jr3Zih9rsM2tGiCbUmdYo7JYdRhvmFM",
	"oqvLU0ApgnUm3ew/TOeNm4TMrP4Imkk9nyXlPtpUdN+AupJ68hyGvfxGOz3l5a/R/bjL3wbhXf67/JZd",
	"Yqm4elPIm6X97dVJHnPTayg9FIFRH2twcaNgUx/1LywRn56+D2DQlAn12BS9iC36WndbV7mJ+IQKYRMN",
	"dRHLsfJ9Q9ckIVzXrHZIzVEKw3nwCnwd5uF7onG0JUGxp1UObNPSmlIvYdmChSYK6zohThWxoJcddHD/",
	"KG39Udr67kpbret0WpWrvfwRBS9Lacg4dPQH4LRtHbHrCmjJnBtxrT4g0HYNcg2mF8apjDUWaAFAkZvv",
	"qbIFYylgHSe60XPZjelcKhlXwHXHE5a2pdRHt8WihqlflOdWvNl1Y3+zc9gbTbJqlAetfYoXkIpDdcPW",
	"kjpuA6DmXdpHkuky4c6ps5Y75WVF6iJjz7OXXDgresRYqGmGSG+iyR205r4QSGK+ApthaJuMWPA2ylhw",
	"g2D69noINGYJJGj668X8h5dnKK6aUZAw3ShOHoLHkjSSQv0Lzk9wpOfNg3TtagK4diS3RFnU6myJcC7m",
	"dg0UKSULJVM1U6rGncNnrzjb79g78mUdE09LnbWABNNipTo6SU+Wemw/iDypCMiTJzItuVIyBIkvVkEx",
	"Oph0a/d8QnjnX5tS6865BI9aB9Dt3G1Xd6ee75o6j/qgZZvgfhDp3k0S2xye0yMnlTBCtRMXxLROw73e",
	"cJhCD4hdEuJSuCrSO5pob13FEo2+AyJnCsKXjlAh8BqE66freOXCM0rVXM/ZY6gQgLAxYWJHY2RG7mkw",
	"2a519Aw2xDnvx1oxSvJaiwddwUmzf8LwJBzEdFR/nvRQlA8aPJUlSWHaGcTp0M2yXs1UipqDPQmRMyq0",
	"khGSce0ulRNtv0+tC2YUPo9vfPyiWC7Jb21UU8zLvva72XtjvWKWgUB4Ka3rt8BCj47QlUQxpojQOC0S",
	"QJ8L0JEuxxlIHa0V8RphMbmnY8XEsWRjF1z8l578n3pyiMZD8lce11GRcycelrnOUuWTSh0x6dBOl0Ly",
	"Ao7tw8IIb+NgufZJtyI0/OAVylhB5bRLu3VobzMgchz30O327atqxcBDelQSKtLDTLzWjRDP87aJF2C2",
	"blw1pnSIi+7MxcNpinIVAAoJSdU1gLJCB14bGNgIyV5AoVeYXQmlD7idG3MI+uI6fq/Kk490eavJ5i2M",
	"ne/vBhsbNT32PQQhcZb3L9glkMIjl64OvG6i3PbPBdC4fLmxllzBSNjkIPJeRSkVu1BSZgMeNGV5kWIv",
	"FW7MwAjNACdDRtNdz7dTvjoWcW2nJmf0CXZC579Mnsvqdkx1/kZAomwI4ytMye+g5ynPeMW4+vPPIma5",
	"eSp0G/5fnJgFzzf8Lqpvw+zcUPlhS4GHDsjLa2GJ2JYKlzc0zwfK9N7rPMlYobqPkGFy12unelV3+pIi",
	"luPPBTj+abS2zENsMlO/x8RfCC/PWHWnVenLoHlrcW1m2137dRiF4hXXA9ur9q4nP7p35hv1xrQajTsP",
	"8l+3f+YxnTCntkk7ys9T4HJWhFqla7xrX791kWE6LCtmjUyQzpUp2OGMTNGldy/tSC3zxzbAvdwf3gDH",
	"KzCVEkS8t8AXsGTcIiZ0NULv9IWfOB2+ZGnKtkYTvxAvdH1DgIqhxQC9yMyDjNBCgnqwNg/WrODqz8T8",
	"meCdlhCvren+Pvm3jyJbJw/BTqYceAxUBiNuHVCU44p1ZlsmT8TJaqWsdoidZk+mZ30Dffpkaoc+t4vC",
	"lUYH0Tur2j7qpuWohNWQeTXJYHuorsH3q0F2IqkAd07xMHbOMaR4u3E3PZTcyMx7aernxfSuM7cTfofZ",
	"VDU7FWFHxdP5qV3rur3YKt/ikjFWF57WUNqxm2O9nYfoOmISOjixD5xS2GRip/IOWQg9CXE1a4RuaLoz",
	"L3rrpzkorWGERGcTjVI52WpUujdgN/zTCL6ngrM8JXR1pRwNmzvtUKULkFsAWho7vVTt69m0I7pWUcYC",
	"EEY6TCcbQNaRbWjOjy+HPz3c3yc/dqrPZs7R48vAP8sASwJBoG4rNA0gKYmBCqi+lRKd5zheA3o1OosG",
	"UcHTaBK5MuV2ux1hPTxifDW2a8X4/dXF2w/zt8NXo7PRWmY6Ey2JVPY0usmBIvuG6DWmeAU6hX8+vUJD",
	"hFfqN1SvD22cTxMV1NTHE9t9Q3FOokn076Oz0UubXNMyNsY5GW9ejk0iSYy/qG3sx87867QjBOprKzBZ",
	"+mWRpmUcUzU5aD/WPIXEZqmqBhxGr5JoEv2sYueWe6qIc8kerToaH3DxHP4SLlEjOmHo4oTquyru2E1K",
	"xNyfYGKg81sJumkENT0ii1WnnCq0eu6sNbUb7YP2NnXCTx/Iq7Mz65NLMK+XeY2P43/aTwtU8A4riRZ3",
	"tfQ2sgW/Khl5dfY68LUchhwh+0H0+uzlk5FmigoBau4oLuRaR4iJQfr6+ZF+YPIdK6hF+NPzI3RfqqHL",
	"lLg+dLzS7ogV6gf1rON2Vh0BeRG4mxzyFMd+Ba1+HS/D13FmltWql0cuox99Xz7lZXwwk0HIN8x8MOpJ",
	"zsPSuK8bBEXM/hmvoY81dPVePyGuTol7gxPkWrm+k7t85FJVFXHXgKRvFBPBK2VaRbwqui5Md1ylC50b",
	"bffQPY9Ut/H0EvCXz01Ao7yteZIYW/O3b4v7PDWfj5vZhuLv7Nb9/xq01j07dg2tmev0PdVZNkxaJQUB",
	"s4aT0E08aNhMtZWugOecUNnZjfGU5u6ZrE+vC+IM0XdlFIKCqVNhupdVi4WJ4MbR/mH/fwEAAP//qsWQ",
	"EUtTAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
