// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8/W/bOJb/CqFZoLtz/kh7vcWOgcMhTdqZYJrGcJI94JrcgpaeZW4lUiUpZzyF//cD",
	"vyRKomw5TXpYdH5pHZF87/Hx8X1LX6KY5QWjQKWIZl8iEa8hx/rnaVFkJMaSMHotsSz1w4KzArgkoP+i",
	"OAf1fwIi5qRQU6NZ9EuZY4o44AQvM0BqEmIrJNeAcA1zEo0iuS0gmkVCckLTaDeK1KJtF+LNGhAt8yVw",
	"BShmVGJCgQv0sCbxGmEOGt0WEToQjZCYmx03MX2osLg5iC0F8A0kaMX4HuiESkiBK/CiYtefOKyiWfTD",
	"tOby1LJ42uHvjQK00+R9LgmHJJp9NCx2jPEor7DcVxSw5T8hloqAMOjZlwhomSuocw4F1twYRdcKoPm5",
	"KCk1v95yzng0im7pJ8oeaDSKzlheZCAh8TBajo6i38YK8niDuaJXKBQdGnycnUGPiM5YTVVnyJHZGajp",
	"7gx5G2mySlyXeY75tk/aCV2xg9KuJvFcw0MJSEwyQlMtNhkWEomtkJD7IoQkx1SQXlk9Wpia2wgK1TDR",
	"CQDyROgXwJlcK5k8h5TjBJKA2BwtKk2cNY7eKR7y3jkBKWlOqMjdjaKz+e0CBCt5DJeMEsn4dQGx2jnO",
	"sqtVNPu4/yRCi3caMKMJMULTlqFqyOk2YWVHaKXDKCAsCoil06NxyTlQidRBWuVKBDqdXyCHXslSU3yV",
	"/N1UsnZDQqr7xsmpJDkYTBVptZwqXchZrukyooQkQ5gyuQauEJsrEM2iBEsYK1ghyc5BCJweNiB2HiI0",
	"0adH04o7eMlKaSnef42cFv8ZKHAcPga1+0kOEidY4klazURyjWWLGw9YIAESLbGABJWFQVttnFD519dB",
	"48ABixDyPy85gdVfkBmvjE2F8YUYtM9h6qISOKvrdg7SwGVBraIhVBSMQgJXbb8+/ZASapPnqZ0bXiow",
	"73Am4GhF04JrYbWeOtCtxw0d0eCDR91pUXC20droTN28lRJY8J6eAyX6xztMMqO14hiEIMsM2n+4qzzH",
	"XOip11sa6x9XG+AZLgpC02vIIJaMK4b/HWdEDd8WCbbGVKkf9/iyzCQpMrh6UL5TNX8Y695SzrIsByoX",
	"8LkEIcNbvSapstVHzKk40jujYtUCCiaUUt0G+aTY0zvQYaY/WDH2XQYge7irxxwvz2FDYvAYbR747DZP",
	"Oky/gbzIsIS/AxeEUXsGOze/qxjMc8Sh4CDUdUQYFeutIDHOUKIHu8oeF8Qi6AI8nV/YMZTAilAQWtNs",
	"zDNIkLnulVmpMBtlyFYIU2Qu6wRdK63KBRJrVmaJUlcb4BJxiFlKye8VNG0ijBskQUikNCKnOEMbnJUw",
	"QpgmKMdbxEHBRSX1IOgpYoIuGTcO1gytpSzEbDpNiZx8+puYEKb0VV5SIrdTZUQ5WZbq4KYJbCCbCpKO",
	"MY/XREIsSw5TXJCxJpZqd2CSJz9wKxEipFc/EZp0WfkroQki6kTMTENqzTHn+y3eXt8gB99w1TDQO9aa",
	"l4oPhK6Am5na1iooQJOCEWpNUUa0B1AucyLVIem7otg8QWeYUibRElCpJBSSCbqg6AznkJ1hAc/OScU9",
	"MVYsE2HDb0zsIXNzpVl0CRJry2bdsH0r6ls43BbaNdYQtmyad4+sDHjkh0yXgdbwNHvCCccBnBhbgrN5",
	"Y/yo2FGhbormJS7UVQ0EHIYtIDz/oaZfGL/40fFGh4N6mzXcfp6dMboiaR+3ONAEOCS9Ws2pNOshJ05r",
	"mmVKMa1IGnCZWuS28eylV7AMuqSmi/nZW3tV1d9dH02ZKEYvzgOjLXIasPyV/XRdKF+TE9kbxw484iA0",
	"e9bdiPLg8fYA+voo28QAVYRNHJ6n8ZT3EX9sbH0Qlp+hwUI0HcU6pXFLRVkUjA9PxgQxVyiCoxXe4GhN",
	"TM+wR2G186trF0q3jjwPhoFMSA6A9KjNInJ0u3h/+BIbgP1HcHXdm+MJk9JSLlfXhqqvp6TyQnvoiYty",
	"mIQ2ARnJHEUJEZ++Zn0OORuqKUIQWtxQu6mAWuqG8qY///TfmNv84BknUrnFj85EhRD7ia7uaI08NOoR",
	"FBp2RIbG/HjTc2u6EqINW1dk3xMhbbZ8RdLK+dRWn0jIjQ9C1JKcUCwZ92BvP+jMvgXupIFRGJAA+5lI",
	"Y8rnnG1IAjYFNtq/6tdyCZyCBHENMQd51OILmhEKj8D6i5RFaFlIKO0DzDneqr/rMkT3UHIs4/UcSxXj",
	"GL3iOF6Yh9Es+t+PePz7vfrnZPzT+B+T+x//FDJTTbS7AGFsoBGz6tfUP2yk0w0OFR5b/zDRSm4SmVaQ",
	"SpMSa4rREfnQECeNj5ocw8Yc//YeaCrX0ezVf/x11Gbr6fh/TsY/ze7uxv+Y3N3d3f34SObuepVTrbBD",
	"0boZ9WP2sMdis6cqpHahPLJrVRAoOSaZqTnFssRZne/FeyL/2jMfJheBYMWIt4lLxJ58tbdFTabJshpQ",
	"hsxgttqnfpAQ1bnz8EW0GvDwXhtBxm4UVd7io/zAI29ftaZx/461rEdEaVYYm/GZu28X1tEeAKCevxtF",
	"NqUwbOmtmVzjtqtPdWQ0pE7QdiFqsWxsZNQUfJ/H/ilX0qIPrt5MzVKfxH7f5BuUCm0E6wosTxfMfFV9",
	"sA+E55ldaWscLgwuYMmYTZnO2YOKtK9Wq0f6aQ0qPKydMY+QwGjTC2sM+eQGhhs7CIwHfLjG1QuajmqG",
	"TSyCduNIIqZlSRKdRy0p+VxCtkUkASrJauulPAIWwcvWhYtep94MpdF14IaWbbAdqVPMMVmMJsw3jEl0",
	"cX4MKEWwzqWb/YfpvHKTkJk1HEE7reezpNpHl4r+G9BUbE+exbCX36iip7z8Dbofd/m7ILzLf1vcsHMs",
	"FVevSnm1sr+9SsljbnoDpYciMOpjDS5ulWyao/6FJeLT03cCjNoyoR6bshexZV/rcOs6NxGfUClsqqEp",
	"YgVW3m/omiSE66rVFqk5SmE4H16Bb8Lcf080jq4kKPZ0CoJdWjpTmkUsW7LQRGFdKcSZIhb0sr0u7h/F",
	"rT+KW99dcatznY6rc3WXP6LkZSkNGYeeDgGcda0jdn0BHZlzI67ZBwR6WINcg+mGcSpjjQVaAlDk5nuq",
	"bMlYBlhHim70VPZjOpVKxhVw3fOEpW0q9dE9YNHANKy/ya14s+3H/mbrsLfaZNUoD1r7DC8hE/sqh50l",
	"TdwGQMO7tI8k04XCrVNnHXfKy4s0Rcae5yC5cFb0gLFQ0wyR3kSTPejMfSGQxDwFm2PomoxY8C7KWHCD",
	"YP72cgw0ZgkkaP7r2fUPL09QXLejIGH6UZw8BI8laaWFhpecn+BIT9sH6RrWBHDtSD4QZVHrsyXCuZgP",
	"a6BIKVmomKqZUrfu7D97xdlhx96TMeuZeFzyrAMkmBir1NFRerLSY7tR5ElFQJ48kenIlZIhSHyxCorR",
	"3rRbt+sTwjv/2qRaf9IleNQ6gO5mb/v6O/V819Z50AetGgV3o0h3b5LYZvGcHjmqiBGqnrggpnMa7gWH",
	"gzkpB8QuCXEpXBcZHE10t65iiVbnAZELBeFLT6gQeBHCddT1vHThGaV6rufsMVQKQNiYMLGlMTIjdzSY",
	"btc6egEb4pz3Q80YFXmdxaO+4KTdQWF4Eg5ieuo/T3ooygcNnsqKZDDvDeJ06GZZr2YqRc3BnoQoGBVa",
	"yQjJuHaXqom246fRBzMJn8c3Pn5Rrlbkty6qOeZVZ/vt4r2xXjHLQSC8ktb1W2KhRyfoQqIYU0RonJUJ",
	"oM8l6EiX4xykjtbKeI2wmN3RqWLiVLKpCy7+S0/+Tz05ROM++auO66DIuRMPy1xvsfJJpY6YdGivSyF5",
	"CYf2YWGEt7G3YPukWxEafvAK5aykct6n3Xq0txkQBY4H6Hb7/lW9YuQhPSgJNelhJl7qVojned/ECzA7",
	"N64eUzrERXfm4uEsQ4UKAIWEpO4bQHmpA68NjGyEZC+g0CvMroTSB9zOjTkEfXEdv9cFyke6vPVk8x7G",
	"1vd3g62Nmh77JoKQOC+GlqAU6gweuTTd88KJcts/l0Dj6vXGRnIFI2GTg8h7GaVS7EJJmQ140JwVZYa9",
	"VLgxAxO0AJyMGc22A99P+epYxDWempzRJ9gKnf8yeS6r2zHV+RsBibIhjKeYkt9Bz1Oeccq4+vPPImaF",
	"eSp0I/5fnJgFzzf8Nqpvw+zcUPnhgQIPHZCX18ISsQcqXN7QPB8p03un8yRTheouQobJfS+e6lX96UuK",
	"WIE/l+D4p9HaMg+xyUz9JhN/Ibw8Y92fVqcvg+atw7WFbXgd1mMUildcF+yg6rue/OjumW/UHdNpNe49",
	"yH/dDprH9MIc2yjtKD/NgMtFGWqWbvCue/3WZY7puKqYtTJBOlemYIczMmWf3j23I43MH9sA93J/eAMc",
	"p2AqJYh474EvYcW4RUxoOkHv9IWfOR2+YlnGHowmfiFe6PqGABVDixF6kZsHOaGlBPVgbR6sWcnVn4n5",
	"M8FbLSFeY9PdXfJvH0W+Tu6DvUwF8BioDEbcOqCoxhXrzLZMnoiTNFVWO8ROsyfTtb6BIZ0yjUO/tovC",
	"lUYH0Turxj6apuWghDWQeTXJYIOorsEPq0H2IqkB907xMPbOMaR4u3E3PZTcyM2baern2fy2N7cTfovZ",
	"VDV7FWFPxdP5qX3r+r3YOt/ikjFWFx7XUtqzm0PdnfvoOmASejixC5xS2GRip/L2WQg9CXE1a4KuaLY1",
	"r3rrpwUorWGERGcTjVI52mrUujdgN/zTCL6pgvMiIzS9UI6GzZ32qNIlyAcAWhk7vVTt69m0I7pUUcYS",
	"EEY6TCcbQNaRbWnOjy/HP93f3SU/9qrPds7R48vIP8sASwJBoG4sNA0gGYmBCqi/lhKdFjheA3o1OYlG",
	"UcmzaBa5MuXDw8ME6+EJ4+nUrhXT9xdnbz9cvx2/mpxM1jLXmWhJpLKn0VUBFNl3RC8xxSnoFP7p/AKN",
	"EU7Vb6hfINo4nyYqqamPJ7b7huKCRLPo3ycnk5c2uaZlbIoLMt28nJpEkph+UdvYTZ3512lHCNTXUjBZ",
	"+lWZZVUcUzc5aD/WPIXEZqnqBhxGL5JoFv2sYueOe6qIc8kerTpan3DxHP4KLlEjOmHo4oT6yyru2E1K",
	"xNyfYGKg92sJumkEtT0ii1WnnGq0eu6iM7Uf7b32NnXCTx/Iq5MT65NLMC+YeZ2P03/ajwvU8PYriQ53",
	"tfS2sgW/Khl5dfI68L0chhwhu1H0+uTlk5FmigoBam4pLuVaR4iJQfr6+ZF+YPIdK6lF+NPzI3TfqqGr",
	"jLhOdJxqd8QK9b161nM7646AogzcTQ5FhmO/gta8jufh67gwyxrVywOX0Y++z5/yMt6bySDkG2Y+GfUk",
	"52Fp3DUNgiJm94zX0McaunqvnxBXr8S9wQlyrVzfyV0+cKnqirhrQNI3ionglTKtIl4VXReme67Smc6N",
	"dnvonkequ3gGCfjL5yagVd7WPEmMrfnbt8V9mpkPyC1sQ/F3duv+fw1a554duobWzPX6nuosWyatloKA",
	"WcNJ6CbuNWym2kpT4AUnVPZ2YzyluXsm6zPogjhD9F0ZhaBg6lSY7mXVYmEiuGm0u9/9XwAAAP//2xiv",
	"p01TAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
