// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9fXPbNvLwV8HwbiZJH0qy3Vwm1cwz97i203oaxx6/3M1dlecCkSsJZxJgAVCO2vF3",
	"/w3eSJAEJcpxer+Z3vSPKsQCWCwW+4Zd+LcoYXnBKFApoulvkUhWkGP987goMpJgSRg9o+u/Ya6/FpwV",
	"wCUB/S+oG3CaEgWLs6sGiNwUEE0jITmhy+gxjlIQCSeFgo2m0RldE85oDlSiNeYEzzNA97AZrXFWAiow",
	"4SJGhP4bEgkpSks1DOIllSSHcRS78dlcQUSPj50vsb+SmwISjW2WXS6i6c+/RX/msIim0Z8mNSEmlgqT",
	"AAke4zYNKM5B/b+5rtsVINWC2ALJFSBcD+Vh7agSwPq3iFEYgON5jpfgIXrF2ZqkwKPHj48fdxBDYlmK",
	"Ww3Rxt+0KewxEoQus8YSEKN6VSmsSaK3AWiZR9OfoysOBdaLitUYXJqf1yWl5tcZ54xHcXRH7yl7oFEc",
	"nbC8yEBCGn1sEyaOPo/UyKM15oqaQk3RWYE/Z6fRQ6LTVmPVaXJodhpqvDtN3kKahBY3ZZ5jvhlI8Czz",
	"aS36if0j4EyuNlEcncKS4xTSAIH3JmoT23qOXhBv8l6YAD2bABW6j3F0cnV3DYKVPIELRolkfL9zG+r8",
	"qAdm1EipLv2rJpQwKjGhAqUgMckEWjCOGAWERQGJdCc6KTlXUktILO0xJwIdX50jN73aqqasyLCQtxxT",
	"oWe6JX2SQ8EhJeHMTBVqsuoLKVpwlmu8hGEdyRCmTK6Aq4kXjOdYRtMoxRJGaqyu2ImjHITAywAWP5Y5",
	"pogDTrVEtnCI0FTvHl1W1MFzVkqLcYXeODQZmwvga0h/AAoch7dBrX6cg8Qplni8rCCRXGHZosYDFkiA",
	"RHMsIEVlYaatFk6ofPO6xoNQCUslF+OIAxahyY/RyzknsHiFDITe+cacL8SglZodURNsY9OK5cwJiCot",
	"MLCbFiSPej2/lIRDqg6yHqHCIA6xXEWAev9DmqKN3haR1aBRrJmSLdAtLyFG73AmIEb2fPviS7VHcaQB",
	"9hZYLezsWK2vbujW54asaVCzy4+bQq+l5jpC0QnOITvBoiGMj4uCs7WTgu7nKVCif7zDJDONSQJCkHkG",
	"7X84uXGFudCgNxua6B+Xa+AZLgpClzeQQSIZV3v7N5wR1XxXpNjqOCXr3OeLMpOkyODygYKGP9Ua5BQS",
	"ludECMK09htG7zPKWZYpO+0afilBSG+RJ0rCLZRggBuyVIPuAVNRqBeiIt01FEwoib4J0k2Rq7ehQ1y/",
	"sSL0uwxA9lBbtznaGlJ6hDcffPKbL0M3wbDigiydAedU3jAz8AciA92VGbmt10/lHDgFCeIGEg5yr87n",
	"NCMUnjDrj1IWoW6aBpzRs88FB02ZgJrmjCKoAJCR9lpQq+HTMlO6Sak7MZ5RpU0sBBHo0zfI/vdpikbo",
	"gtBSgpiiT998QjmWyQoEOhj95bsxGqEfWck7TUffqqZTvFES4YJRuWpCHI6+PVQQwabDI6/z3wHu26O/",
	"Gc/oTVkUjCtPR5kNWHGeQvWTwvjCQmK6QcY7egnj5TjWwxCKVgrlajxYA9/ob6/UvJ9Gn6boGtNl3etg",
	"9PaTJtzhETq+UObDW3R8YaDjT1P0nghZAR/Gh0cWWkiEaYoOj+QK5ZqGps/k0xTdSChqtCauj0Gm3ePG",
	"+BXNtbytSaK0yluvy4yefcbKxFaUQwejt/Hhm9HRt3ZLg4rYHLYuG5nviINiJMWcCKNitREkwZlnaDet",
	"N1yQvwEP8+Xx1bltQyksCLXor803SJFh/spOrGa2/tQCYYqM7h2jG2UmcYHEipVZqnTPGrhEHBK2pOTX",
	"ajRt80ltL0oQEikTh1OcGZLGeptyvEEc1LiopN4IGkSM0QXjyqxbsClaSVmI6WSyJHJ8/1aMCVOnNy8p",
	"kZuJsoo5mZeKJScprCGbCLIcYZ6siIRElhwmuCAjjSzV9v04T//ErZQVwe25JzTt0vInQlN1XjEykJZD",
	"KpLpE74CdH12c4vcBIashoLevtbEVIQgdAHcQGrrWY0CNC0Yoda4zIi26ct5TqTaJa2AFJ3H6ARTyiSa",
	"AyqV2Id0jM59W+Brk1JRT4wUycLEdFbzLvvxUtPoAiTWpqpVM9t61LptuHFr+1jLtmWkeifJMoGHfsgW",
	"NaN1PO5uRCocjWl5M8MDM9pUTjc98Z0ynwO31qFyGRWbPaxIskKYg55OsdzAaYTEXAas7A/VLA4GOUeq",
	"8k/Co3sez7A9C8eG2punSewI42FezTJoA5vef8gXEwbAbdRKByK0pNwaHGnygzqOO/lBASkjwUhv5dY6",
	"EaOdPT/w9SyO3/bQUJveO6lqbKk+Qp54cYraWzP0Uoy7IMsu2TjQFDikvfrOKbvmcK6bN2430umvrT3P",
	"1kUKlvWqctvsa3TrlOrPCaMUEuu/VZvdXffy+urkzCqE8KFXELXO8AIErXnC7GGs1vPT8Ni2GZ2f7jdw",
	"i6iNRfiT9lPXd0e6QjX1Wm8xX0KANko7kAWxdk8KQmGD0qabg3KQK5Y2ucZ3ou8oaD9TO8zK8dpcgwDZ",
	"9VHbaw6g2L/acyUYOZGb3ZENy9jE9eiyjBVTw/Rha2Z7+LtH3n4fvISbGonWSqwQbZ7+ajndnfhC8Wmi",
	"gZXorCd6FsG5be1Pk51bxtoR79pCw+oyBAvRDP7Utwd3VDhfb2AEJohwNUWwtZo32Foj09PsYVgR7D1Z",
	"QLJJMthP32Su21fkOHtW66kMCl/Mb60lP43RQoPoG1Qn+NxemECb3bWG9LThsFCTvuXqNLhLF//bLcmB",
	"lbL1dU8mbC2mzUit5saKAu1bl7kb3l/7buiaJrthfVrtgG6ckcsbF7wLmSqmFZmmuVWYUussdHlTaf7e",
	"A5IHL2xuG4NoIOvncHR3/X631WDG7Wfgy5snWZiXN4OX0LIp3TKC51e3nJIliB47LdVt7bFMmAmJFT76",
	"y5spPhiPx6+GkqY5aT+hqsDyXuSqAiW7BGRSlMPEVhMPI7XiKCXi/kv655CzodZOaIQWadVqqkEtdkNJ",
	"23Njow7CpjCErKJDhtgmDNW9Pv875jYR4IQTSRKcPfkiPYSof0/fba0nD7V6CIWam+Ks2eZfc3khnB6x",
	"1BJKeEsYtPZeu4PpqHHLSVdjEAn5XgEIG22yJMec4436t/Es++c17aiwNwvD5w5eZHSmZwNtBqsCTGTH",
	"HOxAjEON2mDT3GQs2FWUfE/6tRIfQgsQGyEhT3scUNOIBHC1CB1ftih1+UCH6a+wlMBpMICT2S3RgKiw",
	"kI3FdGI+5krA4VFSIrUWi9EDkSuly9T/lcEnysWCfI7VJ4zECrJsJOQmA7TM2NxNpvHXs+MlJlRIl7WR",
	"bVDGcApmCo1Tjj+/B7qUq2h69Jc3cWSHiKbR//8Zj349Hv3zYPTddDYb/Ws8m81m33z85s8hxdSkdygd",
	"zUSPr1hGkoFy9M7rYdjqsVdE9mkdv9WPkoRNaeGlf1k5gGzfHGtnjmQm8pjIEmd1EsyXig1rNfght9qK",
	"H3QG+kLFgbOAu3G4vUdvxTGNhDKpAmJLlpG3B5qOJqTrYpqKjsEcI5+8Q6WazXjaKkt3L7kRZFQGmHMW",
	"n+SzqxEyLOQNAB2SAmXZwmT8AEXzjWFTI6eG5ztVvuGTPL89FUDVp6EC9jWbtNDehzk7DGmk6bl1rAcM",
	"UMNX4irdR1KlPdc+3sloYNU8iVH4YPpk9NmvYmO9NzW+NdU8VvM5oN/MfPrVhMerK8zTB8xB38Ka23xC",
	"l1a1oca96PNfWVgcXGbg88XenuG6Yq9k2HBg7VKnnoTzXq9hzphNyrliD8AhvVwsnmjHN3D1Zu20eYgE",
	"WptWeqPJRzfQ3FhBoD1g4zdOe9AIqCDsLTto1UtSMSlLkmqrr6TklxKyDSIpUEkWm60+qX91HRbnxx6E",
	"Un0myWXeHrbDm4o4oeuS7xmT6Px0n6GqM2jWH8bzsjqoN+6gDpygfcXtk6RaRxeL/nPSsfp23LkUGlLH",
	"j3JM8dIk6Wo5YGSiLqRIsjJVLQ8roO67SzSZA0rZA7WWsZJbWhBD2t1xB3djkq526lOzmAq60itP7f+4",
	"g2zpk4JVBqfnvwZpDP+c4rix2KeJ4+4QfeJY2lzYIMGqQHZxy06xVDx/WcrLhf3tZUo+RQ43kPSmCLT6",
	"swY7t1I2m62+OCXi/vnLEOKeQ2ydHX16Dbw+v0Tco1LYKGiTKQusfNVw7JPrrNWN8oNXnhOvh2+OuV2K",
	"6Tm6vKPJU/o5/AtcZsr6PlAmWBejHH8meZmj1HZCOMvYg5/BYi7nJUOJraIZI70U16EWUcJKvRRhnbbH",
	"1Fla2ws5UGu0Y883yo1SLoRy8seoTq6sPgqEOUzRJ2HyFAUoE1XE6FNuPpjUQ/VhZT7oJEu9F3V44OVf",
	"pz8fjr77OJul37z662yW/izy1cdgdKCTRd3dwA5IM0vRpqRpZLBOr8aZIpu5N9/qf/83e/G/2Yt/wOzF",
	"zoHaL5Gx2/0JOY0W05AW7imswNkA0eBA65q1sBFSCQovhGQlhq68tZwSDNqZAo4OLuemEgyEsiTlCri9",
	"xTLSaYUFmgNQ5Abw9nzOWAaY2gCcbj3uucTTchpLm1TpT/CgZL839rDwj+vx/WZQxa6C5UFuzfAcsi+p",
	"ez52XpcZSRfvFUW2cTKx42Z4Bc5NrrMbNIi1wm5EEMyIMA/Q8E4H9oVw1846SBm4rxQ8TOyrs4sR0IQp",
	"X+Pqp5ObPx0eoKSuAULCFAH5zBkgajPmPTwj+WvsoStRtGFJ9EBsKa/dViKqQKbyvpSM9g4hEaHT0rPv",
	"iqrDtrzHD+oB3O9qoDNInwQx0mwvMVuJwcc48thiNy8pvoHUZ6Ug62wN03dreyG82C8NwvdHSIO7q+NI",
	"nfzM3ipeDe+Kd3db+1U16GMcvSNZdV3cOtCMSuhLjy0yTCiS8Fmil3e370ZvXyHGdYXum9fVDtkRHGEX",
	"JOvdIgV3prqpT10PnD24LFlp7GOu9JqeZYwuSqENHiBaP80ijdwsUhjNIoPTLBqjU+O9aCFcAfk+rf4U",
	"xbZLIBk1jpaclUWYJGp5LwTSELHnvVi0tBPjMnVomQMnCTo/baPFGZMGq67pxFLYOnUB3KYpIQU7Rv9g",
	"pbYoDTImsJUr+2+Bc5IRzBFLJM7MpStGGWAdM/oVOHOFWgdvXr/We4uNnkhIbjsoQRHu8/ro4JUyaWVJ",
	"0okAuVT/kyS536C59cVQlXM4RucLpEzWimKxCXM1F6MdIbVOJVtrgin0wqUQ/W4znguWlRIqr9kxZ6vI",
	"AH1gEoy0x3SD4DMR2qrXoFrmzwEp0+GBEykhHOUpBfCtm8YeKPCvwC8hD786akGpE64t7ciFJZHXSgaG",
	"1sRhARyocnQYwugHIpspDlplQijJgJVUXlVb5sIMk06UQcG4YhuzTy+E2RF749IyI10lsToeqmsdX9BT",
	"NnRwvWv9zOPzjM1BsdjUVcs9lT+uebdNWg9VeY7BMY1Fdg1rInpfWeC2VUf7BdQu5VZ8O/UbFfKdWeO+",
	"6FE88M2cVirPbmxsZZJlxNDEPaXHHV5WHvBAZqbox9vbq4HsrBjyKshDO/lXMo9/nQblIEtO69sJjYqA",
	"NXCPobeJoX24j3e5zzEPNgEjsaEJ2sKXJmkntHheWQN31++NbE1YDgLhhbS+pdK+OpUVnUuUYGovMwD9",
	"UoIOdXKcg9SRpzJZISymaBZNFA9OJJu4QMlfNfT/1dBD5GODw6vt+/2Z2nFkaObeN6A6fN2TeXvtc7Tj",
	"L13QaNNmA4WGqMDJ/SCzsj+zuPcJgS7i5u51S5aZsQEkQwkHbbW3CwMHmeqV2RtIl/m6G2xXGCLT1mca",
	"pk97kGw3mnEk9GxDlXqNJTIdd2rzp+tvM8FApT2MIDXOwQFEgZMto+jmnUOFd74ePvYo9HFXCMD2rjcp",
	"xDoXOrP667ym5YViO3Sp2xARyMVBrdGcZcqKF0RISL3E97zUkcM1xHanrYAXuodZk1DqhltYc9IDMQdK",
	"mawzDZ8Y3qmBzStTnZSzDrE1PrbGRkicF1uimibpT8f7H7CwS9kjlJlCBk+Zy7onuvs+8y23PNp1jAT8",
	"UmpJYGviG7cd2DkxCfIe9Koukk2lqIkeoitWlBn28i3M6R+ja8DpiNFsM/CNry+O7l3gQuFoL3HuYSP0",
	"jZS5ebIWCqb6QkVAqkQg40tMya8m4yvBEpaMq3++FAkrzFeh3xN65Zg5yEXDxJW9bQsmuijPMbRL3m0T",
	"lsrBFO46z3yPlQCe6cuLiZprFtnXc/qeLNC9+m8VKWIF/qUER0Q9rU0oclkrxlJ+Ibzrv7oMqL5VHPRm",
	"ZnRty8n/Ey9+HtOGdaSAfteXPtsWXZASraqzql7f8uZi5Ay/tDqz/hVv+J2JLv23VZt0Yb4IKXT6pHxz",
	"nWIcKFVR5ziFImObPYouwky3R/HKbWWQOQfS3QfpI3m+pETWr131xUrd+wiDkrk1sBZ6zcr/3Z0bbwU8",
	"sSRmv9clKo5waa0FJFtF0n9rbf5319r856pm9n18xO3ycQZcXttExfbrGB5du2RelTmmoypLsHWjqp1q",
	"NXb4erPsM7lc9pWyrqWz89gauOck4TVw5byX5ulW792gOSwYtxMTuhyjd1qwTLcnU70QL5pZUi/yF80s",
	"qRerF71ZUrNZ+n/6E6MK4AlQ2VvaXLcrqpkVmftWTpZL5RGEKGmsUePKrmFItUpjv29sp3BipRvR26bG",
	"OpoqeSdzNSbrpmDa1g7PuDuqYAmrzgIflmfZi0s9cC+IN2MvjEHFW7STm2qpRC01JxTbD7l5fVP9PLm6",
	"671WDT8TbTI3e2VDT1anc5X7+vU70o+VsN580JZhZMW4K5keZt71rGbXY5rb8NohJXso8RjYpa355+HU",
	"Vdy4omjZZk6ablPUGghxBTVGlzTbmEe49dcCOHIHUCdOGCm1t/KuxXpAffvb2Ftm3jApmiq8G0/DeZER",
	"ujxXrk4ww6sS63OQDwC0MlJ0V0WI30FSV8msfeK6nTbg0Sn29zaw4pAYvCU5/JO56K674nvPjERpkV3p",
	"uV8VI1R+JBd27Vownh9/OHZvvh5fnx1P3l+eHN+eX36I0cMKOOiPzZRa5V4QqhMSOGIJYGqST13P6g5W",
	"pxtjLklSZpgjQSRoG4nY58kxBxybB0/NQ6XoWF/P4skHePjXPxi/j9FZqU7C5Apz4ti6pDifk2XJSoG+",
	"HSUrzHGiLz3cWls34+jlLPrh4nYWxWgW3d2ezKJXQXa761RYtKuB6lRf+3iuifTjUrIcS5KECkekEtRL",
	"W9Vm4ioaU1aGsn/kztyY5oO/Ji2Tyx84TsBPMd8qyRycOsQeM23rUzFdJ6MudAn+qCteTRGI9kYTvTDI",
	"McmiaSQB5/9vkZHlSiYyGxMWuTCOlhPvdAs6YVRylqFbwHkURyVXXV2ubaN3Jxj1c3OIjy9D3V65ci6T",
	"faZz/SHJsCLOGkxREOQ28WaRAUidxgXp0oXcTYhLroBw9MD4vbLbxXhm6iYToALq+Ed0XOBkBehofNBZ",
	"zMPDwxjr5jHjy4ntKybvz0/OPtycjY7GB+OVzDOzYVIxZ9Qi0vHVeRRHa+chRutDnBUrfGgruSguSDSN",
	"vh0fjA/tTbNmuAkuyGR9OLHrmfymkH2cOFNf5ymEnq/7AWTD1YzbkQfP9WyqPBeBaKg7W+XF6HlqBg9E",
	"RhTW7spSWwfbA36tWZSuWbaQ7kVS60U1qM32sDtYveTpuF/yEmL7R4ACIdJu8UpVqa3LZlDLo6qm1Xeu",
	"9bwa+LrlfW2b96N27QummEi1Hx0ctDLRvBjO5N/2jzvU4w0J3/iP3D52DuDlT4rxjg5eBx5oZe46XoG8",
	"Pjh8NtRMul8AmzuKS7nS0eXUTPr660/6gcl3rKR2wu++/oTur+rQRUbc33bCS2Gee9Tven9U33qOfJ3d",
	"X5SBA39na/FaGa07z/I1FJlSTX4y8Zef5LqO7jmO6UcDDEJ+z8zjxc+yUfYx9cemxlTIPH7F8+nPGjqT",
	"r59xrl5W/B6nyFVs/UEO+Y7TVieuuzIjfdRYqKTtxGRkYIpCxW19J8306lbMfR3m7s4ziM8PvzYCIUqm",
	"Rhe9/X3nPs7Mi+bXtiL+D3b4/rMKr3Pcdp1Gqwa3Grx7HshrwGnoOO6l/PontBbtsyrBr6STBp0Xp57+",
	"UKoiyKc6/q7rWDWDGF9xEum/T2n6ddKHHOPpB/5bBpOOV1m2sKqp65k0R+jnOn+wLvKPHx//JwAA//97",
	"UxaTI3UAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
