# Disable debug information package creation
%define debug_package %{nil}

# Define the Go Import Path
%global goipath github.com/flightctl/flightctl

# SELinux specifics
%global selinuxtype targeted
%define selinux_policyver 3.14.3-67
%define agent_relabel_files() \
    semanage fcontext -a -t flightctl_agent_exec_t "/usr/bin/flightctl-agent" ; \
    restorecon -v /usr/bin/flightctl-agent

Name:           flightctl
Version:        0.2.1~778~g6ec1839
Release:        1.20250211115242037271.propagate.rendered.778.g6ec1839%{?dist}
Summary:        Flightctl is a manager of the edge device fleets.

%gometa

License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT
URL:            %{gourl}

Source0:        flightctl-0.2.1~778~g6ec1839.tar.gz

BuildRequires:  golang
BuildRequires:  make
BuildRequires:  git
BuildRequires:  openssl-devel

Requires: openssl

# Skip description for the main package since it won't be created
%description
# Main package is empty and not created.

# cli sub-package
%package cli
Summary: Flightctl CLI
%description cli
Flightctl is a command line interface for managing edge device fleets.

# agent sub-package
%package agent
Summary: Flightctl Agent

Requires: flightctl-selinux = %{version}
Requires: bootc

%description agent
Flightctl Agent is a component of the flightctl tool.


%package selinux
Summary: SELinux policies for Flightctl Agent
BuildRequires: selinux-policy >= %{selinux_policyver}
BuildRequires: selinux-policy-devel >= %{selinux_policyver}
BuildArch: noarch
Requires: flightctl-agent = %{version}
Requires: selinux-policy >= %{selinux_policyver}

%description selinux
The flightctl-selinux package provides the SELinux policy modules required by the Flightctl Agent.


%prep
%goprep -A
%setup -q %{forgesetupargs} -n flightctl-0.2.1~778~g6ec1839

%build
    # if this is a buggy version of go we need to set GOPROXY as workaround
    # see https://github.com/golang/go/issues/61928
    GOENVFILE=$(go env GOROOT)/go.env
    if [[ ! -f "${GOENVFILE}" ]]; then
        export GOPROXY='https://proxy.golang.org,direct'
    fi

    SOURCE_GIT_TAG=%{version} \
    SOURCE_GIT_TREE_STATE=clean \
    SOURCE_GIT_COMMIT=$(echo %{version} | awk -F'~g' '{print $2}') \
    SOURCE_GIT_TAG_NO_V=%{version} \
    make build-cli build-agent

    # SELinux modules build
    make --directory packaging/selinux

%install
    mkdir -p %{buildroot}/usr/bin
    cp bin/flightctl %{buildroot}/usr/bin
    mkdir -p %{buildroot}/usr/lib/systemd/system
    mkdir -p %{buildroot}/%{_sharedstatedir}/flightctl
    mkdir -p %{buildroot}/usr/lib/flightctl/hooks.d/{afterupdating,beforeupdating,afterrebooting,beforerebooting}
    mkdir -p %{buildroot}/usr/lib/greenboot/check/required.d
    install -m 0755 packaging/greenboot/flightctl-agent-running-check.sh %{buildroot}/usr/lib/greenboot/check/required.d/20_check_flightctl_agent.sh
    cp bin/flightctl-agent %{buildroot}/usr/bin
    cp packaging/must-gather/flightctl-must-gather %{buildroot}/usr/bin
    cp packaging/hooks.d/afterupdating/00-default.yaml %{buildroot}/usr/lib/flightctl/hooks.d/afterupdating
    cp packaging/systemd/flightctl-agent.service %{buildroot}/usr/lib/systemd/system
    bin/flightctl completion bash > flightctl-completion.bash
    install -Dpm 0644 flightctl-completion.bash -t %{buildroot}/%{_datadir}/bash-completion/completions
    bin/flightctl completion fish > flightctl-completion.fish
    install -Dpm 0644 flightctl-completion.fish -t %{buildroot}/%{_datadir}/fish/vendor_completions.d/
    bin/flightctl completion zsh > _flightctl-completion
    install -Dpm 0644 _flightctl-completion -t %{buildroot}/%{_datadir}/zsh/site-functions/
    install -d %{buildroot}%{_datadir}/selinux/packages/%{selinuxtype}
    install -m644 packaging/selinux/*.bz2 %{buildroot}%{_datadir}/selinux/packages/%{selinuxtype}

    rm -f licenses.list

    find . -type f -name LICENSE -or -name License | while read LICENSE_FILE; do
        echo "%{_datadir}/licenses/%{NAME}/${LICENSE_FILE}" >> licenses.list
    done
    mkdir -vp "%{buildroot}%{_datadir}/licenses/%{NAME}"
    cp LICENSE "%{buildroot}%{_datadir}/licenses/%{NAME}"

    mkdir -vp "%{buildroot}%{_docdir}/%{NAME}"

    for DOC in docs examples .markdownlint-cli2.yaml README.md; do
        cp -vr "${DOC}" "%{buildroot}%{_docdir}/%{NAME}/${DOC}"
    done

%check
    %{buildroot}%{_bindir}/flightctl-agent version


%pre selinux
%selinux_relabel_pre -s %{selinuxtype}

%post selinux

%selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/%{selinuxtype}/flightctl_agent.pp.bz2
%agent_relabel_files

%postun selinux

if [ $1 -eq 0 ]; then
    %selinux_modules_uninstall -s %{selinuxtype} flightctl_agent
fi

%posttrans selinux

%selinux_relabel_post -s %{selinuxtype}

# File listings
# No %files section for the main package, so it won't be built

%files cli -f licenses.list
    %{_bindir}/flightctl
    %license LICENSE
    %{_datadir}/bash-completion/completions/flightctl-completion.bash
    %{_datadir}/fish/vendor_completions.d/flightctl-completion.fish
    %{_datadir}/zsh/site-functions/_flightctl-completion

%files agent -f licenses.list
    %license LICENSE
    %{_bindir}/flightctl-agent
    %{_bindir}/flightctl-must-gather
    /usr/lib/flightctl/hooks.d/afterupdating/00-default.yaml
    /usr/lib/systemd/system/flightctl-agent.service
    %{_sharedstatedir}/flightctl
    /usr/lib/greenboot/check/required.d/20_check_flightctl_agent.sh
    %{_docdir}/%{NAME}/*
    %{_docdir}/%{NAME}/.markdownlint-cli2.yaml

%files selinux
%{_datadir}/selinux/packages/%{selinuxtype}/flightctl_agent.pp.bz2

%changelog

* Tue Feb 11 2025 Lily Sturmann <lkatalin@users.noreply.github.com> - 0.2.1~778~g6ec1839-1.20250211115242037271.propagate.rendered.778.g6ec1839
- NO-ISSUE: Do not create NetworkPolicies when deploying on ACM (#890) (Rastislav Wagner)
- NO-ISSUE: Clean unused API that is now handled via ws (Miguel Angel Ajo)
- NO-ISSUE: Update the Agent API to support multiple consoles (Miguel Angel Ajo)
- EDM-1141: In some cases the rollout fails but it is not reported with an error message and does not timeout (Ori Amizur)
- NO-ISSUE: Pull CI RPM Builder image before using it (Miguel Angel Ajo)
- EDM-973: device/hooks: skip run action execution if binary not found (#889) (Sam Batschelet)
- EDM-1104: agent: improve rollback error handling and testing (Sam Batschelet)
- NO-ISSUE: *: ensure response bodies are closed (Sam Batschelet)
- EDM-611: device/applications: dont mark degraded on reboot if there are no apps (Sam Batschelet)
- EDM-683: Normalize Device Labels into a Separate Table for Optimized Queries and Fast Distinct Label Retrieval (#845) (Assaf Albo)
- EDM-1101: pty console support and selinux (Miguel Angel Ajo)
- EDM-1094: API accepts decimal numbers for rollout policy percentages (Ori Amizur)
- stam (Ori Amizur)
- NO-ISSUE: Additional fields for kv ss and secrets job (#874) (Rastislav Wagner)
- EDM-390: Update device lifecycle status immediately upon user request (Lily Sturmann)
- EDM-1087: Handle configuration changes (Ori Amizur)
- EDM-925: T17: Do not only rely on client-side authorization (#834) (Gregory Shilin)
- EDM-1014: Report versions of all software components phase 2 (#862) (Gregory Shilin)
- EDM-1104: agent/rollback: set version failed before rollback (Sam Batschelet)
- NO-ISSUE: test/agent: improve container workflow (Sam Batschelet)
- EDM-1086: agent: improve logging during image pull (Sam Batschelet)
- EDM-1000: agent/hooks: add success criteria when hooks fire to the logs (Sam Batschelet)
- EDM-715: Wrap variables in script files in quotes (Dakota Crowder)
- EDM-715: Remove WantedBy=default.target (Dakota Crowder)
- EDM-715: Remove setting HOME in kv container (Dakota Crowder)
- EDM-715: tag images with 0.4.0 (Dakota Crowder)
- EDM-715: Configure standalone deployments for rootless podman (Dakota Crowder)
- EDM-715: Add default.target to .container files so services start on system boot (Dakota Crowder)
- EDM-715: Ensure directories are created before copying files (Dakota Crowder)
- EDM-715: Configure podman for rootless setup (Dakota Crowder)
- EDM-715: Explicitly define volumes for api, db, kv (Dakota Crowder)
- EDM-500: EDM-999: agent: ensure rollback on failure (Sam Batschelet)
- EDM-1096: Print num devices in list fleets only when available (Avishay Traeger)
- NO-ISSUE: Use PostgreSQL 16 instead of 12 (#870) (Gregory Shilin)
- NO-ISSUE: Add podManagementPolicy field to kv statefulset (rawagner)
- NO-ISSUE: Generate secrets via job (#863) (Rastislav Wagner)
- EDM-1072: Replace vagrant with libvirt solution to run e2e in host not suitable for bootc (sserafin)
- EDM-1082: Bug fix to ensure enrolled device lifecycle status is not reset (Lily Sturmann)
- EDM-1025: Move callback manager to separate package (Avishay Traeger)
- EDM-1071: Add condition displaying the rollout status (Ori Amizur)
- EDM-1014: Report versions of all software components p1 - cli+service (#854) (Gregory Shilin)
- EDM-960:  Inline config E2E tests (amalykhi)
- EDM-1074: The doc to install flightctl-cli got a typo in information … (#847) (Gregory Shilin)
- EDM-1065: Return device status summary in fleet list (Avishay Traeger)
- NO-ISSUE: do not create our own versions of lo.ToPtr (Gregory Shilin)
- NO-ISSUE: cmd/flightctl-agent: fix config dir validation (#844) (Antonio Murdaca)
- EDM-811: Enable status.lifecycle.status field selector for devices (Lily Sturmann)
- EDM-1068: Allow insecure comm with Keycloak for external connections too (#838) (Rastislav Wagner)
- EDM-1070: It's not possible to update a fleet setting only disruption budget without device selection (Ori Amizur)
- EDM-1075: api/properties: fix bugs in IsManagedBy (Sam Batschelet)
- NO-ISSUE: test/sctipts: fix trap typo (Sam Batschelet)
- NO-ISSUE: properly handle wrapped errors (#836) (Gregory Shilin)
- EDM-885: git is missed on some platforms (#841) (Gregory Shilin)
- NO-ISSUE: Respect global.generateSecrets flag for Keycloak chart too (#835) (Rastislav Wagner)
- EDM-1069: Fix updating device after fleet update (Avishay Traeger)
- EDM-1062: Handle rollout of a new device or a device that just joined a fleet (Ori Amizur)
- NO-ISSUE: Small API fixes (Frank A. Zdarsky)
- NO-ISSUE: makefile: add make-agent-container (Sam Batschelet)
- EDM-1064: Add architecture documentation for rollout policies (Ori Amizur)
- EDM-945: Return the most relevant openapi error (Avishay Traeger)
- EDM-1054: Remove ownership change check in store (Avishay Traeger)
- NO-ISSUE:  Increment resource_version when marking/unmarking devices for rollout (Ori Amizur)
- NO-ISSUE: add typing to helper (Cameron Wall)
- EDM-1055: agent: add support for rpm-ostree hosts (Sam Batschelet)
- NO-ISSUE: Update flight control API config (Cameron Wall)
- EDM-520: Implement rollout policy batch selection (Ori Amizur)
- NO-ISSUE: Split listQuery 'Build' function to 'BuildNoOrder' and 'Build'. (Ori Amizur)
- NO-ISSUE: Fix strategy for rollout device selection (Ori Amizur)
- EDM-1052: Return full resources upon update (Avishay Traeger)
- EDM-1022: device: ensure continuity between the resource and summary status (Sam Batschelet)
- EDM-1043: Adding flightctl application lifecycle E2E test TC76800 (sserafin)
- EDM-885: RPM build (Gregory Shilin)
- EDM-1024: Use generic implementations for common store methods (Avishay Traeger)
- EDM-707: device/applications/compose: enforce service container_name is not supported (Sam Batschelet)
- NO-ISSUE: agent/config: ensure required directories (Sam Batschelet)
- NO-ISSUE: make packit replace -rc to ~rc in tags (#810) (Miguel Angel Ajo Pelayo)
- EDM-390: Remove decommissioning device from fleet (Lily Sturmann)
- EDM-1012: Fix device updated status for managed devices (Avishay Traeger)
- EDM-993: CLI headless login (#793) (Rastislav Wagner)
- NO-ISSUE: Handle release tags with ~rc0 / ~rc1 etc... (Miguel Angel Ajo Pelayo)
- Helm updates: Fix Redis deployment and remove DB limits (#802) (Avishay Traeger)
- EDM-391: Update device side decommission handling (Lily Sturmann)
- NO-ISSUE: Add missing API description (Frank A. Zdarsky)
- EDM-885: added go-rpm-macros to docs (#800) (Gregory Shilin)
- EDM-1046: applications/compose: ensure manually stopped containers are tracked as degraded status (Sam Batschelet)
- Add keyset-based matching to label selectors and fix orphaned device selection bug (#803) (Assaf Albo)
- EDM-1012: Set OutOfDate info if rollout failed (Avishay Traeger)
- EDM-882: Approving ER adds user identity (#788) (Rastislav Wagner)
- EDM-820: Generate passwords & inject them via secrets (#796) (Rastislav Wagner)
- NO-ISSUE: tests/e2e/agent bump upgrade timeout to 2m (Sam Batschelet)
- EDM-722: applications: improve beforeUpdate validations (Sam Batschelet)
- EDM-213: e2e agent automation (#784) (Samuel De La Cruz Lopez)
- EDM-556: add device engine (Sam Batschelet)
- EDM-885: make build-cli-multiarch target (#789) (Gregory Shilin)
- EDM-1038: Create container with all CLI artifacts for publishing (Miguel Angel Ajo)
- EDM-714: Remove rabbit refs in deploy scripts (Dakota Crowder)
- EDM-714: Fix file removal (Dakota Crowder)
- Revert "EDM-714: Rename rabbitmq to mq to be more inline with db and kv, fix file removal" (Dakota Crowder)
- EDM-714: Rename rabbitmq to mq to be more inline with db and kv, fix file removal (Dakota Crowder)
- EDM-714: Specify periodic and worker as systemd deps of the api container (Dakota Crowder)
- EDM-714: Better handling around setting PRIMARY_IP from our friend coderabbit (Dakota Crowder)
- EDM-714: Remove -it from not interactive exec cmds (Dakota Crowder)
- EDM-714: Fix standalone mq commands (Dakota Crowder)
- EDM-714: Add shared file for deploying individual services, share some config, cleanup the existing scripts (Dakota Crowder)
- EDM-714: Move deploy quadlets logic to a script file (Dakota Crowder)
- EDM-714: Move clean quadlets logic to a script file w/ some better logging (Dakota Crowder)
- EDM-714: Use more specific matching when copying files to /etc/containers/systemd/ (Dakota Crowder)
- EDM-714: Use more specific matching for stopping standalone services (Dakota Crowder)
- EDM-714: Use absolute paths for volume mount refs (Dakota Crowder)
- EDM-714: Add back creation of admin db to dpeloy-db make command (Dakota Crowder)
- EDM-714: Remove podman-compose code, move quadlets code into the deploy/podman directory (Dakota Crowder)
- EDM-714: Change deploy and kill kv commands to use quadlets (Dakota Crowder)
- EDM-714: Change deploy and kill mq commands to use quadlets (Dakota Crowder)
- EDM-714: Remove standalone network (Dakota Crowder)
- EDM-714: Use separate standalone config to spin up db rather than templating (Dakota Crowder)
- EDM-714: Spin up standalone postgres db (Dakota Crowder)
- EDM-714: Remove redis volume when we clean quadlets deployment (Dakota Crowder)
- EDM-714: Create separate file for the redis.conf volume instead of using ExecStartPre (Dakota Crowder)
- EDM-714: Wait for postgres db and add superuser permission when starting up quadlets (Dakota Crowder)
- EDM-846: Deploy default fctl roles in ACM env (#708) (Rastislav Wagner)
- EDM-1018: Add helm values for ACM deployment (#791) (Avishay Traeger)
- EDM-1036: Dispatch tasks via Redis (Avishay Traeger)
- EDM-773: Update charts to support deployment via ACM operator (#780) (Miguel Angel Ajo Pelayo)
- EDM-885: move CLI build to a separate PR (Gregory Shilin)
- EDM-885: RPM versioning (Gregory Shilin)
- EDM-967: Add identity information for K8S (#785) (Ori Amizur)
- EDM-768: Run linter on OpenAPI specs (Frank A. Zdarsky)
- EDM-768: Only set pdeathsig on Linux (Frank A. Zdarsky)
- EDM-768: Simplify enrollment config (Frank A. Zdarsky)
- EDM-768: Align CSR API with K8s (Frank A. Zdarsky)
- EDM-1021: applications: add controller sync test (Sam Batschelet)
- EDM-1021: applications: ensure id is deterministic (Sam Batschelet)
- EDM-1015: Add note in docs about go template syntax (Avishay Traeger)
- EDM-989: Flightctl should fail with explicit message if login was not done (rawagner)
- EDM-992: Validate URL for login cmd (#777) (Rastislav Wagner)
- EDM-983: Testing for Filtering (Eldar101)
- EDM-710: Validate Repository Spec Selectors Using GenericRepoSpec (#769) (Assaf Albo)
- EDM-1017: Replace variables in git config mountPath (Avishay Traeger)
- EDM-390: Update device lifecycle status based on Condition (Lily Sturmann)
- EDM-391: add lifecycle manager (Sam Batschelet)
- NO-ISSUE: Add shortcut 'k' for 'insecure-skip-tls-verify' flag (#778) (Rastislav Wagner)
- EDM-869: TC75506 Resources lifecycle (#687) (amalykhi)
- NO-ISSUE: Small fix in template variables doc (sserafin)
- EDM-821: Support pure k8s authN (rawagner)
- Revert "EDM-773: Update charts to support deployment via ACM operator" (#772) (Rastislav Wagner)
- EDM-969: applications: ensure unique ID (Sam Batschelet)
- EDM-969: applications: add internal support for tracking by ID (Sam Batschelet)
- EDM-390: Add decommission spec to rendered device config (Lily Sturmann)
- EDM-943: Add document describing k8s RBAC authorization (Ori Amizur)
- EDM-390: Set decommission request in device spec (Lily Sturmann)
- EDM-390: Add decommission request to device spec (Lily Sturmann)
- EDM-1008: Add permissions check for device console (#763) (Rastislav Wagner)
- EDM-1005: Fix selector behavior for NULL columns in the database (#762) (Assaf Albo)
- EDM-1011: CLI to request device count when listing fleets (Avishay Traeger)
- EDM-1010: Fix template variable for inline config path (Avishay Traeger)
- EDM-526: policy: ensure DST is properly covered (Sam Batschelet)
- EDM-970: Fix K8S_RBAC_NS value for ACM deployment (#759) (Rastislav Wagner)
- EDM-773: Update charts to support deployment via ACM operator (#760) (Rastislav Wagner)
- EDM-526: policy: improve logging (Sam Batschelet)
- EDM-526: device: ensure policy has an escape hatch (Sam Batschelet)
- EDM-526: policy: add schedule tests and improve logic (Sam Batschelet)
- EDM-526: api: install tzdata for time zone validation (Sam Batschelet)
- EDM-526: spec/queue: refactor (Sam Batschelet)
- EDM-526: device: update status to align with policy checks and docs (Sam Batschelet)
- EDM-526: spec/queue: improve docs (Sam Batschelet)
- EDM-526: plumb update policy (Sam Batschelet)
- EDM-526: agent: add update policy (Sam Batschelet)
- Integrate Labels and Annotations Filtering into Selector Framework (#751) (Assaf Albo)
- EDM-768: Align createOrUpdate (Frank A. Zdarsky)
- EDM-768: Fix properties next to ref linting issue (Frank A. Zdarsky)
- EDM-768: Fix PascalCase linting issue (Frank A. Zdarsky)
- EDM-768: Fix linting issues (Frank A. Zdarsky)
- EDM-822: Container port (Eldar101)
- EDM-781: Field selectors tests (Eldar Weiss)
- EDM-390: Set enrolled devices to 'Enrolled' lifecycle status (Lily Sturmann)
- EDM-954: Use approved RabbitMQ (Avishay Traeger)
- EDM-819: Remove any unnecessary helm for the gRPC endpoint (Miguel Angel Ajo)
- EDM-818: gRPC and agent HTTPS under the same endpoint (Miguel Angel Ajo)
- EDM-955: Use approved Redis (Avishay Traeger)
- NO-ISSUE: Collect logs in smoke/e2e github workflows (Avishay Traeger)
- EDM-922: Fine-tune HTTP server settings (Avishay Traeger)
- EDM-953: Use approved Postgres (Avishay Traeger)
- NO-ISSUE: omit grpc from make generate (Sam Batschelet)
- EDM-649: Update CSR error codes to be more expressive and accurate (Lily Sturmann)
- NO-ISSUE: reduce scope of bootc API (Sam Batschelet)
- Revert "NO-ISSUE: helm: unblock CI pin rabbitmq" (Sam Batschelet)
- EDM-390: Add decommission CLI command (Lily Sturmann)
- EDM-390: Small fix for decommission target type (Lily Sturmann)
- NO-ISSUE: troubleshooting: add basic agent debug (Sam Batschelet)
- EDM-948: Allow specifying Namespace for k8s RBAC checks (#736) (Rastislav Wagner)
- EDM-870: flightctl console cli on web socket (#731) (Miguel Angel Ajo Pelayo)
- MGMT-18492: Add logical support for reboot hooks (Sam Batschelet)
- EDM-390: Add lifecyclestatus to devicestatus (Lily Sturmann)
- NO-ISSUE: libvirt-dev should always be installed (Miguel Angel Ajo)
- NO-ISSUE: Implement Go tools pattern (Frank A. Zdarsky)
- NO-ISSUE: Update GH runner (Frank A. Zdarsky)
- EDM-390: Add decommissioning field to rendered device spec (Lily Sturmann)
- NO-ISSUE: packaging: add flightctl agent version to must-gather (Sam Batschelet)
- NO-ISSUE: metrics: register flightctl_api_errors_client_total (Sam Batschelet)
- EDM-391: Add 'decommissioning' Condition and Reasons for device (Lily Sturmann)
- NO-ISSUE: Use a password for accessing Valkey (Avishay Traeger)
- NO-ISSUE: Move key-value code out of tasks package (Avishay Traeger)
- EDM-854: Use go-templates for fleet template parameters (Avishay Traeger)
- NO-ISSUE: helm: unblock CI pin rabbitmq (Sam Batschelet)
- EDM-879: improve service generated app status (Sam Batschelet)
- EDM-886: correctly fmt service side app status (Sam Batschelet)
- EDM-526: ensure errors reported by os.exec are properly handeled (Sam Batschelet)
- EDM-870: ws console wiring (Miguel Angel Ajo)
- EDM-870: Move console request/connection to websocket (Miguel Angel Ajo)
- EDN-860: Add permission checks for all API endpoints (Ori Amizur)
- NO-ISSUE: Fix OpenAPI descriptions (Frank A. Zdarsky)
- EDM-848: revert tzdata host mount (#690) (Sam Batschelet)
- EDM-876: Fix helm template error (Celia Amador)
- EDM-788: Add init script for PostgreSQL to set master user as superuser (#679) (Assaf Albo)
- EDM-838: Update ACM registration doc (Frank A. Zdarsky)
- NO-ISSUE: redeploy kind pods for development (Miguel Angel Ajo)
- NO-ISSUE: move ownership od status exporters to managers (Sam Batschelet)
- EDM-853: spec/queue: ensure item requeue backoff only if tried  (#696) (Sam Batschelet)
- EDM-642: Remove sorting mechanism for TP phase (#701) (Assaf Albo)
- MGMT-17672: Document device statuses (Frank A. Zdarsky)
- EDM-417: Get renderedVersion from DB (Frank A. Zdarsky)
- EDM-417: Update unit-tests for server-side status (Frank A. Zdarsky)
- EDM-417: Do not report retries, fail faster (Frank A. Zdarsky)
- EDM-417: Compute service-side status (Frank A. Zdarsky)
- EDM-649: Add specific error message when CSR approval fails (Lily Sturmann)
- EDM-649: Remove extraneous CN len check (Lily Sturmann)
- EDM-842: transient networking error should not mark agent degraded (Sam Batschelet)
- EDM-772: Move UI chart to main repo (#673) (Rastislav Wagner)
- NO-ISSUE: agent: ensure bootstrap status (Sam Batschelet)
- EDM-761: Document lifecycle hooks (Frank A. Zdarsky)
- EDM-764: Update Hooks API implementation (Frank A. Zdarsky)
- EDM-764: Update Hooks API (Frank A. Zdarsky)
- EDM-659: agent/fileio: ensure ignition gid, uid and mode (Sam Batschelet)
- NO-ISSUE: Pass internalOpenShiftApiUrl from values to api-config CM (#680) (Rastislav Wagner)
- EDM-424: add update policy api and validation (Sam Batschelet)
- EDM-420: Increase DB parameters (#669) (Gregory Shilin)
- NO-ISSUE: Append UI port to valid redirect URIs (rawagner)
- EDM-390: Add decommissioning route to device API (Lily Sturmann)
- EDM-417: Centralize API consts (Frank A. Zdarsky)
- NO-ISSUE: add command to prepare e2e test (sserafin)
- EDM-621: Fix microshift registration docs (Avishay Traeger)
- EDM-767: Actually update ignition mount path (Avishay Traeger)
- EDM-708: Reduce git access (Avishay Traeger)
- NO-ISSUE: Remove duplicated code in git helpers (Avishay Traeger)
- MGMT-17672: device: align update status phases (Sam Batschelet)
- Add developer documentation for field-selector (#658) (Assaf Albo)
- EDM-681: Allow field selector when 'summaryOnly' is enabled (#656) (Assaf Albo)
- EDM-704: Automate test 75991 (sserafin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: created a document with instructions to run devicesimulator (Gregory Shilin)
- EDM-695: Logger verbosity flag was added (-v) (#651) (Gregory Shilin)
- EDM-423: Fix lexer state for nested exists/notexists selectors (#655) (Assaf Albo)
- EDM-423: Adapt K8s lexer to support RHS equality symbol (asafbss)
- EDM-423: Modify k8s containment operator; remove support for 'in' and 'notin' on JSON fields (asafbss)
- EDM-423: Remove selector casting; implement a whitelist of selectors per resource for stricter filtering (asafbss)
- EDM-423: Move alias back to label in API while keeping it as a field in device model (asafbss)
- EDM-423: Add documentation for Field Selectors (asafbss)
- EDM-666: Updated selector names to match the documented API (asafbss)
- EDM-664: Added selector support for Spec field in field-selector (asafbss)
- EDM-423: Introduce Alias Field for Device Metadata (asafbss)
- EDM-423: Add more Kubernetes operators to enhance selectors for fields (asafbss)
- EDM-423: Kubernetes vanilla label selector (asafbss)
- NO-ISSUE: Fix linter and spellchecker issues (Frank A. Zdarsky)
- NO-ISSUE: Fix path-filter (Frank A. Zdarsky)
- EDM-694: Add Valkey key value store service (Ricardo Noriega)
- EDM-694: Use primary IP and nip.io domains (Ricardo Noriega)
- EDM-694: Add FlightCtl Network to slice (Ricardo Noriega)
- EDM-694: Add Makefile Quadlet targets for deploy and clean (Ricardo Noriega)
- EDM-694: Initial FlightCtl deployment with Quadlets (Ricardo Noriega)
- NO-ISSUE: Update config storage API (Avishay Traeger)
- EDM-578: Remove templateversion populate task (Avishay Traeger)
- EDM-582: Freeze HTTP configurations (Avishay Traeger)
- EDM-583: Freeze k8s secret configurations (Avishay Traeger)
- EDM-581: Freeze git configurations (Avishay Traeger)
- NO-ISSUE: Remove device's TV annotation if removed from fleet (Avishay Traeger)
- EDM-580: Deploy Valkey for frozen configurations (Avishay Traeger)
- EDM-578: Separate fleet validate and device render logic (Avishay Traeger)
- EDM-420: Enable to run devicesimulator on multiple hosts (#650) (Gregory Shilin)
- NO-ISSUE: Improve UpdateDeviceWithRetries to handle all errors (Miguel Angel Ajo)
- EDM-446: device/fileio: ensure readable paths in PathExists (Sam Batschelet)
- EDM-656: agent: clarify completed status (Sam Batschelet)
- EDM-656: agent: ensure Shutdown is threadsafe (Sam Batschelet)
- EDM-656: agent/device improve systemd status reporting (Sam Batschelet)
- NO-ISSUE: console: simplify exec test case (Sam Batschelet)
- NO-ISSUE: Update UI to v0.3.0 (Celia Amador)
- EDM-673: Enable exposing APIs via Gateway (rawagner)
- EDM-240: improve logging (Sam Batschelet)
- EDM-240: tests: add embeded application image (Sam Batschelet)
- EDM-240: applications: add support for embedded compose (Sam Batschelet)
- EDM-240: agent: add shutdown manager and improve graceful flow (Sam Batschelet)
- NO-ISSUE: Starting tests for the update lifecycle (Miguel Angel Ajo Pelayo)
- EDM-648: Fix integration tests (Ricardo Noriega)
- EDM-648: Refactor HTTP requests into helpers (Ricardo Noriega)
- EDM-648: Adding new HTTP repotester (Ricardo Noriega)
- EDM-648: Add validationSuffix API (Ricardo Noriega)
- NO-ISSUE: Prepare for 0.3.0-rc3 (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Redirect http keycloak to https (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Fixing stagging db resource tuning and route labels (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Fix keycloak-db-pvc.yaml label indent (Miguel Angel Ajo Pelayo)
- EDM-622: Fix local registry deploy targets (Ricardo Noriega De Soto)
- EDM-620: enable using specific rpm releases in e2e testing (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Update ui chart to 0.3.0-rc2 (Miguel Angel Ajo Pelayo)
- NO-ISSUE: device/bootstrap: unset NOTIFY_SOCKET after bootstrap (Sam Batschelet)
- NO-ISSUE: Fix docs path filter and linting issue (Frank A. Zdarsky)
- EDM-617: ignition: user,group ensure parse int (#624) (Sam Batschelet)
- EDM-240: docs: add compose requirements to Containerfile (#622) (Sam Batschelet)
- EDM-412: Fix podman build typo (Lily Sturmann)
- EDM-655: applications: reduce scope of events api (#621) (Sam Batschelet)
- NO-ISSUE: agent: console: adjust log levels (#620) (Sam Batschelet)
- NO-ISSUE: fix rabbitmq pv path (mparram)
- EDM-240: update applications documentation (#607) (Sam Batschelet)
- EDM-240: ensure network cleanup if the contianers are stopped (#617) (Sam Batschelet)
- EDM-642: EDM-240: add support for completed applications status (#612) (Sam Batschelet)
- EDM-650: Load k8s ca.crt when deployed on k8s (rawagner)
- EDM-587: Fix dev Kind deployment with auth enabled (rawagner)
- NO-ISSUE: fix link typo (Lily Sturmann)
- NO-ISSUE: Point helm to ui 0.3.0-rc1 (Miguel Angel Ajo Pelayo)
- MGMT-18170: Update documentation for certificate request (Lily Sturmann)
- EDM-623: Restore Prometheus default settings (#608) (Celia Amador)
- NO-ISSUE: Add support for match expressions (Ori Amizur)
- EDM-604: Improve error handling and messages for selector errors (asafbss)
- EDM-616: Fix 500 error when filtering devices using JSONB field selectors (asafbss)
- EDM-423: Improve error handling for SelectorError type (asafbss)
- EDM-423: Change description for fieldSelector API to improve clarity (asafbss)
- EDM-423: Refactor sorting functionality (asafbss)
- EDM-423: Refactor field selector for future enhanced operators integration (asafbss)
- EDM-423: Initial integration of field selector and orderby with service and store (asafbss)
- EDM-423: Initial integration of field selector with Kubernetes selectors (asafbss)
- EDM-423: Implement query-based filtering solution (asafbss)
- NO-ISSUE: ensure agent teardown on failure (#606) (Sam Batschelet)
- EDM-240: ensure application status (#595) (Sam Batschelet)
- EDM-513: Enable E2E on a target OpenShift deployment (Miguel Angel Ajo)
- EDM-619: Improve login error handling and merge skip-tls-insecure flags (#603) (Rastislav Wagner)
- NO-ISSUE: improve simulator logging (#605) (Sam Batschelet)
- NO-ISSUE: Fix links to UI image versions, not helm charts (Celia Amador)
- NO-ISSUE: Document how to modify the deployed UI version (Celia Amador)
- EDM-577: Added new CLI testcases (Samuel de la Cruz)
- NO-ISSUE: Fix nil pointer deref in agentserver when metrics == nil (vraiti)
- NO-ISSUE: Fix agent/api traffic instrumentation bug (#599) (vraiti)
- NO-ISSUE: Remove containers matchPattern from device spec (#596) (Sam Batschelet)
- EDM-613: Adapt examples to updated config API (Frank A. Zdarsky)
- EDM-613: Adapt to updated config API (Frank A. Zdarsky)
- EDM-613: Remove discriminator from config API (Frank A. Zdarsky)
- EDM-567: fix conditional workflows (Frank A. Zdarsky)
- EDM-601: Improve deployment experience on Kind (rawagner)
- NO-ISSUE: Move Prometheus components to e2e-extras (vraiti)
- NO-ISSUE: modify publish latest cli bins action to properly handle existing latest release (Dakota Crowder)
- EDM-609: EDM-608: ensure unique application names (#591) (Sam Batschelet)
- NO-ISSUE: Update golangci lint (#593) (Frank Zdarsky)
- EDM-531: Docs for ACM registration (#571) (Ricardo Noriega De Soto)
- NO-ISSUE: Update certificate request command in building-images.md (Lily Sturmann)
- EDM-595: Fix bug in csr-generate usage description (Lily Sturmann)
- EDM-595: Update help description formatting in CLI (Lily Sturmann)
- EDM-240: applications: add support for reconciliation and status repoting (#561) (Sam Batschelet)
- EDM-240: breaking: make application status data an array (#586) (Sam Batschelet)
- EDM-603: Add prometheus target filters (#590) (vraiti)
- EDM-463: Enable flightctl-api access to to ingress (#551) (Miguel Angel Ajo Pelayo)
- NO-ISSUE: fix nodeports references and prometheus default (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Cleanup helm install details (#574) (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Fix Prometheus Nodeport in Kind (#585) (vraiti)
- NO-ISSUE: Fix helm error on acm install (Miguel Angel Ajo)
- EDM-588: Fix link to UI and pass insecureSkipVerify flag for auth config (rawagner)
- NO-ISSUE: Move device/fleet spec comparison methods to api (Avishay Traeger)
- EDM-240: plumb applications API (#572) (Sam Batschelet)
- EDM-447: Add fleet policy in openapi (Ori Amizur)
- EDM-571: Support for setuid/setgid/sticky bits in inline config (Avishay Traeger)
- EDM-485: Update smoke test sim cmd (Dakota Crowder)
- NO-ISSUE: ensure enrollemnt requests are retried (#576) (Sam Batschelet)
- EDM-573: Run helm dependency build in release job (rawagner)
- MGMT-18708: use client-enrollment as name (Miguel Angel Ajo Pelayo)
- MGMT-18708: Retry API login and reduce agent intervals (Miguel Angel Ajo Pelayo)
- MGMT-17725: Align Prometheus components with values.kind.yaml (vraiti)
- MGMT-17725: Fix instrumentation audit workers (vraiti)
- MGMT-18708: Add certificate request command to CI (Lily Sturmann)
- MGMT-18708: Add single CLI command to obtain enrollment cert (Lily Sturmann)
- MGMT-18708: Add auto-approval for enrollment certificates (Lily Sturmann)
- MGMT-18708: Add 'enrollment' as valid signer (Lily Sturmann)
- MGMT-18708: Add handling for encrypted keys (Lily Sturmann)
- MGMT-17673: add image building docs (Frank A. Zdarsky)
- EDM-555: add resource monitor API validation (#563) (Sam Batschelet)
- EDM-567: Do not trigger full tests on docs changes (Frank A. Zdarsky)
- Reduce backoff durations and log slow API requests (#564) (Sam Batschelet)
- EDM-554: e2e images: enable podman.service (#562) (Sam Batschelet)
- MGMT-18458: EDM-295: EDM-296: Simplify helm charts and add UI helm chart as dependency (rawagner)
- EDM-563: Fleet list API should return device count only on demand (Avishay Traeger)
- EDM-546: Fix device spec comparisons (Avishay Traeger)
- EDM-511: Provide script to generate endpoint environment variables (Miguel Angel Ajo)
- MGMT-17725: Add Prometheus observability to Flightctl (vraiti)
- EDM-485: Add label arg for devices created by the device simulator (Dakota Crowder)
- MGMT-17725: Add observability instrumentation to flightctl API server (Vance Raiti)
- EDM-541: Move developer docs (#560) (Frank Zdarsky)
- EDM-540: Fix validateAgainstSchema causing 400 errors on non-nullable required status fields (asafbss)
- EDM-519: add better handling of obsolete files (#547) (Sam Batschelet)
- NO-ISSUE: Enable LTO to reduce binary size (Miguel Angel Ajo Pelayo)
- EDM-506: Enable static builds for CLI (#552) (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Align openapi descriptions and user docs (Avishay Traeger)
- NO-ISSUE: Move GRPC consts to separate package (Avishay Traeger)
- EDM-455: Simplify inline config API (Avishay Traeger)
- NO-ISSUE: Remove gorm dep from flterrors (Avishay Traeger)
- EDM-458: Refine names and minor adjustments (asafbss)
- EDM-458: Suppress gocyclo lint warning for printTable function (asafbss)
- EDM-458: adapt integration tests for summary and type changes (asafbss)
- EDM-458: add support for SummaryOnly for listDevices API (asafbss)
- EDM-458: temporary adapt  the cli to support devices summary (asafbss)
- EDM-458: return 400 on limit error (asafbss)
- EDM-458: fix retrieving devices' statuses by kind fleet (asafbss)
- EDM-458: adding devices summary API (asafbss)
- EDM-427: Remove yaml dep (Dakota Crowder)
- EDM-427: Change yaml unmarshal when reading bootc status to use json (Dakota Crowder)
- EDM-427: Remove log (Dakota Crowder)
- MGMT-17672: Adding device and fleet management sections (Frank A. Zdarsky)
- EDM-427: Add additional test cases (Dakota Crowder)
- EDM-427: Scaffold tests for IsOsImageReconciled (Dakota Crowder)
- EDM-427: Modify IsOsImageReconciled to use target in its comparison (Dakota Crowder)
- NO-ISSUE: fix CLI version output (Frank A. Zdarsky)
- NO-ISSUE: more detailed CLI version info (Frank A. Zdarsky)
- EDM-427: Fix spelling err, add image digest status update to system info exporter (Dakota Crowder)
- EDM-507: Add -o wide to device table (Frank A. Zdarsky)
- EDM-427: Add setting diget in SetOSImage (Dakota Crowder)
- NO-ISSUE: Bump gorm.io/driver/postgres from 1.5.7 to 1.5.9 (dependabot[bot])
- EDM-427: Send image digest as a part of device os status update during bootstrap (Dakota Crowder)
- EDM-427: Add test cases with port (Dakota Crowder)
- EDM-299: make iamge required for ImageApplicationProvider (Sam Batschelet)
- EDM-299: add validation for applications API (Sam Batschelet)
- EDM-427: Use regex definition to parse imageinto base, tag, and digest (Dakota Crowder)
- EDM-427: Remove image type, add simple method for converting image to bootc target before swtich is called (Dakota Crowder)
- EDM-427: fix linting issue in test (Dakota Crowder)
- EDM-427: Report current booted os image digest when updating the device os status (Dakota Crowder)
- EDM-427: Fix bootstrap test (Dakota Crowder)
- EDM-427: remove imageDigest from spec, shift around some code in image package (Dakota Crowder)
- EDM-299: add device applications API (#441) (Sam Batschelet)
- EDM-452: Ensure tag releases for cli, stop recreating (Miguel Angel Ajo Pelayo)
- EDM-452: Ensure plain version tags for releases (Miguel Angel Ajo Pelayo)
- EDM-482: node-exporter conatainer failed to start due the Failed to open directory, disabling udev device properties (Ori Amizur)
- EDM-427: Separate out image pkg (Dakota Crowder)
- EDM-427: remove isOsSame (Dakota Crowder)
- EDM-427: update ensureImage flow to use Image type (Dakota Crowder)
- EDM-427: update checkRollback and IsRollingBack (Dakota Crowder)
- EDM-427: fix IsIOSUpdate, add bootc status to image func and update CheckOsRec (Dakota Crowder)
- EDM-427: add areImagesEquivalent func (Dakota Crowder)
- EDM-427: begin working towards shared Image struct intermediary to make comparisons between device os specs and bootc state easier to reason about (Dakota Crowder)
- EDM-462: refactored the tests to use testify suite through "go test". (Amir Yogev)
- EDM-462: dropped check for nil message + renamed console creation. (Amir Yogev)
- EDM-427: add imageDigest to device os spec and status, use optional digests in IsOSUpdate (Dakota Crowder)
- EDM-462: keep using bash as a test command and refined test cases with mock setup. (Amir Yogev)
- EDM-456: Update allowed callback urls in Kind deployment (#533) (Rastislav Wagner)
- EDM-462: not using bash as a test command + mock StreamClient.Recv(). (Amir Yogev)
- EDM-462: adding unit tests for console.go. (Amir Yogev)
- MGMT-18490: Add shell completion to CLI RPM (Vance Raiti)
- EDM-373: Style adjustments to getRenderedVersion (Dakota Crowder)
- EDM-373: Style adjustments to getNextRenderedVersion (Dakota Crowder)
- EDM-373: Style adjustments for pathFromType (Dakota Crowder)
- EDM-373: Fix spelling mistakes (Dakota Crowder)
- EDM-373: Remove a test case and consolidate logic (Dakota Crowder)
- EDM-373: Address linting issues w/ spec file (Dakota Crowder)
- EDM-373: Slight adjustments / cleanup for some tests (Dakota Crowder)
- NO-ISSUE: ensure cli builds on new tag (#521) (Sam Batschelet)
- EDM-373: Additional cases for GetDesired (Dakota Crowder)
- EDM-373: Begin adding tests for GetDesired (Dakota Crowder)
- EDM-298: Add user guide for deploying Flightctl on ACM (#510) (Rastislav Wagner)
- EDM-428: Remove interval and TPM fields from enrollmentconfig API (#522) (Rastislav Wagner)
- EDM-352: Add flow chart of for tasks in docs (Avishay Traeger)
- EDM-373: Add tests around request to get spec (Dakota Crowder)
- NO-ISSUE: agent: remove samber/lo as dep (Sam Batschelet)
- EDM-373: Add test cases for pathFromType, getNextRenderedVersion, getRenderedVersion (Dakota Crowder)
- EDM-373: Add tests for IsUpdating (Dakota Crowder)
- EDM-373: Add tests for Rollback and SetClient (Dakota Crowder)
- EDM-373: Write tests for PrepareRollback (Dakota Crowder)
- EDM-373: Adjust test names (Dakota Crowder)
- EDM-373: Add test coverage for additional methods, add bootc status err (Dakota Crowder)
- EDM-373: Move defined error types down into private write/read calls and have public interface wrap them (Dakota Crowder)
- EDM-373: Have writeRenderedToFile raise write specific err (Dakota Crowder)
- EDM-373: Add additional error types for reading (Dakota Crowder)
- NO-ISSUE:  Add support for builtin hooks (Ori Amizur)
- EDM-373: Add ErrCheckingFileExists (Dakota Crowder)
- EDM-373: Create an ErrWritingSpec shared error type (Dakota Crowder)
- EDM-373: Use shared error type and ErrorIs in existing specs (Dakota Crowder)
- EDM-373: Spec manager test coverage (#520) (DakCrowder)
- EDM-373: Remove fmt dep from test file (Dakota Crowder)
- EDM-373: Add spec manager unit tests for NewManager, Initialize, Ensure (Dakota Crowder)
- NO-ISSUE: Update version in docs (Celia Amador)

* Tue Feb 11 2025 Lily Sturmann <lkatalin@users.noreply.github.com> - 0.2.1~778~g6ec1839-1.20250211115157971745.propagate.rendered.778.g6ec1839
- NO-ISSUE: Do not create NetworkPolicies when deploying on ACM (#890) (Rastislav Wagner)
- NO-ISSUE: Clean unused API that is now handled via ws (Miguel Angel Ajo)
- NO-ISSUE: Update the Agent API to support multiple consoles (Miguel Angel Ajo)
- EDM-1141: In some cases the rollout fails but it is not reported with an error message and does not timeout (Ori Amizur)
- NO-ISSUE: Pull CI RPM Builder image before using it (Miguel Angel Ajo)
- EDM-973: device/hooks: skip run action execution if binary not found (#889) (Sam Batschelet)
- EDM-1104: agent: improve rollback error handling and testing (Sam Batschelet)
- NO-ISSUE: *: ensure response bodies are closed (Sam Batschelet)
- EDM-611: device/applications: dont mark degraded on reboot if there are no apps (Sam Batschelet)
- EDM-683: Normalize Device Labels into a Separate Table for Optimized Queries and Fast Distinct Label Retrieval (#845) (Assaf Albo)
- EDM-1101: pty console support and selinux (Miguel Angel Ajo)
- EDM-1094: API accepts decimal numbers for rollout policy percentages (Ori Amizur)
- stam (Ori Amizur)
- NO-ISSUE: Additional fields for kv ss and secrets job (#874) (Rastislav Wagner)
- EDM-390: Update device lifecycle status immediately upon user request (Lily Sturmann)
- EDM-1087: Handle configuration changes (Ori Amizur)
- EDM-925: T17: Do not only rely on client-side authorization (#834) (Gregory Shilin)
- EDM-1014: Report versions of all software components phase 2 (#862) (Gregory Shilin)
- EDM-1104: agent/rollback: set version failed before rollback (Sam Batschelet)
- NO-ISSUE: test/agent: improve container workflow (Sam Batschelet)
- EDM-1086: agent: improve logging during image pull (Sam Batschelet)
- EDM-1000: agent/hooks: add success criteria when hooks fire to the logs (Sam Batschelet)
- EDM-715: Wrap variables in script files in quotes (Dakota Crowder)
- EDM-715: Remove WantedBy=default.target (Dakota Crowder)
- EDM-715: Remove setting HOME in kv container (Dakota Crowder)
- EDM-715: tag images with 0.4.0 (Dakota Crowder)
- EDM-715: Configure standalone deployments for rootless podman (Dakota Crowder)
- EDM-715: Add default.target to .container files so services start on system boot (Dakota Crowder)
- EDM-715: Ensure directories are created before copying files (Dakota Crowder)
- EDM-715: Configure podman for rootless setup (Dakota Crowder)
- EDM-715: Explicitly define volumes for api, db, kv (Dakota Crowder)
- EDM-500: EDM-999: agent: ensure rollback on failure (Sam Batschelet)
- EDM-1096: Print num devices in list fleets only when available (Avishay Traeger)
- NO-ISSUE: Use PostgreSQL 16 instead of 12 (#870) (Gregory Shilin)
- NO-ISSUE: Add podManagementPolicy field to kv statefulset (rawagner)
- NO-ISSUE: Generate secrets via job (#863) (Rastislav Wagner)
- EDM-1072: Replace vagrant with libvirt solution to run e2e in host not suitable for bootc (sserafin)
- EDM-1082: Bug fix to ensure enrolled device lifecycle status is not reset (Lily Sturmann)
- EDM-1025: Move callback manager to separate package (Avishay Traeger)
- EDM-1071: Add condition displaying the rollout status (Ori Amizur)
- EDM-1014: Report versions of all software components p1 - cli+service (#854) (Gregory Shilin)
- EDM-960:  Inline config E2E tests (amalykhi)
- EDM-1074: The doc to install flightctl-cli got a typo in information … (#847) (Gregory Shilin)
- EDM-1065: Return device status summary in fleet list (Avishay Traeger)
- NO-ISSUE: do not create our own versions of lo.ToPtr (Gregory Shilin)
- NO-ISSUE: cmd/flightctl-agent: fix config dir validation (#844) (Antonio Murdaca)
- EDM-811: Enable status.lifecycle.status field selector for devices (Lily Sturmann)
- EDM-1068: Allow insecure comm with Keycloak for external connections too (#838) (Rastislav Wagner)
- EDM-1070: It's not possible to update a fleet setting only disruption budget without device selection (Ori Amizur)
- EDM-1075: api/properties: fix bugs in IsManagedBy (Sam Batschelet)
- NO-ISSUE: test/sctipts: fix trap typo (Sam Batschelet)
- NO-ISSUE: properly handle wrapped errors (#836) (Gregory Shilin)
- EDM-885: git is missed on some platforms (#841) (Gregory Shilin)
- NO-ISSUE: Respect global.generateSecrets flag for Keycloak chart too (#835) (Rastislav Wagner)
- EDM-1069: Fix updating device after fleet update (Avishay Traeger)
- EDM-1062: Handle rollout of a new device or a device that just joined a fleet (Ori Amizur)
- NO-ISSUE: Small API fixes (Frank A. Zdarsky)
- NO-ISSUE: makefile: add make-agent-container (Sam Batschelet)
- EDM-1064: Add architecture documentation for rollout policies (Ori Amizur)
- EDM-945: Return the most relevant openapi error (Avishay Traeger)
- EDM-1054: Remove ownership change check in store (Avishay Traeger)
- NO-ISSUE:  Increment resource_version when marking/unmarking devices for rollout (Ori Amizur)
- NO-ISSUE: add typing to helper (Cameron Wall)
- EDM-1055: agent: add support for rpm-ostree hosts (Sam Batschelet)
- NO-ISSUE: Update flight control API config (Cameron Wall)
- EDM-520: Implement rollout policy batch selection (Ori Amizur)
- NO-ISSUE: Split listQuery 'Build' function to 'BuildNoOrder' and 'Build'. (Ori Amizur)
- NO-ISSUE: Fix strategy for rollout device selection (Ori Amizur)
- EDM-1052: Return full resources upon update (Avishay Traeger)
- EDM-1022: device: ensure continuity between the resource and summary status (Sam Batschelet)
- EDM-1043: Adding flightctl application lifecycle E2E test TC76800 (sserafin)
- EDM-885: RPM build (Gregory Shilin)
- EDM-1024: Use generic implementations for common store methods (Avishay Traeger)
- EDM-707: device/applications/compose: enforce service container_name is not supported (Sam Batschelet)
- NO-ISSUE: agent/config: ensure required directories (Sam Batschelet)
- NO-ISSUE: make packit replace -rc to ~rc in tags (#810) (Miguel Angel Ajo Pelayo)
- EDM-390: Remove decommissioning device from fleet (Lily Sturmann)
- EDM-1012: Fix device updated status for managed devices (Avishay Traeger)
- EDM-993: CLI headless login (#793) (Rastislav Wagner)
- NO-ISSUE: Handle release tags with ~rc0 / ~rc1 etc... (Miguel Angel Ajo Pelayo)
- Helm updates: Fix Redis deployment and remove DB limits (#802) (Avishay Traeger)
- EDM-391: Update device side decommission handling (Lily Sturmann)
- NO-ISSUE: Add missing API description (Frank A. Zdarsky)
- EDM-885: added go-rpm-macros to docs (#800) (Gregory Shilin)
- EDM-1046: applications/compose: ensure manually stopped containers are tracked as degraded status (Sam Batschelet)
- Add keyset-based matching to label selectors and fix orphaned device selection bug (#803) (Assaf Albo)
- EDM-1012: Set OutOfDate info if rollout failed (Avishay Traeger)
- EDM-882: Approving ER adds user identity (#788) (Rastislav Wagner)
- EDM-820: Generate passwords & inject them via secrets (#796) (Rastislav Wagner)
- NO-ISSUE: tests/e2e/agent bump upgrade timeout to 2m (Sam Batschelet)
- EDM-722: applications: improve beforeUpdate validations (Sam Batschelet)
- EDM-213: e2e agent automation (#784) (Samuel De La Cruz Lopez)
- EDM-556: add device engine (Sam Batschelet)
- EDM-885: make build-cli-multiarch target (#789) (Gregory Shilin)
- EDM-1038: Create container with all CLI artifacts for publishing (Miguel Angel Ajo)
- EDM-714: Remove rabbit refs in deploy scripts (Dakota Crowder)
- EDM-714: Fix file removal (Dakota Crowder)
- Revert "EDM-714: Rename rabbitmq to mq to be more inline with db and kv, fix file removal" (Dakota Crowder)
- EDM-714: Rename rabbitmq to mq to be more inline with db and kv, fix file removal (Dakota Crowder)
- EDM-714: Specify periodic and worker as systemd deps of the api container (Dakota Crowder)
- EDM-714: Better handling around setting PRIMARY_IP from our friend coderabbit (Dakota Crowder)
- EDM-714: Remove -it from not interactive exec cmds (Dakota Crowder)
- EDM-714: Fix standalone mq commands (Dakota Crowder)
- EDM-714: Add shared file for deploying individual services, share some config, cleanup the existing scripts (Dakota Crowder)
- EDM-714: Move deploy quadlets logic to a script file (Dakota Crowder)
- EDM-714: Move clean quadlets logic to a script file w/ some better logging (Dakota Crowder)
- EDM-714: Use more specific matching when copying files to /etc/containers/systemd/ (Dakota Crowder)
- EDM-714: Use more specific matching for stopping standalone services (Dakota Crowder)
- EDM-714: Use absolute paths for volume mount refs (Dakota Crowder)
- EDM-714: Add back creation of admin db to dpeloy-db make command (Dakota Crowder)
- EDM-714: Remove podman-compose code, move quadlets code into the deploy/podman directory (Dakota Crowder)
- EDM-714: Change deploy and kill kv commands to use quadlets (Dakota Crowder)
- EDM-714: Change deploy and kill mq commands to use quadlets (Dakota Crowder)
- EDM-714: Remove standalone network (Dakota Crowder)
- EDM-714: Use separate standalone config to spin up db rather than templating (Dakota Crowder)
- EDM-714: Spin up standalone postgres db (Dakota Crowder)
- EDM-714: Remove redis volume when we clean quadlets deployment (Dakota Crowder)
- EDM-714: Create separate file for the redis.conf volume instead of using ExecStartPre (Dakota Crowder)
- EDM-714: Wait for postgres db and add superuser permission when starting up quadlets (Dakota Crowder)
- EDM-846: Deploy default fctl roles in ACM env (#708) (Rastislav Wagner)
- EDM-1018: Add helm values for ACM deployment (#791) (Avishay Traeger)
- EDM-1036: Dispatch tasks via Redis (Avishay Traeger)
- EDM-773: Update charts to support deployment via ACM operator (#780) (Miguel Angel Ajo Pelayo)
- EDM-885: move CLI build to a separate PR (Gregory Shilin)
- EDM-885: RPM versioning (Gregory Shilin)
- EDM-967: Add identity information for K8S (#785) (Ori Amizur)
- EDM-768: Run linter on OpenAPI specs (Frank A. Zdarsky)
- EDM-768: Only set pdeathsig on Linux (Frank A. Zdarsky)
- EDM-768: Simplify enrollment config (Frank A. Zdarsky)
- EDM-768: Align CSR API with K8s (Frank A. Zdarsky)
- EDM-1021: applications: add controller sync test (Sam Batschelet)
- EDM-1021: applications: ensure id is deterministic (Sam Batschelet)
- EDM-1015: Add note in docs about go template syntax (Avishay Traeger)
- EDM-989: Flightctl should fail with explicit message if login was not done (rawagner)
- EDM-992: Validate URL for login cmd (#777) (Rastislav Wagner)
- EDM-983: Testing for Filtering (Eldar101)
- EDM-710: Validate Repository Spec Selectors Using GenericRepoSpec (#769) (Assaf Albo)
- EDM-1017: Replace variables in git config mountPath (Avishay Traeger)
- EDM-390: Update device lifecycle status based on Condition (Lily Sturmann)
- EDM-391: add lifecycle manager (Sam Batschelet)
- NO-ISSUE: Add shortcut 'k' for 'insecure-skip-tls-verify' flag (#778) (Rastislav Wagner)
- EDM-869: TC75506 Resources lifecycle (#687) (amalykhi)
- NO-ISSUE: Small fix in template variables doc (sserafin)
- EDM-821: Support pure k8s authN (rawagner)
- Revert "EDM-773: Update charts to support deployment via ACM operator" (#772) (Rastislav Wagner)
- EDM-969: applications: ensure unique ID (Sam Batschelet)
- EDM-969: applications: add internal support for tracking by ID (Sam Batschelet)
- EDM-390: Add decommission spec to rendered device config (Lily Sturmann)
- EDM-943: Add document describing k8s RBAC authorization (Ori Amizur)
- EDM-390: Set decommission request in device spec (Lily Sturmann)
- EDM-390: Add decommission request to device spec (Lily Sturmann)
- EDM-1008: Add permissions check for device console (#763) (Rastislav Wagner)
- EDM-1005: Fix selector behavior for NULL columns in the database (#762) (Assaf Albo)
- EDM-1011: CLI to request device count when listing fleets (Avishay Traeger)
- EDM-1010: Fix template variable for inline config path (Avishay Traeger)
- EDM-526: policy: ensure DST is properly covered (Sam Batschelet)
- EDM-970: Fix K8S_RBAC_NS value for ACM deployment (#759) (Rastislav Wagner)
- EDM-773: Update charts to support deployment via ACM operator (#760) (Rastislav Wagner)
- EDM-526: policy: improve logging (Sam Batschelet)
- EDM-526: device: ensure policy has an escape hatch (Sam Batschelet)
- EDM-526: policy: add schedule tests and improve logic (Sam Batschelet)
- EDM-526: api: install tzdata for time zone validation (Sam Batschelet)
- EDM-526: spec/queue: refactor (Sam Batschelet)
- EDM-526: device: update status to align with policy checks and docs (Sam Batschelet)
- EDM-526: spec/queue: improve docs (Sam Batschelet)
- EDM-526: plumb update policy (Sam Batschelet)
- EDM-526: agent: add update policy (Sam Batschelet)
- Integrate Labels and Annotations Filtering into Selector Framework (#751) (Assaf Albo)
- EDM-768: Align createOrUpdate (Frank A. Zdarsky)
- EDM-768: Fix properties next to ref linting issue (Frank A. Zdarsky)
- EDM-768: Fix PascalCase linting issue (Frank A. Zdarsky)
- EDM-768: Fix linting issues (Frank A. Zdarsky)
- EDM-822: Container port (Eldar101)
- EDM-781: Field selectors tests (Eldar Weiss)
- EDM-390: Set enrolled devices to 'Enrolled' lifecycle status (Lily Sturmann)
- EDM-954: Use approved RabbitMQ (Avishay Traeger)
- EDM-819: Remove any unnecessary helm for the gRPC endpoint (Miguel Angel Ajo)
- EDM-818: gRPC and agent HTTPS under the same endpoint (Miguel Angel Ajo)
- EDM-955: Use approved Redis (Avishay Traeger)
- NO-ISSUE: Collect logs in smoke/e2e github workflows (Avishay Traeger)
- EDM-922: Fine-tune HTTP server settings (Avishay Traeger)
- EDM-953: Use approved Postgres (Avishay Traeger)
- NO-ISSUE: omit grpc from make generate (Sam Batschelet)
- EDM-649: Update CSR error codes to be more expressive and accurate (Lily Sturmann)
- NO-ISSUE: reduce scope of bootc API (Sam Batschelet)
- Revert "NO-ISSUE: helm: unblock CI pin rabbitmq" (Sam Batschelet)
- EDM-390: Add decommission CLI command (Lily Sturmann)
- EDM-390: Small fix for decommission target type (Lily Sturmann)
- NO-ISSUE: troubleshooting: add basic agent debug (Sam Batschelet)
- EDM-948: Allow specifying Namespace for k8s RBAC checks (#736) (Rastislav Wagner)
- EDM-870: flightctl console cli on web socket (#731) (Miguel Angel Ajo Pelayo)
- MGMT-18492: Add logical support for reboot hooks (Sam Batschelet)
- EDM-390: Add lifecyclestatus to devicestatus (Lily Sturmann)
- NO-ISSUE: libvirt-dev should always be installed (Miguel Angel Ajo)
- NO-ISSUE: Implement Go tools pattern (Frank A. Zdarsky)
- NO-ISSUE: Update GH runner (Frank A. Zdarsky)
- EDM-390: Add decommissioning field to rendered device spec (Lily Sturmann)
- NO-ISSUE: packaging: add flightctl agent version to must-gather (Sam Batschelet)
- NO-ISSUE: metrics: register flightctl_api_errors_client_total (Sam Batschelet)
- EDM-391: Add 'decommissioning' Condition and Reasons for device (Lily Sturmann)
- NO-ISSUE: Use a password for accessing Valkey (Avishay Traeger)
- NO-ISSUE: Move key-value code out of tasks package (Avishay Traeger)
- EDM-854: Use go-templates for fleet template parameters (Avishay Traeger)
- NO-ISSUE: helm: unblock CI pin rabbitmq (Sam Batschelet)
- EDM-879: improve service generated app status (Sam Batschelet)
- EDM-886: correctly fmt service side app status (Sam Batschelet)
- EDM-526: ensure errors reported by os.exec are properly handeled (Sam Batschelet)
- EDM-870: ws console wiring (Miguel Angel Ajo)
- EDM-870: Move console request/connection to websocket (Miguel Angel Ajo)
- EDN-860: Add permission checks for all API endpoints (Ori Amizur)
- NO-ISSUE: Fix OpenAPI descriptions (Frank A. Zdarsky)
- EDM-848: revert tzdata host mount (#690) (Sam Batschelet)
- EDM-876: Fix helm template error (Celia Amador)
- EDM-788: Add init script for PostgreSQL to set master user as superuser (#679) (Assaf Albo)
- EDM-838: Update ACM registration doc (Frank A. Zdarsky)
- NO-ISSUE: redeploy kind pods for development (Miguel Angel Ajo)
- NO-ISSUE: move ownership od status exporters to managers (Sam Batschelet)
- EDM-853: spec/queue: ensure item requeue backoff only if tried  (#696) (Sam Batschelet)
- EDM-642: Remove sorting mechanism for TP phase (#701) (Assaf Albo)
- MGMT-17672: Document device statuses (Frank A. Zdarsky)
- EDM-417: Get renderedVersion from DB (Frank A. Zdarsky)
- EDM-417: Update unit-tests for server-side status (Frank A. Zdarsky)
- EDM-417: Do not report retries, fail faster (Frank A. Zdarsky)
- EDM-417: Compute service-side status (Frank A. Zdarsky)
- EDM-649: Add specific error message when CSR approval fails (Lily Sturmann)
- EDM-649: Remove extraneous CN len check (Lily Sturmann)
- EDM-842: transient networking error should not mark agent degraded (Sam Batschelet)
- EDM-772: Move UI chart to main repo (#673) (Rastislav Wagner)
- NO-ISSUE: agent: ensure bootstrap status (Sam Batschelet)
- EDM-761: Document lifecycle hooks (Frank A. Zdarsky)
- EDM-764: Update Hooks API implementation (Frank A. Zdarsky)
- EDM-764: Update Hooks API (Frank A. Zdarsky)
- EDM-659: agent/fileio: ensure ignition gid, uid and mode (Sam Batschelet)
- NO-ISSUE: Pass internalOpenShiftApiUrl from values to api-config CM (#680) (Rastislav Wagner)
- EDM-424: add update policy api and validation (Sam Batschelet)
- EDM-420: Increase DB parameters (#669) (Gregory Shilin)
- NO-ISSUE: Append UI port to valid redirect URIs (rawagner)
- EDM-390: Add decommissioning route to device API (Lily Sturmann)
- EDM-417: Centralize API consts (Frank A. Zdarsky)
- NO-ISSUE: add command to prepare e2e test (sserafin)
- EDM-621: Fix microshift registration docs (Avishay Traeger)
- EDM-767: Actually update ignition mount path (Avishay Traeger)
- EDM-708: Reduce git access (Avishay Traeger)
- NO-ISSUE: Remove duplicated code in git helpers (Avishay Traeger)
- MGMT-17672: device: align update status phases (Sam Batschelet)
- Add developer documentation for field-selector (#658) (Assaf Albo)
- EDM-681: Allow field selector when 'summaryOnly' is enabled (#656) (Assaf Albo)
- EDM-704: Automate test 75991 (sserafin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: typo fix (Gregory Shilin)
- EDM-695: created a document with instructions to run devicesimulator (Gregory Shilin)
- EDM-695: Logger verbosity flag was added (-v) (#651) (Gregory Shilin)
- EDM-423: Fix lexer state for nested exists/notexists selectors (#655) (Assaf Albo)
- EDM-423: Adapt K8s lexer to support RHS equality symbol (asafbss)
- EDM-423: Modify k8s containment operator; remove support for 'in' and 'notin' on JSON fields (asafbss)
- EDM-423: Remove selector casting; implement a whitelist of selectors per resource for stricter filtering (asafbss)
- EDM-423: Move alias back to label in API while keeping it as a field in device model (asafbss)
- EDM-423: Add documentation for Field Selectors (asafbss)
- EDM-666: Updated selector names to match the documented API (asafbss)
- EDM-664: Added selector support for Spec field in field-selector (asafbss)
- EDM-423: Introduce Alias Field for Device Metadata (asafbss)
- EDM-423: Add more Kubernetes operators to enhance selectors for fields (asafbss)
- EDM-423: Kubernetes vanilla label selector (asafbss)
- NO-ISSUE: Fix linter and spellchecker issues (Frank A. Zdarsky)
- NO-ISSUE: Fix path-filter (Frank A. Zdarsky)
- EDM-694: Add Valkey key value store service (Ricardo Noriega)
- EDM-694: Use primary IP and nip.io domains (Ricardo Noriega)
- EDM-694: Add FlightCtl Network to slice (Ricardo Noriega)
- EDM-694: Add Makefile Quadlet targets for deploy and clean (Ricardo Noriega)
- EDM-694: Initial FlightCtl deployment with Quadlets (Ricardo Noriega)
- NO-ISSUE: Update config storage API (Avishay Traeger)
- EDM-578: Remove templateversion populate task (Avishay Traeger)
- EDM-582: Freeze HTTP configurations (Avishay Traeger)
- EDM-583: Freeze k8s secret configurations (Avishay Traeger)
- EDM-581: Freeze git configurations (Avishay Traeger)
- NO-ISSUE: Remove device's TV annotation if removed from fleet (Avishay Traeger)
- EDM-580: Deploy Valkey for frozen configurations (Avishay Traeger)
- EDM-578: Separate fleet validate and device render logic (Avishay Traeger)
- EDM-420: Enable to run devicesimulator on multiple hosts (#650) (Gregory Shilin)
- NO-ISSUE: Improve UpdateDeviceWithRetries to handle all errors (Miguel Angel Ajo)
- EDM-446: device/fileio: ensure readable paths in PathExists (Sam Batschelet)
- EDM-656: agent: clarify completed status (Sam Batschelet)
- EDM-656: agent: ensure Shutdown is threadsafe (Sam Batschelet)
- EDM-656: agent/device improve systemd status reporting (Sam Batschelet)
- NO-ISSUE: console: simplify exec test case (Sam Batschelet)
- NO-ISSUE: Update UI to v0.3.0 (Celia Amador)
- EDM-673: Enable exposing APIs via Gateway (rawagner)
- EDM-240: improve logging (Sam Batschelet)
- EDM-240: tests: add embeded application image (Sam Batschelet)
- EDM-240: applications: add support for embedded compose (Sam Batschelet)
- EDM-240: agent: add shutdown manager and improve graceful flow (Sam Batschelet)
- NO-ISSUE: Starting tests for the update lifecycle (Miguel Angel Ajo Pelayo)
- EDM-648: Fix integration tests (Ricardo Noriega)
- EDM-648: Refactor HTTP requests into helpers (Ricardo Noriega)
- EDM-648: Adding new HTTP repotester (Ricardo Noriega)
- EDM-648: Add validationSuffix API (Ricardo Noriega)
- NO-ISSUE: Prepare for 0.3.0-rc3 (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Redirect http keycloak to https (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Fixing stagging db resource tuning and route labels (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Fix keycloak-db-pvc.yaml label indent (Miguel Angel Ajo Pelayo)
- EDM-622: Fix local registry deploy targets (Ricardo Noriega De Soto)
- EDM-620: enable using specific rpm releases in e2e testing (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Update ui chart to 0.3.0-rc2 (Miguel Angel Ajo Pelayo)
- NO-ISSUE: device/bootstrap: unset NOTIFY_SOCKET after bootstrap (Sam Batschelet)
- NO-ISSUE: Fix docs path filter and linting issue (Frank A. Zdarsky)
- EDM-617: ignition: user,group ensure parse int (#624) (Sam Batschelet)
- EDM-240: docs: add compose requirements to Containerfile (#622) (Sam Batschelet)
- EDM-412: Fix podman build typo (Lily Sturmann)
- EDM-655: applications: reduce scope of events api (#621) (Sam Batschelet)
- NO-ISSUE: agent: console: adjust log levels (#620) (Sam Batschelet)
- NO-ISSUE: fix rabbitmq pv path (mparram)
- EDM-240: update applications documentation (#607) (Sam Batschelet)
- EDM-240: ensure network cleanup if the contianers are stopped (#617) (Sam Batschelet)
- EDM-642: EDM-240: add support for completed applications status (#612) (Sam Batschelet)
- EDM-650: Load k8s ca.crt when deployed on k8s (rawagner)
- EDM-587: Fix dev Kind deployment with auth enabled (rawagner)
- NO-ISSUE: fix link typo (Lily Sturmann)
- NO-ISSUE: Point helm to ui 0.3.0-rc1 (Miguel Angel Ajo Pelayo)
- MGMT-18170: Update documentation for certificate request (Lily Sturmann)
- EDM-623: Restore Prometheus default settings (#608) (Celia Amador)
- NO-ISSUE: Add support for match expressions (Ori Amizur)
- EDM-604: Improve error handling and messages for selector errors (asafbss)
- EDM-616: Fix 500 error when filtering devices using JSONB field selectors (asafbss)
- EDM-423: Improve error handling for SelectorError type (asafbss)
- EDM-423: Change description for fieldSelector API to improve clarity (asafbss)
- EDM-423: Refactor sorting functionality (asafbss)
- EDM-423: Refactor field selector for future enhanced operators integration (asafbss)
- EDM-423: Initial integration of field selector and orderby with service and store (asafbss)
- EDM-423: Initial integration of field selector with Kubernetes selectors (asafbss)
- EDM-423: Implement query-based filtering solution (asafbss)
- NO-ISSUE: ensure agent teardown on failure (#606) (Sam Batschelet)
- EDM-240: ensure application status (#595) (Sam Batschelet)
- EDM-513: Enable E2E on a target OpenShift deployment (Miguel Angel Ajo)
- EDM-619: Improve login error handling and merge skip-tls-insecure flags (#603) (Rastislav Wagner)
- NO-ISSUE: improve simulator logging (#605) (Sam Batschelet)
- NO-ISSUE: Fix links to UI image versions, not helm charts (Celia Amador)
- NO-ISSUE: Document how to modify the deployed UI version (Celia Amador)
- EDM-577: Added new CLI testcases (Samuel de la Cruz)
- NO-ISSUE: Fix nil pointer deref in agentserver when metrics == nil (vraiti)
- NO-ISSUE: Fix agent/api traffic instrumentation bug (#599) (vraiti)
- NO-ISSUE: Remove containers matchPattern from device spec (#596) (Sam Batschelet)
- EDM-613: Adapt examples to updated config API (Frank A. Zdarsky)
- EDM-613: Adapt to updated config API (Frank A. Zdarsky)
- EDM-613: Remove discriminator from config API (Frank A. Zdarsky)
- EDM-567: fix conditional workflows (Frank A. Zdarsky)
- EDM-601: Improve deployment experience on Kind (rawagner)
- NO-ISSUE: Move Prometheus components to e2e-extras (vraiti)
- NO-ISSUE: modify publish latest cli bins action to properly handle existing latest release (Dakota Crowder)
- EDM-609: EDM-608: ensure unique application names (#591) (Sam Batschelet)
- NO-ISSUE: Update golangci lint (#593) (Frank Zdarsky)
- EDM-531: Docs for ACM registration (#571) (Ricardo Noriega De Soto)
- NO-ISSUE: Update certificate request command in building-images.md (Lily Sturmann)
- EDM-595: Fix bug in csr-generate usage description (Lily Sturmann)
- EDM-595: Update help description formatting in CLI (Lily Sturmann)
- EDM-240: applications: add support for reconciliation and status repoting (#561) (Sam Batschelet)
- EDM-240: breaking: make application status data an array (#586) (Sam Batschelet)
- EDM-603: Add prometheus target filters (#590) (vraiti)
- EDM-463: Enable flightctl-api access to to ingress (#551) (Miguel Angel Ajo Pelayo)
- NO-ISSUE: fix nodeports references and prometheus default (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Cleanup helm install details (#574) (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Fix Prometheus Nodeport in Kind (#585) (vraiti)
- NO-ISSUE: Fix helm error on acm install (Miguel Angel Ajo)
- EDM-588: Fix link to UI and pass insecureSkipVerify flag for auth config (rawagner)
- NO-ISSUE: Move device/fleet spec comparison methods to api (Avishay Traeger)
- EDM-240: plumb applications API (#572) (Sam Batschelet)
- EDM-447: Add fleet policy in openapi (Ori Amizur)
- EDM-571: Support for setuid/setgid/sticky bits in inline config (Avishay Traeger)
- EDM-485: Update smoke test sim cmd (Dakota Crowder)
- NO-ISSUE: ensure enrollemnt requests are retried (#576) (Sam Batschelet)
- EDM-573: Run helm dependency build in release job (rawagner)
- MGMT-18708: use client-enrollment as name (Miguel Angel Ajo Pelayo)
- MGMT-18708: Retry API login and reduce agent intervals (Miguel Angel Ajo Pelayo)
- MGMT-17725: Align Prometheus components with values.kind.yaml (vraiti)
- MGMT-17725: Fix instrumentation audit workers (vraiti)
- MGMT-18708: Add certificate request command to CI (Lily Sturmann)
- MGMT-18708: Add single CLI command to obtain enrollment cert (Lily Sturmann)
- MGMT-18708: Add auto-approval for enrollment certificates (Lily Sturmann)
- MGMT-18708: Add 'enrollment' as valid signer (Lily Sturmann)
- MGMT-18708: Add handling for encrypted keys (Lily Sturmann)
- MGMT-17673: add image building docs (Frank A. Zdarsky)
- EDM-555: add resource monitor API validation (#563) (Sam Batschelet)
- EDM-567: Do not trigger full tests on docs changes (Frank A. Zdarsky)
- Reduce backoff durations and log slow API requests (#564) (Sam Batschelet)
- EDM-554: e2e images: enable podman.service (#562) (Sam Batschelet)
- MGMT-18458: EDM-295: EDM-296: Simplify helm charts and add UI helm chart as dependency (rawagner)
- EDM-563: Fleet list API should return device count only on demand (Avishay Traeger)
- EDM-546: Fix device spec comparisons (Avishay Traeger)
- EDM-511: Provide script to generate endpoint environment variables (Miguel Angel Ajo)
- MGMT-17725: Add Prometheus observability to Flightctl (vraiti)
- EDM-485: Add label arg for devices created by the device simulator (Dakota Crowder)
- MGMT-17725: Add observability instrumentation to flightctl API server (Vance Raiti)
- EDM-541: Move developer docs (#560) (Frank Zdarsky)
- EDM-540: Fix validateAgainstSchema causing 400 errors on non-nullable required status fields (asafbss)
- EDM-519: add better handling of obsolete files (#547) (Sam Batschelet)
- NO-ISSUE: Enable LTO to reduce binary size (Miguel Angel Ajo Pelayo)
- EDM-506: Enable static builds for CLI (#552) (Miguel Angel Ajo Pelayo)
- NO-ISSUE: Align openapi descriptions and user docs (Avishay Traeger)
- NO-ISSUE: Move GRPC consts to separate package (Avishay Traeger)
- EDM-455: Simplify inline config API (Avishay Traeger)
- NO-ISSUE: Remove gorm dep from flterrors (Avishay Traeger)
- EDM-458: Refine names and minor adjustments (asafbss)
- EDM-458: Suppress gocyclo lint warning for printTable function (asafbss)
- EDM-458: adapt integration tests for summary and type changes (asafbss)
- EDM-458: add support for SummaryOnly for listDevices API (asafbss)
- EDM-458: temporary adapt  the cli to support devices summary (asafbss)
- EDM-458: return 400 on limit error (asafbss)
- EDM-458: fix retrieving devices' statuses by kind fleet (asafbss)
- EDM-458: adding devices summary API (asafbss)
- EDM-427: Remove yaml dep (Dakota Crowder)
- EDM-427: Change yaml unmarshal when reading bootc status to use json (Dakota Crowder)
- EDM-427: Remove log (Dakota Crowder)
- MGMT-17672: Adding device and fleet management sections (Frank A. Zdarsky)
- EDM-427: Add additional test cases (Dakota Crowder)
- EDM-427: Scaffold tests for IsOsImageReconciled (Dakota Crowder)
- EDM-427: Modify IsOsImageReconciled to use target in its comparison (Dakota Crowder)
- NO-ISSUE: fix CLI version output (Frank A. Zdarsky)
- NO-ISSUE: more detailed CLI version info (Frank A. Zdarsky)
- EDM-427: Fix spelling err, add image digest status update to system info exporter (Dakota Crowder)
- EDM-507: Add -o wide to device table (Frank A. Zdarsky)
- EDM-427: Add setting diget in SetOSImage (Dakota Crowder)
- NO-ISSUE: Bump gorm.io/driver/postgres from 1.5.7 to 1.5.9 (dependabot[bot])
- EDM-427: Send image digest as a part of device os status update during bootstrap (Dakota Crowder)
- EDM-427: Add test cases with port (Dakota Crowder)
- EDM-299: make iamge required for ImageApplicationProvider (Sam Batschelet)
- EDM-299: add validation for applications API (Sam Batschelet)
- EDM-427: Use regex definition to parse imageinto base, tag, and digest (Dakota Crowder)
- EDM-427: Remove image type, add simple method for converting image to bootc target before swtich is called (Dakota Crowder)
- EDM-427: fix linting issue in test (Dakota Crowder)
- EDM-427: Report current booted os image digest when updating the device os status (Dakota Crowder)
- EDM-427: Fix bootstrap test (Dakota Crowder)
- EDM-427: remove imageDigest from spec, shift around some code in image package (Dakota Crowder)
- EDM-299: add device applications API (#441) (Sam Batschelet)
- EDM-452: Ensure tag releases for cli, stop recreating (Miguel Angel Ajo Pelayo)
- EDM-452: Ensure plain version tags for releases (Miguel Angel Ajo Pelayo)
- EDM-482: node-exporter conatainer failed to start due the Failed to open directory, disabling udev device properties (Ori Amizur)
- EDM-427: Separate out image pkg (Dakota Crowder)
- EDM-427: remove isOsSame (Dakota Crowder)
- EDM-427: update ensureImage flow to use Image type (Dakota Crowder)
- EDM-427: update checkRollback and IsRollingBack (Dakota Crowder)
- EDM-427: fix IsIOSUpdate, add bootc status to image func and update CheckOsRec (Dakota Crowder)
- EDM-427: add areImagesEquivalent func (Dakota Crowder)
- EDM-427: begin working towards shared Image struct intermediary to make comparisons between device os specs and bootc state easier to reason about (Dakota Crowder)
- EDM-462: refactored the tests to use testify suite through "go test". (Amir Yogev)
- EDM-462: dropped check for nil message + renamed console creation. (Amir Yogev)
- EDM-427: add imageDigest to device os spec and status, use optional digests in IsOSUpdate (Dakota Crowder)
- EDM-462: keep using bash as a test command and refined test cases with mock setup. (Amir Yogev)
- EDM-456: Update allowed callback urls in Kind deployment (#533) (Rastislav Wagner)
- EDM-462: not using bash as a test command + mock StreamClient.Recv(). (Amir Yogev)
- EDM-462: adding unit tests for console.go. (Amir Yogev)
- MGMT-18490: Add shell completion to CLI RPM (Vance Raiti)
- EDM-373: Style adjustments to getRenderedVersion (Dakota Crowder)
- EDM-373: Style adjustments to getNextRenderedVersion (Dakota Crowder)
- EDM-373: Style adjustments for pathFromType (Dakota Crowder)
- EDM-373: Fix spelling mistakes (Dakota Crowder)
- EDM-373: Remove a test case and consolidate logic (Dakota Crowder)
- EDM-373: Address linting issues w/ spec file (Dakota Crowder)
- EDM-373: Slight adjustments / cleanup for some tests (Dakota Crowder)
- NO-ISSUE: ensure cli builds on new tag (#521) (Sam Batschelet)
- EDM-373: Additional cases for GetDesired (Dakota Crowder)
- EDM-373: Begin adding tests for GetDesired (Dakota Crowder)
- EDM-298: Add user guide for deploying Flightctl on ACM (#510) (Rastislav Wagner)
- EDM-428: Remove interval and TPM fields from enrollmentconfig API (#522) (Rastislav Wagner)
- EDM-352: Add flow chart of for tasks in docs (Avishay Traeger)
- EDM-373: Add tests around request to get spec (Dakota Crowder)
- NO-ISSUE: agent: remove samber/lo as dep (Sam Batschelet)
- EDM-373: Add test cases for pathFromType, getNextRenderedVersion, getRenderedVersion (Dakota Crowder)
- EDM-373: Add tests for IsUpdating (Dakota Crowder)
- EDM-373: Add tests for Rollback and SetClient (Dakota Crowder)
- EDM-373: Write tests for PrepareRollback (Dakota Crowder)
- EDM-373: Adjust test names (Dakota Crowder)
- EDM-373: Add test coverage for additional methods, add bootc status err (Dakota Crowder)
- EDM-373: Move defined error types down into private write/read calls and have public interface wrap them (Dakota Crowder)
- EDM-373: Have writeRenderedToFile raise write specific err (Dakota Crowder)
- EDM-373: Add additional error types for reading (Dakota Crowder)
- NO-ISSUE:  Add support for builtin hooks (Ori Amizur)
- EDM-373: Add ErrCheckingFileExists (Dakota Crowder)
- EDM-373: Create an ErrWritingSpec shared error type (Dakota Crowder)
- EDM-373: Use shared error type and ErrorIs in existing specs (Dakota Crowder)
- EDM-373: Spec manager test coverage (#520) (DakCrowder)
- EDM-373: Remove fmt dep from test file (Dakota Crowder)
- EDM-373: Add spec manager unit tests for NewManager, Initialize, Ensure (Dakota Crowder)
- NO-ISSUE: Update version in docs (Celia Amador)

* Fri Feb 7 2025 Miguel Angel Ajo <majopela@redhat.com> - 0.4.0-1
- Add selinux support for console pty access

* Mon Nov 4 2024 Miguel Angel Ajo <majopela@redhat.com> - 0.3.0-1
- Move the Release field to -1 so we avoid auto generating packages
  with -5 all the time.
* Wed Aug 21 2024 Sam Batschelet <sbatsche@redhat.com> - 0.0.1-5
- Add must-gather script to provide a simple mechanism to collect agent debug
* Wed Aug 7 2024 Sam Batschelet <sbatsche@redhat.com> - 0.0.1-4
- Add basic greenboot support for failed flightctl-agent service
* Wed Mar 13 2024 Ricardo Noriega <rnoriega@redhat.com> - 0.0.1-3
- New specfile for both CLI and agent packages
