// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYX28buRH/KsS2DwogS47Pd2gNHFAnUHFq4pwRu+nD2RBG3JGWZy65IblyhUDfvRhy",
	"V9rVciX5mgTtm63l/J/f/Ib8knCdF1qhcja5+pJYnmEO/s9r59A6cEKrT2jEQnD/90f8XKJ1dCJFy40o",
	"6NfkKqk+MKfZis6v2f3tDYOdFpaCA/YsXMZchuwdrqXIMRwWaJJhUhhdoHECvQPAORZu5op8hoqbtTc0",
	"A7m0wfgCSumSq98SYyEZJsh58jjcc+q9sI7pBQu6MPU+7bQxkEtthMtyywYGP5fCYMrm69q5V8kwEQ5z",
	"b9GtC0yuEuuMUMtkM6x/AGNgTf83HM7AZjFXbQYXP/50op+k5Jt5aMVSCbXsyaf1KTUWCmt9blMLJ3pd",
	"Kf7Kjosn8rrbdW/A4k+XZ6i4TjFl19N3rCjnUnD2hGu2MDonp5Jh1wSXukxhicrNRNFVPL1lkKYGrWXa",
	"sExbpyBHipaa18v1xnXIVqGNa+X7r+fnF/uJvdXGMVXmczQvsiiUwyUaMomnJWxycr7wiaNxpyikc2Fe",
	"YFSR4tR1rSRUGG5rnkRwykqLKRvgaDkasgcSe0joD+T8IYnmvoZi214FxH2Tv7Qgt2csyAR7NoMf/nLZ",
	"Y1Lk4PE1WzUG5+wJ122kJR3z05trjx9wpaknY5Cm8tjTGy6fzwotBV936/WPu18/nC20yWk0pyxHsKXX",
	"qLVjlVBMIzqgAd6O4MumE8NNdZDBXJeu0btgGdlmQecLYnHSzuK9l9+/v2u2G1towyxyyh7XeV6qOn0D",
	"7WVARk18LrXDo61N082f9EwW02NwpXfVPlLsj9vDAXva/JHRYkrlRI6nlps6rBI5UGzfvDGM2ghM77YN",
	"ewCltgZq4JQe4NiyoPmIKSHHevVNBy5Gr7vWa5HtQlEY7TTXktU6IoaIAU/MGFX99u3H3mz5sodaEXnW",
	"TLVPMF0SaGDq4MjotFXPpjE8tDH1c//jNiI9/x25o/T07n620MpibPkLXwKD1JVoLn/NuDqrnkFbyrCB",
	"QpqKgNTbxhFnStyvfNMzFjSwFB0IaVkVSie0vWLVdmM5mBijTX/E/jOZjcTdu9LSHOmq+uX+/pZRnkrL",
	"/IkYnzdS1Ja+3iaMofepykESiSkY6QumciFHa2GJ0U7vaPRFWE9WIkXF8YWXA6zEWGmJEVYXo0umFZ7Z",
	"TLs2+13fTtlAArUTy8E6NGxuQPGMBaCGa4VCS4glSL3q5H5HXk3HPgSREBDjWjkQ1foqu5eXAgzk6NDY",
	"jvr/ds3o2yMqfs5pbEgRyy2N9MYpJvWyZyWgLx3xm9YC0C/cNy5vIgsEGzSYPjrplVb8OOPyDKREtUQW",
	"zn9L6j7Co13irIKsWgfsoXBp6sLT8etLo+He4bpPEx7XNFGpNjY0xAFNfdFSvl4a5d5sDYWpK93Yw7fZ",
	"iE3d8EMTQoFM9+ZVPTjoOBuAfIa1ZQ909iHxm9Te28Nxd/3XYZgSjycMutOYsD3StvOuNdsOzbVX34VC",
	"IkzaHXBcgshfSNFvvQzDfzsDnOasTwptuXUqYiy1ACFLgxFH6weHFUiRBnfrw2wgFgzUuvWucMjTntbb",
	"vTl4I10f/pWhy9C0omAFWNp423UlOz97LUO2AGnxZ6H8v41unGstEVScXPvo+u44UTdbu2qIStvwwNZD",
	"kkItdGg05YB7vsEchCQoIuR/W0ixzBx3ciQ0wRty0nCfIfu7/8LeauWMluwegZBbGhLNnCvs1Xjckt7s",
	"90u9QH2qFijP+1wKmmKE6raF0YO6z4T1h54NFHbvztf71MgsmpXgGJsUrRqOHmhXlYJjhfUq2usCeIbs",
	"YnTeCfD5+XkE/vNIm+W4krXj99O3kw93k7OL0fkoc7n0HSecJHV7iYtlIRkm2ytRsno9RwevSYUuUEEh",
	"kqvkh9G5vx4V4DLfM+PVxej12F847PhLdRFJN/Sp0LFF4tMfebZlg7nU/IlWJg7SX68JaV50mm61NpjN",
	"+7jdo65+23fjn0p8LpERslwwUV+NU/RVm6Nf0LxGvzgJEqO4d/1Yh5s0oRCAH964I8+Om8dwGK17o9N1",
	"DQJUPldQFLJqi/HvNlxNd6r+bHCRXCV/Gu/e08fVY/r4yEv6po1XcjIMa88jvpQX5+ff3puK0bw7e1eM",
	"HngQ3gqJVITNMLn8ik62L18Rl95AyupLxRmbhrnaaVty68fv6dZUOTR0FbtDs0LDvEAY7rC0/n2gAYRH",
	"+kAwvRyHW9F4S4svBemWiQbRC9QwbCLXt9M+gE52hPwtMBC/J37n1u/Z4SJ1nEQ3tf+1dt8W/f+j12mj",
	"8UfD1A+8OU5o7FYS+83+a92o9ihVs5WAmpxGDR5ouLB53PwnAAD//+PtAJfwHAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
