// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYX28buRH/KsS2DwogS44vObQGDqgTqDg1cc6I3fThbAgj7kjLM5fckFy5QqDvXgy5",
	"K+1quZJ8PQftm63l/J/f/Ib8lnCdF1qhcja5/JZYnmEO/s8r59A6cEKrL2jEQnD/92f8WqJ1dCJFy40o",
	"6NfkMqk+MKfZis6v2d3NNYOdFpaCA/YkXMZchuwDrqXIMRwWaJJhUhhdoHECvQPAORZu5op8hoqbtTc0",
	"A7m0wfgCSumSy18TYyEZJsh58jDcc+qjsI7pBQu6MPU+7bQxkEtthMtyywYGv5bCYMrm69q5V8kwEQ5z",
	"b9GtC0wuE+uMUMtkM6x/AGNgTf83HM7AZjFXbQYXb3880U9S8mIeWrFUQi178ml9So2Fwlqf29TCiV5X",
	"iv9gx8Ujed3tundg8cc3Z6i4TjFlV9MPrCjnUnD2iGu2MDonp5Jh1wSXukxhicrNRNFVPL1hkKYGrWXa",
	"sExbpyBHipaa18v1xnXIVqGNa+X7r+fnF/uJvdHGMVXmczTPsiiUwyUaMomnJWxycr7wkaNxpyikc2Fe",
	"YFSR4tR1rSRUGG5rnkRwykqLKRvgaDkasnsSu0/oD+T8PonmvoZi214FxH2TP7cgt2csyAR7NoMf/vKm",
	"x6TIweNrtmoMztkjrttISzrmp9dXHj/gSlNPxiBN5bGnN1w+nxVaCr7u1usft798Oltok9NoTlmOYEuv",
	"UWvHKqGYRnRAA7wdwbdNJ4br6iCDuS5do3fBMrLNgs5nxOKkncV7L7/7eNtsN7bQhlnklD2u87xUdfoG",
	"2suAjJr4WmqHR1ubpps/6ZkspsfgSu+qfaTYn7eHA/a0+T2jxZTKiRxPLTd1WCVyoNi+eWMYtRGY3m4b",
	"9gBKbQ3UwCk9wLFlQfMRU0KO9eqbDlyMXnet1yLbhaIw2mmuJat1RAwRA56YMar6zfvPvdnyZQ+1IvKs",
	"mWqfYLok0MDUwZHRaaueTWN4aGPq5/6HbUR6/htyR+np3f1soZXF2PIXvgQGqSvRXP6acXVWPYO2lGED",
	"hTQVAak3jSPOlLhf+aZnLGhgKToQ0rIqlE5oe8Wq7cZyMDFGm/6I/WcyG4m7d6WlOdJV9fPd3Q2jPJWW",
	"+RMxPm+kqC19tU0YQ+9TlYMkElMw0hdM5UKO1sISo53e0eiLsJ6sRIqK4zMvB1iJsdISI6wuRm+ZVnhm",
	"M+3a7Hd1M2UDCdROLAfr0LC5AcUzFoAarhUKLSGWIPWqk/sdeTUd+xREQkCMa+VAVOur7F5eCjCQo0Nj",
	"O+r/2zWjb4+o+DmnsSFFLLc00hunmNTLnpWAvnTEr1sLQL9w37i8jiwQbNBg+uikV1rx44zLM5AS1RJZ",
	"OP+S1H2ER7vEWQVZtQ7YQ+HS1IXH49eXRsN9wHWfJjyuaaJSbWxoiAOa+qKlfD03yr3ZGgpTV7qxh2+z",
	"EZu64YcmhAKZ7s2renDQcTYA+QRry+7p7H3iN6m9t4fj7vqvwzAlHk4YdKcxYXukbedda7YdmmuvvguF",
	"RJi0O+C4BJE/k6LfexmG/3YGOM1ZnxTacutUxFhqAUKWBiOO1g8OK5AiDe7Wh9lALBiodetd4ZCnPa23",
	"e3PwRro+/CtDl6FpRcEKsLTxtutKdn7yWoZsAdLiT0L5fxvdONdaIqg4ufbR9e1xom62dtUQlbbhga2H",
	"JIVa6NBoygH3fIM5CElQRMj/tpBimTnu5EhogjfkpOEuQ/Z3/4W918oZLdkdAiG3NCSaOVfYy/G4Jb3Z",
	"75d6gfpSLVCe97kUNMUI1W0Lo3t1lwnrDz0ZKOzena/3qZFZNCvBMTYpWjUc3dOuKgXHCutVtFcF8AzZ",
	"xei8E+DT09MI/OeRNstxJWvHH6fvJ59uJ2cXo/NR5nLpO044Ser2EhfLQjJMtleiZPV6jg5ekwpdoIJC",
	"JJfJD6Nzfz0qwGW+Z8ari9Hrsb9w2PG36iKSbuhToWOLxJff82zLBnOp+SOtTBykv14T0rzoNN1qbTCb",
	"93G7R13+uu/GP5X4WiIjZLlgor4ap+irNke/oHmNfnESJEZx7/qxDjdpQiEAP7xxR54dNw/hMFr3Tqfr",
	"GgSofK6gKGTVFuPfbLia7lT92eAiuUz+NN69p4+rx/TxkZf0TRuv5GQY1p5HfCkvzs9f3puK0bw7e1eM",
	"HngQ3gqJVITNMHnzBzrZvnxFXHoHKasvFWdsGuZqp23Jrbff062pcmjoKnaLZoWGeYEw3GFp/ftAAwgP",
	"9IFg+nYcbkXjLS0+F6RbJhpEL1DDsIlc3Uz7ADrZEfJLYCB+T/zOrd+zw0XqOIluav9r7b4t+v9Hr9NG",
	"44+GqR94c5zQ2K0k9pv9l7pR7VGqZisBNTmNGjzQcGHzsPlPAAAA//9cF+AD8BwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
