// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWW2/jNhP9KwS/7yEFHCnJZheFnuoEWay7t2Dt5mUTBDQ1lrjhRSFHDozA/70gKSWy",
	"LG3Sou2TZXHmzIVnjuaRcqMqo0Gjo9kjdbwExcLjFBEcMhRGX4EVK8HD8ze4r8Ght8jBcSsq/5ZmtDkg",
	"aMja22/I4vIzYc8oJGfIyIPAkmAJ5CNspFAQjQVYOqGVNRVYFBASYOLuFiu1H+mMOXh3egiamxxyMp19",
	"JFW9lIKTO9iQlTXKh6YTipsKaEYdWqELup1QeB3ixV8A5GDxNYDeLjYRBoE0v2WyiEgrVkukGbWO0UkP",
	"+UJzuwl/CJOFsQJLRWoHOTmApEgm5Nq7XVP/AJxf01+GwpXMlfvxXMlO3r7bC/mBuXI0WPSJ8VzJ3vx6",
	"OhJSLW8rIwXf7Hfr9/nXL4crY5VnS04UMFdbyMnSGCSN0xAiSnc73H+1+DTvtpysjCUOeG2BcKNUrRs6",
	"kwMTfJgcTPq+NggvXq8nerAMFB/CsbVGoeC1HZh9npLG5Sf1O1HoQdK4Ad7MRaEZ+vp/QhvXMsc6Vjk3",
	"cpNYqdcW4jtzef5ttAjfGrivhYWcZt+fRv7mydAsfwBHH3VUj1xltIMhQYoncYBbuekK0rqDsyc/Flwt",
	"oyru4najk2hFPGLtnns5rzkH30D/5z0TEvLBZvbqb2MO1X9hrbHj1YZjn85AzaMS6+m7D/VhsbhsKwoW",
	"T9kIjVCADYwea880z0WcKAIhpxyQCenoQE0xyFgxTQoKnGMFDDavh+hfCb0ysTaNjAdtAMWEpBlFYOq3",
	"lRRFiRxlIgydUM2UR1iUQN6HE3JuNFojyQKYohNaW+9aIlYuS9Md721/yNqGXzUNJ9PLGeFSgMagQLsR",
	"kmu9KIULRg+WVa4nTaOfSuLArgWPqtb/ynZJnVx7XkvBoeFMU+20YrwEcpIc7RX48PCQsHCcGFukja9L",
	"P83OL77MLw5PkqOkRCWDEAiUHq7XuKEu0Aldg3WxTevjJSA79hCmAs0qQTP6JjlKjj1DGZaBEun6JDlO",
	"WeF3k/Qx/N6KfOuPKjO0gVz9nbWDHCyl4XdCF4QzGb4CfkKC6yx/Qu2oT8jRMgUI1tHsez+NP7S4r4GI",
	"HDTGEP6afOwcwq0twUeLKUJOPWVpFup+5mNbLu0KBNoaJs2O5svvz8NNNAaHZybftEMAOvSKVZVsaJH+",
	"cD7Txw7U/y2saEb/lz7vg2mzDKYvbILbXRXzSUZ9CEoUrvLk6Ojfz6ZRxpBOT5JGxsPPWyXBX8J2Qk//",
	"wSR3xXogpTOWk3ZjPiQzvWZS5Hu09Wm9/S/TmmkE66V7DnYNlgSHqLSscOET3RmEm4DggmmchKglKfVU",
	"bDz64/G1nS73onyRtWDtwCad2eiksL3Z/hkAAP//je3bdMQMAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
