// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

// AttestationVerificationRequest Request to verify TPM attestation data with the Keylime verifier
type AttestationVerificationRequest struct {
	// AikTpm Base64-encoded AIK public key from TPM
	AikTpm string `json:"aik_tpm"`

	// EkTpm Base64-encoded EK public key from TPM
	EkTpm *string `json:"ek_tpm,omitempty"`

	// Ekcert Base64-encoded EK certificate
	Ekcert *string `json:"ekcert,omitempty"`

	// EncAlg Encryption algorithm used (e.g., "rsa", "ecc")
	EncAlg *string `json:"enc_alg,omitempty"`

	// HashAlg Hash algorithm used (e.g., "sha256", "sha384")
	HashAlg *string `json:"hash_alg,omitempty"`

	// MbPolicy JSON-formatted measured boot policy
	MbPolicy *string `json:"mb_policy,omitempty"`

	// MtlsCert mTLS certificate for secure communication (optional)
	MtlsCert *string `json:"mtls_cert,omitempty"`

	// Quote Base64-encoded TPM quote data
	Quote *string `json:"quote,omitempty"`

	// RuntimePolicy JSON-formatted IMA runtime policy
	RuntimePolicy *string `json:"runtime_policy,omitempty"`

	// SignAlg Signature algorithm used (e.g., "rsassa", "rsapss")
	SignAlg *string `json:"sign_alg,omitempty"`

	// TpmPolicy JSON-formatted TPM PCR policy
	TpmPolicy *string `json:"tpm_policy,omitempty"`
}

// AttestationVerificationResponse Response from Keylime attestation verification
type AttestationVerificationResponse struct {
	// Results Verification result status (e.g., "Success", "Failed")
	Results string `json:"results"`
}

// ErrorResponse Error response from Keylime verifier
type ErrorResponse struct {
	// Code HTTP status code
	Code *int `json:"code,omitempty"`

	// Results Additional error details
	Results *map[string]interface{} `json:"results,omitempty"`

	// Status Error status message
	Status *string `json:"status,omitempty"`
}

// VerifyAttestationJSONRequestBody defines body for VerifyAttestation for application/json ContentType.
type VerifyAttestationJSONRequestBody = AttestationVerificationRequest
